-- Decouple operational conversation lifecycle from lead/client linkage.
-- Stored InquiryState remains backward-compatible (NEW / IN_WORK / SPAM are operational),
-- while WAITING_CLIENT and CLOSED are represented by answered + metadata.

-- Historical linkage statuses become ordinary active conversations.
UPDATE "CommunicationInquiry"
   SET "state"='IN_WORK'::"InquiryState",
       "updatedAt"=CURRENT_TIMESTAMP
 WHERE "state"::text IN ('CONVERTED', 'LINKED');

-- Rebuild message synchronization so lifecycle follows the actual conversation:
-- inbound -> needs employee action; successful outbound -> waiting for client.
CREATE OR REPLACE FUNCTION turbolev_sync_message_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."direction"::text = 'IN' THEN
    UPDATE "CommunicationInquiry"
       SET "answered"=false,
           "unread"=true,
           "state"=CASE
             WHEN "state"::text='SPAM' THEN "state"
             WHEN "state"::text='NEW' THEN "state"
             ELSE 'IN_WORK'::"InquiryState"
           END,
           "metadata"=COALESCE("metadata", '{}'::jsonb) - 'lifecycleClosedAt',
           "lastInboundAt"=COALESCE(NEW."sentAt", CURRENT_TIMESTAMP),
           "updatedAt"=CURRENT_TIMESTAMP
     WHERE "id"=NEW."inquiryId";
  ELSIF NEW."direction"::text = 'OUT'
        AND COALESCE(NEW."deliveryStatus", '') IN ('SENT','DELIVERED','READ','CRM_ONLY') THEN
    UPDATE "CommunicationInquiry"
       SET "answered"=true,
           "unread"=false,
           "state"=CASE WHEN "state"::text='SPAM' THEN "state" ELSE 'IN_WORK'::"InquiryState" END,
           "metadata"=COALESCE("metadata", '{}'::jsonb) - 'lifecycleClosedAt',
           "lastOutboundAt"=COALESCE(NEW."sentAt", CURRENT_TIMESTAMP),
           "updatedAt"=CURRENT_TIMESTAMP
     WHERE "id"=NEW."inquiryId";
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "CommunicationMessage_task_after_insert" ON "CommunicationMessage";
CREATE TRIGGER "CommunicationMessage_task_after_insert"
AFTER INSERT ON "CommunicationMessage"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_message_task();

DROP TRIGGER IF EXISTS "CommunicationMessage_task_after_delivery_update" ON "CommunicationMessage";
CREATE TRIGGER "CommunicationMessage_task_after_delivery_update"
AFTER UPDATE OF "deliveryStatus" ON "CommunicationMessage"
FOR EACH ROW
WHEN (OLD."deliveryStatus" IS DISTINCT FROM NEW."deliveryStatus")
EXECUTE FUNCTION turbolev_sync_message_task();

-- Keep inquiry task semantics aligned with the virtual lifecycle:
-- only NEW/IN_WORK + unanswered conversations require action.
CREATE OR REPLACE FUNCTION turbolev_sync_inquiry_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'inquiry:' || NEW."id" || ':active';
  task_title TEXT;
BEGIN
  IF NEW."assignedUserId" IS NOT NULL
     AND NEW."state"::text IN ('NEW','IN_WORK')
     AND NEW."answered" = false
     AND NOT (COALESCE(NEW."metadata", '{}'::jsonb) ? 'lifecycleClosedAt') THEN
    task_title := CASE WHEN NEW."state"::text = 'NEW'
      THEN 'Опрацювати нове звернення: '
      ELSE 'Відповісти клієнту: '
    END || LEFT(COALESCE(NULLIF(BTRIM(NEW."subject"), ''), 'без теми'), 170);

    INSERT INTO "CrmTask" (
      "id", "title", "status", "priority", "assignedUserId", "dueAt",
      "sourceType", "sourceId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
    ) VALUES (
      turbolev_task_id(NEW."id"), task_title, 'OPEN',
      CASE WHEN NEW."channel"::text = 'BINOTEL' AND LOWER(COALESCE(NEW."subject", '') || ' ' || COALESCE(NEW."preview", '')) LIKE '%пропущ%' THEN 'CRITICAL' ELSE 'HIGH' END,
      NEW."assignedUserId", NEW."receivedAt" + INTERVAL '15 minutes',
      'INQUIRY', NEW."id", true, task_key,
      jsonb_build_object('channel', NEW."channel"::text), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
    ON CONFLICT ("dedupeKey") DO UPDATE SET
      "title" = EXCLUDED."title",
      "status" = 'OPEN',
      "priority" = EXCLUDED."priority",
      "assignedUserId" = EXCLUDED."assignedUserId",
      "dueAt" = EXCLUDED."dueAt",
      "completedAt" = NULL,
      "metadata" = EXCLUDED."metadata",
      "updatedAt" = CURRENT_TIMESTAMP;
  ELSE
    UPDATE "CrmTask"
       SET "status"='DONE', "completedAt"=COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt"=CURRENT_TIMESTAMP
     WHERE "dedupeKey"=task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;

  RETURN NEW;
END;
$$;

-- metadata changes now also participate in task synchronization, so manual CLOSE
-- immediately closes the employee's outstanding inquiry task.
DROP TRIGGER IF EXISTS "CommunicationInquiry_task_after_update" ON "CommunicationInquiry";
CREATE TRIGGER "CommunicationInquiry_task_after_update"
AFTER UPDATE OF "state", "assignedUserId", "answered", "receivedAt", "subject", "metadata" ON "CommunicationInquiry"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_inquiry_task();
