import "server-only";

import {
  FinancialObligationDirection,
  FinancialObligationStatus,
  InquiryState,
  PayrollPeriodStatus,
  PlannerAppointmentStatus,
  SalaryAccrualStatus,
  SupplierConnectionStatus,
  SupplierOrderStatus,
} from "@/src/generated/prisma/client";
import { getPrisma } from "@/src/lib/prisma";

const DAY_MS = 86_400_000;
const MINUTE_MS = 60_000;
const KYIV_TZ = "Europe/Kyiv";

export type AttentionCategory =
  | "COMMUNICATIONS"
  | "SERVICE"
  | "DIAGNOSTICS"
  | "PARTS"
  | "SUPPLIERS"
  | "FINANCE"
  | "PAYROLL"
  | "POSTS"
  | "QUALITY"
  | "WARRANTY"
  | "MANUAL";

export type AttentionLevel = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
export type AttentionBucket = "ACTION" | "WAITING" | "MONITORING";

export type AttentionAction = {
  label: string;
  section: string;
  params?: Record<string, string>;
};

export type AttentionSignal = {
  id: string;
  sourceType: string;
  sourceId: string | null;
  taskId: string | null;
  title: string;
  description: string | null;
  reason: string;
  category: AttentionCategory;
  level: AttentionLevel;
  bucket: AttentionBucket;
  dueAt: string | null;
  occurredAt: string;
  isOverdue: boolean;
  overdueMinutes: number;
  isToday: boolean;
  autoGenerated: boolean;
  amount: number | null;
  currency: string | null;
  counterparty: string | null;
  action: AttentionAction | null;
  metadata: Record<string, unknown>;
};

export type PostLoadPost = {
  id: string;
  name: string;
  locationId: string;
  locationName: string;
  utilizationPct: number;
  bookedHours: number;
  capacityHours: number;
};

export type PostLoadPeriod = {
  date: string;
  utilizationPct: number;
  bookedHours: number;
  capacityHours: number;
  activePosts: number;
  posts: PostLoadPost[];
};

export type AttentionCenterResult = {
  signals: AttentionSignal[];
  summary: {
    total: number;
    critical: number;
    overdue: number;
    action: number;
    waiting: number;
    today: number;
  };
  categories: Record<AttentionCategory, number>;
  postLoad: {
    today: PostLoadPeriod | null;
    tomorrow: PostLoadPeriod | null;
  };
  generatedAt: string;
};

type TaskLike = {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  dueAt: Date | null;
  sourceType: string;
  sourceId: string | null;
  clientId: string | null;
  vehicleId: string | null;
  metadata: unknown;
  autoGenerated: boolean;
  createdAt: Date;
};

export type AttentionCenterOptions = {
  userId: string;
  tasks: TaskLike[];
  canCommunications: boolean;
  canPlanner: boolean;
  canProcurement: boolean;
  canFinance: boolean;
  canPayrollNetwork: boolean;
  plannerLocationIds: string[] | null;
  procurementLocationIds: string[] | null;
  financeLocationIds: string[] | null;
};

const activeAppointmentStatuses: PlannerAppointmentStatus[] = [
  PlannerAppointmentStatus.BOOKED,
  PlannerAppointmentStatus.ARRIVED,
  PlannerAppointmentStatus.DIAGNOSTICS,
  PlannerAppointmentStatus.WAITING_PARTS_SELECTION,
  PlannerAppointmentStatus.WAITING_CALCULATION,
  PlannerAppointmentStatus.WAITING_APPROVAL,
  PlannerAppointmentStatus.WAITING_PARTS,
  PlannerAppointmentStatus.READY_FOR_REPAIR,
  PlannerAppointmentStatus.IN_REPAIR,
  PlannerAppointmentStatus.WAITING_QC,
  PlannerAppointmentStatus.WAITING_PAYMENT,
  PlannerAppointmentStatus.READY_FOR_PICKUP,
  PlannerAppointmentStatus.WARRANTY,
  PlannerAppointmentStatus.PAUSED,
];

function numberOf(value: unknown) {
  const numeric = Number(value ?? 0);
  return Number.isFinite(numeric) ? numeric : 0;
}

function round(value: number, digits = 1) {
  const scale = 10 ** digits;
  return Math.round((value + Number.EPSILON) * scale) / scale;
}

function dateIso(value: Date | null | undefined) {
  return value ? value.toISOString() : null;
}

function ageMinutes(date: Date, now: Date) {
  return Math.max(0, Math.floor((now.getTime() - date.getTime()) / MINUTE_MS));
}

function minutesLate(dueAt: Date | null, now: Date) {
  if (!dueAt || dueAt.getTime() >= now.getTime()) return 0;
  return Math.max(1, Math.floor((now.getTime() - dueAt.getTime()) / MINUTE_MS));
}

function kyivParts(date = new Date()) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: KYIV_TZ,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(date);
  return {
    year: Number(parts.find((part) => part.type === "year")?.value),
    month: Number(parts.find((part) => part.type === "month")?.value),
    day: Number(parts.find((part) => part.type === "day")?.value),
  };
}

function kyivOffsetMinutes(date: Date) {
  const value = new Intl.DateTimeFormat("en-US", {
    timeZone: KYIV_TZ,
    timeZoneName: "shortOffset",
    hour: "2-digit",
  }).formatToParts(date).find((part) => part.type === "timeZoneName")?.value;
  const match = value?.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);
  if (!match) return 180;
  const minutes = Number(match[2]) * 60 + Number(match[3] || 0);
  return match[1] === "+" ? minutes : -minutes;
}

function kyivDateStartUtc(year: number, month: number, day: number) {
  const probe = new Date(Date.UTC(year, month - 1, day, 12));
  const offset = kyivOffsetMinutes(probe);
  return new Date(Date.UTC(year, month - 1, day, 0, -offset));
}

function kyivDay(offsetDays = 0) {
  const now = kyivParts(new Date(Date.now() + offsetDays * DAY_MS));
  const start = kyivDateStartUtc(now.year, now.month, now.day);
  const nextProbe = new Date(Date.UTC(now.year, now.month - 1, now.day + 1, 12));
  const next = kyivParts(nextProbe);
  const end = kyivDateStartUtc(next.year, next.month, next.day);
  return { start, end };
}

function kyivDayKey(date: Date) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: KYIV_TZ,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

function sameKyivDay(a: Date, b: Date) {
  return kyivDayKey(a) === kyivDayKey(b);
}

function metadataRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function metadataText(value: unknown, key: string) {
  const record = metadataRecord(value);
  const raw = record[key];
  return typeof raw === "string" && raw.trim() ? raw.trim() : null;
}

function isMissedCallTask(task: TaskLike) {
  if (task.sourceType !== "INQUIRY") return false;
  const metadata = metadataRecord(task.metadata);
  const callStatus = typeof metadata.callStatus === "string" ? metadata.callStatus.toUpperCase() : "";
  if (callStatus === "MISSED" || callStatus === "BUSY" || metadata.missedCall === true || metadata.answered === false) return true;
  const text = `${task.title} ${task.description || ""}`.toLocaleLowerCase("uk-UA");
  return text.includes("пропущен") || text.includes("пропущений дзвінок")
    || (String(metadata.channel || "").toUpperCase() === "BINOTEL"
      && (text.includes("не з'єдна") || text.includes("не з’єдна")));
}

function isMissedCallInquiry(item: {
  channel: string;
  subject: string | null;
  preview: string | null;
  answered: boolean | null;
  metadata: unknown;
}) {
  const metadata = metadataRecord(item.metadata);
  const callStatus = typeof metadata.callStatus === "string" ? metadata.callStatus.toUpperCase() : "";
  if (callStatus === "MISSED" || callStatus === "BUSY" || metadata.missedCall === true) return true;
  if (item.channel !== "BINOTEL") return false;
  if (item.answered === false) return true;
  const text = `${item.subject || ""} ${item.preview || ""}`.toLocaleLowerCase("uk-UA");
  return text.includes("пропущ") || text.includes("не з'єдна") || text.includes("не з’єдна");
}

function categoryForTask(sourceType: string): AttentionCategory {
  if (sourceType === "INQUIRY" || sourceType === "LEAD") return "COMMUNICATIONS";
  if (sourceType === "APPOINTMENT" || sourceType === "WORK_ORDER") return "SERVICE";
  if (sourceType === "DIAGNOSTIC") return "DIAGNOSTICS";
  if (sourceType === "PARTS_REQUEST") return "PARTS";
  if (sourceType === "PAYMENT") return "FINANCE";
  if (sourceType === "QC") return "QUALITY";
  if (sourceType === "WARRANTY") return "WARRANTY";
  if (sourceType === "ESTIMATE") return "SERVICE";
  return "MANUAL";
}

function taskBucket(task: TaskLike): AttentionBucket {
  const status = metadataText(task.metadata, "status") || "";
  if (task.sourceType === "ESTIMATE") return "WAITING";
  if (task.sourceType === "PARTS_REQUEST" && ["SELECTED", "WAITING_APPROVAL", "ORDERED", "PARTIALLY_RECEIVED"].includes(status)) return "WAITING";
  return "ACTION";
}

function taskAction(task: TaskLike): AttentionAction | null {
  const workOrderId = metadataText(task.metadata, "workOrderId") || (task.sourceType === "WORK_ORDER" ? task.sourceId : null);
  const workOrderTab = metadataText(task.metadata, "workOrderTab");
  if (task.sourceType === "INQUIRY") return { label: "Опрацювати", section: "Нові звернення" };
  if (task.sourceType === "LEAD") return { label: "Відкрити", section: "Активні" };
  if (task.sourceType === "APPOINTMENT") return { label: "Відкрити запис", section: "Планувальник", params: task.sourceId ? { appointmentId: task.sourceId } : undefined };
  if (task.sourceType === "DIAGNOSTIC") {
    if (workOrderId) return { label: "Відкрити", section: "Комерційна пропозиція", params: { workOrderId, workOrderTab: workOrderTab || "diagnostic" } };
    return { label: "Відкрити діагностику", section: "Діагностика", params: task.vehicleId ? { vehicleId: task.vehicleId } : undefined };
  }
  if (task.sourceType === "ESTIMATE") return { label: "Відкрити кошторис", section: "Комерційна пропозиція", params: workOrderId ? { workOrderId, workOrderTab: workOrderTab || "estimate" } : undefined };
  if (task.sourceType === "WORK_ORDER") return { label: "Відкрити КП", section: "Комерційна пропозиція", params: workOrderId ? { workOrderId, workOrderTab: workOrderTab || "overview" } : undefined };
  if (task.sourceType === "PARTS_REQUEST") return workOrderId
    ? { label: "Відкрити запчастини", section: "Комерційна пропозиція", params: { workOrderId, workOrderTab: workOrderTab || "parts" } }
    : { label: "Відкрити підбір", section: "Підбір запчастин", params: task.vehicleId ? { vehicleId: task.vehicleId } : undefined };
  if (task.sourceType === "PAYMENT") return workOrderId
    ? { label: "Відкрити оплату", section: "Комерційна пропозиція", params: { workOrderId, workOrderTab: workOrderTab || "payment" } }
    : { label: "Відкрити оплати", section: "Оплати" };
  if (task.sourceType === "QC") return workOrderId
    ? { label: "Відкрити контроль", section: "Комерційна пропозиція", params: { workOrderId, workOrderTab: workOrderTab || "qc" } }
    : { label: "Відкрити контроль", section: "Комерційна пропозиція", params: { scope: "qc" } };
  if (task.sourceType === "WARRANTY") return workOrderId
    ? { label: "Відкрити гарантію", section: "Комерційна пропозиція", params: { workOrderId, workOrderTab: workOrderTab || "history" } }
    : { label: "Відкрити гарантії", section: "Комерційна пропозиція", params: { scope: "warranty" } };
  return null;
}

function taskLevel(task: TaskLike, now: Date): AttentionLevel {
  if (task.priority === "CRITICAL") return "CRITICAL";
  const late = minutesLate(task.dueAt, now);
  if (late >= 24 * 60) return "CRITICAL";
  if (late > 0 || task.priority === "HIGH") return "HIGH";
  if (task.priority === "LOW") return "LOW";
  return "MEDIUM";
}

function taskSignal(task: TaskLike, now: Date): AttentionSignal {
  const overdue = minutesLate(task.dueAt, now);
  return {
    id: `task:${task.id}`,
    sourceType: task.sourceType,
    sourceId: task.sourceId,
    taskId: task.id,
    title: task.title,
    description: task.description,
    reason: task.autoGenerated ? "CRM автоматично контролює цей етап бізнес-процесу." : "Ручна задача, яку потрібно виконати або перевести в роботу.",
    category: categoryForTask(task.sourceType),
    level: taskLevel(task, now),
    bucket: taskBucket(task),
    dueAt: dateIso(task.dueAt),
    occurredAt: task.createdAt.toISOString(),
    isOverdue: overdue > 0,
    overdueMinutes: overdue,
    isToday: Boolean(task.dueAt && sameKyivDay(task.dueAt, now)),
    autoGenerated: task.autoGenerated,
    amount: null,
    currency: null,
    counterparty: null,
    action: taskAction(task),
    metadata: { ...metadataRecord(task.metadata), status: task.status, clientId: task.clientId, vehicleId: task.vehicleId },
  };
}

function signal(input: Omit<AttentionSignal, "isOverdue" | "overdueMinutes" | "isToday"> & { dueDate?: Date | null }, now: Date): AttentionSignal {
  const dueDate = input.dueDate ?? (input.dueAt ? new Date(input.dueAt) : null);
  const overdue = minutesLate(dueDate, now);
  const { dueDate: _dueDate, ...rest } = input;
  return {
    ...rest,
    dueAt: dueDate ? dueDate.toISOString() : input.dueAt,
    isOverdue: overdue > 0,
    overdueMinutes: overdue,
    isToday: Boolean(dueDate && sameKyivDay(dueDate, now)),
  };
}

function levelRank(level: AttentionLevel) {
  return level === "CRITICAL" ? 0 : level === "HIGH" ? 1 : level === "MEDIUM" ? 2 : 3;
}

function bucketRank(bucket: AttentionBucket) {
  return bucket === "ACTION" ? 0 : bucket === "WAITING" ? 1 : 2;
}

function sortSignals(items: AttentionSignal[]) {
  return items.sort((a, b) => {
    const level = levelRank(a.level) - levelRank(b.level);
    if (level) return level;
    if (a.isOverdue !== b.isOverdue) return a.isOverdue ? -1 : 1;
    const bucket = bucketRank(a.bucket) - bucketRank(b.bucket);
    if (bucket) return bucket;
    const aDue = a.dueAt ? new Date(a.dueAt).getTime() : Number.MAX_SAFE_INTEGER;
    const bDue = b.dueAt ? new Date(b.dueAt).getTime() : Number.MAX_SAFE_INTEGER;
    if (aDue !== bDue) return aDue - bDue;
    return new Date(a.occurredAt).getTime() - new Date(b.occurredAt).getTime();
  });
}

function postLoadForDay(
  dayStart: Date,
  dayEnd: Date,
  locations: Array<{ id: string; name: string; openMinute: number; closeMinute: number; posts: Array<{ id: string; name: string }> }>,
  appointments: Array<{ postId: string | null; plannedStartAt: Date; plannedEndAt: Date }>,
): PostLoadPeriod {
  const posts: PostLoadPost[] = [];
  let bookedMinutesTotal = 0;
  let capacityMinutesTotal = 0;

  for (const location of locations) {
    const capacityPerPost = Math.max(0, location.closeMinute - location.openMinute);
    for (const post of location.posts) {
      const booked = appointments
        .filter((row) => row.postId === post.id && row.plannedStartAt < dayEnd && row.plannedEndAt > dayStart)
        .reduce((sum, row) => {
          const from = Math.max(dayStart.getTime(), row.plannedStartAt.getTime());
          const to = Math.min(dayEnd.getTime(), row.plannedEndAt.getTime());
          return sum + Math.max(0, to - from) / MINUTE_MS;
        }, 0);
      bookedMinutesTotal += booked;
      capacityMinutesTotal += capacityPerPost;
      posts.push({
        id: post.id,
        name: post.name,
        locationId: location.id,
        locationName: location.name,
        utilizationPct: capacityPerPost > 0 ? round((booked / capacityPerPost) * 100) : 0,
        bookedHours: round(booked / 60),
        capacityHours: round(capacityPerPost / 60),
      });
    }
  }

  posts.sort((a, b) => b.utilizationPct - a.utilizationPct || a.name.localeCompare(b.name, "uk"));
  return {
    date: kyivDayKey(dayStart),
    utilizationPct: capacityMinutesTotal > 0 ? round((bookedMinutesTotal / capacityMinutesTotal) * 100) : 0,
    bookedHours: round(bookedMinutesTotal / 60),
    capacityHours: round(capacityMinutesTotal / 60),
    activePosts: posts.length,
    posts,
  };
}

function emptyCategories(): Record<AttentionCategory, number> {
  return {
    COMMUNICATIONS: 0,
    SERVICE: 0,
    DIAGNOSTICS: 0,
    PARTS: 0,
    SUPPLIERS: 0,
    FINANCE: 0,
    PAYROLL: 0,
    POSTS: 0,
    QUALITY: 0,
    WARRANTY: 0,
    MANUAL: 0,
  };
}

function collapseDuplicateInquirySignals(items: AttentionSignal[]) {
  const result: AttentionSignal[] = [];
  const byInquiry = new Map<string, AttentionSignal>();
  for (const item of items) {
    if (item.sourceType !== "INQUIRY" || !item.sourceId) {
      result.push(item);
      continue;
    }
    const key = item.sourceId;
    const existing = byInquiry.get(key);
    if (!existing) {
      byInquiry.set(key, item);
      result.push(item);
      continue;
    }
    const existingCount = Number(existing.metadata.relatedSignalCount || 1);
    existing.metadata = {
      ...existing.metadata,
      relatedSignalCount: existingCount + 1,
      relatedSignalIds: [
        ...(Array.isArray(existing.metadata.relatedSignalIds) ? existing.metadata.relatedSignalIds : [existing.id]),
        item.id,
      ],
      relatedReasons: [
        ...(Array.isArray(existing.metadata.relatedReasons) ? existing.metadata.relatedReasons : [existing.reason]),
        item.reason,
      ],
    };
    if (item.level === "CRITICAL" || (item.level === "HIGH" && existing.level === "MEDIUM")) {
      existing.level = item.level;
      existing.title = item.title;
    }
  }
  return result;
}

export async function buildAttentionCenter(options: AttentionCenterOptions): Promise<AttentionCenterResult> {
  const prisma = getPrisma();
  const now = new Date();
  const today = kyivDay(0);
  const tomorrow = kyivDay(1);
  const dayAfterTomorrow = kyivDay(2);
  const signals: AttentionSignal[] = options.tasks
    .filter((task) => (task.status === "OPEN" || task.status === "IN_PROGRESS") && !isMissedCallTask(task))
    .map((task) => taskSignal(task, now));

  const taskSourceKeys = new Set(options.tasks
    .filter((task) => (task.status === "OPEN" || task.status === "IN_PROGRESS") && task.sourceId && !isMissedCallTask(task))
    .map((task) => `${task.sourceType}:${task.sourceId}`));

  const plannerWhere = options.plannerLocationIds ? { locationId: { in: options.plannerLocationIds } } : {};
  const financeWhere = options.financeLocationIds ? { locationId: { in: options.financeLocationIds } } : {};

  let procurementWorkOrderIds: string[] | null = null;
  if (options.canProcurement && options.procurementLocationIds) {
    const rows = await prisma.serviceAppointment.findMany({
      where: { locationId: { in: options.procurementLocationIds }, workOrderId: { not: null } },
      select: { workOrderId: true },
      distinct: ["workOrderId"],
    });
    procurementWorkOrderIds = rows.map((row) => row.workOrderId).filter((id): id is string => Boolean(id));
  }

  const [inquiries, appointments, locations, loadAppointments, supplierOrders, supplierCredentials, payables, payrollPeriods] = await Promise.all([
    options.canCommunications
      ? prisma.communicationInquiry.findMany({
          where: { state: InquiryState.NEW },
          select: { id: true, channel: true, subject: true, preview: true, receivedAt: true, phone: true, vehicle: true, plate: true, answered: true, metadata: true },
          orderBy: { receivedAt: "asc" },
          take: 250,
        })
      : Promise.resolve([]),
    options.canPlanner
      ? prisma.serviceAppointment.findMany({
          where: { ...plannerWhere, status: { in: activeAppointmentStatuses }, NOT: { id: { startsWith: "demo_" } } },
          select: {
            id: true,
            status: true,
            customerName: true,
            phone: true,
            vehicleId: true,
            vehicleLabel: true,
            plateNumber: true,
            problem: true,
            postId: true,
            mechanicId: true,
            workOrderId: true,
            plannedStartAt: true,
            plannedEndAt: true,
            actualArrivalAt: true,
            actualStartAt: true,
            partsEtaAt: true,
            updatedAt: true,
          },
          orderBy: { plannedEndAt: "asc" },
          take: 400,
        })
      : Promise.resolve([]),
    options.canPlanner
      ? prisma.serviceLocation.findMany({
          where: { isActive: true, ...(options.plannerLocationIds ? { id: { in: options.plannerLocationIds } } : {}) },
          select: {
            id: true,
            name: true,
            openMinute: true,
            closeMinute: true,
            posts: { where: { isActive: true }, select: { id: true, name: true }, orderBy: { sortOrder: "asc" } },
          },
          orderBy: { sortOrder: "asc" },
        })
      : Promise.resolve([]),
    options.canPlanner
      ? prisma.serviceAppointment.findMany({
          where: {
            ...plannerWhere,
            postId: { not: null },
            status: { notIn: [PlannerAppointmentStatus.CANCELLED, PlannerAppointmentStatus.NO_SHOW, PlannerAppointmentStatus.RESERVE] },
            plannedStartAt: { lt: dayAfterTomorrow.end },
            plannedEndAt: { gt: today.start },
            NOT: { id: { startsWith: "demo_" } },
          },
          select: { postId: true, plannedStartAt: true, plannedEndAt: true },
          take: 1000,
        })
      : Promise.resolve([]),
    options.canProcurement
      ? prisma.supplierOrder.findMany({
          where: {
            status: { in: [SupplierOrderStatus.DRAFT, SupplierOrderStatus.SUBMITTED, SupplierOrderStatus.CONFIRMED, SupplierOrderStatus.PARTIAL, SupplierOrderStatus.ERROR] },
            ...(procurementWorkOrderIds ? { workOrderId: { in: procurementWorkOrderIds } } : {}),
          },
          select: {
            id: true,
            status: true,
            workOrderId: true,
            totalPurchase: true,
            currency: true,
            submittedAt: true,
            confirmedAt: true,
            createdAt: true,
            updatedAt: true,
            supplier: { select: { id: true, name: true } },
          },
          orderBy: { updatedAt: "asc" },
          take: 250,
        })
      : Promise.resolve([]),
    options.canProcurement && options.procurementLocationIds === null
      ? prisma.supplierCredential.findMany({
          where: { status: SupplierConnectionStatus.ERROR, supplier: { isActive: true } },
          select: { id: true, status: true, lastCheckedAt: true, lastError: true, supplier: { select: { id: true, name: true } } },
          take: 50,
        })
      : Promise.resolve([]),
    options.canFinance
      ? prisma.financialObligation.findMany({
          where: {
            ...financeWhere,
            direction: FinancialObligationDirection.PAYABLE,
            status: { in: [FinancialObligationStatus.OPEN, FinancialObligationStatus.PARTIALLY_PAID, FinancialObligationStatus.OVERDUE] },
            OR: [
              { status: FinancialObligationStatus.OVERDUE },
              { dueAt: { lte: new Date(now.getTime() + 3 * DAY_MS) } },
              { dueAt: null, issuedAt: { lte: new Date(now.getTime() - 7 * DAY_MS) } },
            ],
          },
          select: {
            id: true,
            status: true,
            amount: true,
            settledAmount: true,
            currency: true,
            issuedAt: true,
            dueAt: true,
            supplierId: true,
            counterpartyName: true,
            description: true,
            workOrderId: true,
            locationId: true,
          },
          orderBy: [{ dueAt: { sort: "asc", nulls: "last" } }, { issuedAt: "asc" }],
          take: 250,
        })
      : Promise.resolve([]),
    options.canPayrollNetwork
      ? prisma.payrollPeriod.findMany({
          where: { status: { in: [PayrollPeriodStatus.OPEN, PayrollPeriodStatus.REVIEW] } },
          select: {
            id: true,
            key: true,
            periodStart: true,
            periodEnd: true,
            status: true,
            accruals: { select: { amount: true, status: true } },
            payments: { select: { amount: true } },
          },
          orderBy: { periodEnd: "asc" },
          take: 12,
        })
      : Promise.resolve([]),
  ]);

  for (const item of inquiries) {
    if (taskSourceKeys.has(`INQUIRY:${item.id}`)) continue;
    const age = ageMinutes(item.receivedAt, now);
    const text = `${String(item.subject || "")} ${String(item.preview || "")}`.toLocaleLowerCase("uk-UA");
    if (isMissedCallInquiry(item)) continue;
    const due = new Date(item.receivedAt.getTime() + 15 * MINUTE_MS);
    signals.push(signal({
      id: `inquiry:${item.id}`,
      sourceType: "INQUIRY",
      sourceId: item.id,
      taskId: null,
      title: "Нове звернення без опрацювання",
      description: [item.subject, item.preview].filter(Boolean).join(" · ").slice(0, 360) || null,
      reason: `Звернення залишається новим уже ${age} хв. Норматив першої реакції — до 15 хв.`,
      category: "COMMUNICATIONS",
      level: age >= 60 ? "CRITICAL" : age >= 15 ? "HIGH" : "MEDIUM",
      bucket: "ACTION",
      dueAt: due.toISOString(),
      dueDate: due,
      occurredAt: item.receivedAt.toISOString(),
      autoGenerated: true,
      amount: null,
      currency: null,
      counterparty: item.phone || null,
      action: { label: "Відкрити звернення", section: "Нові звернення" },
      metadata: { channel: item.channel, phone: item.phone, vehicle: item.vehicle, plate: item.plate },
    }, now));
  }

  for (const row of appointments) {
    const label = row.plateNumber || row.vehicleLabel || row.customerName || "Авто";
    const appointmentAction: AttentionAction = { label: "Відкрити запис", section: "Планувальник", params: { appointmentId: row.id } };
    const activeAfterArrival = row.status !== PlannerAppointmentStatus.BOOKED && row.status !== PlannerAppointmentStatus.READY_FOR_PICKUP && row.status !== PlannerAppointmentStatus.WAITING_PAYMENT;

    if (row.plannedEndAt < now && row.status !== PlannerAppointmentStatus.BOOKED) {
      const late = minutesLate(row.plannedEndAt, now);
      signals.push(signal({
        id: `appointment:${row.id}:overdue`,
        sourceType: "APPOINTMENT",
        sourceId: row.id,
        taskId: null,
        title: `${label}: авто вийшло за плановий час`,
        description: row.problem || null,
        reason: `Плановий час завершення минув. Прострочення — ${late} хв.`,
        category: "SERVICE",
        level: late >= 4 * 60 ? "CRITICAL" : "HIGH",
        bucket: "ACTION",
        dueAt: row.plannedEndAt.toISOString(),
        dueDate: row.plannedEndAt,
        occurredAt: (row.actualArrivalAt || row.plannedStartAt).toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || null,
        action: appointmentAction,
        metadata: { status: row.status, workOrderId: row.workOrderId, vehicleId: row.vehicleId, plateNumber: row.plateNumber },
      }, now));
    }

    if (row.status === PlannerAppointmentStatus.BOOKED && !row.actualArrivalAt && row.plannedStartAt.getTime() + 15 * MINUTE_MS < now.getTime()) {
      const due = new Date(row.plannedStartAt.getTime() + 15 * MINUTE_MS);
      signals.push(signal({
        id: `appointment:${row.id}:arrival`,
        sourceType: "APPOINTMENT",
        sourceId: row.id,
        taskId: null,
        title: `${label}: не підтверджено приїзд`,
        description: row.problem || null,
        reason: "Запланований час приїзду минув більше ніж 15 хв тому, але прибуття авто не зафіксовано.",
        category: "SERVICE",
        level: ageMinutes(row.plannedStartAt, now) >= 60 ? "CRITICAL" : "HIGH",
        bucket: "ACTION",
        dueAt: due.toISOString(),
        dueDate: due,
        occurredAt: row.plannedStartAt.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || row.phone || null,
        action: appointmentAction,
        metadata: { status: row.status, plateNumber: row.plateNumber },
      }, now));
    }

    if (activeAfterArrival && !row.mechanicId) {
      const anchor = row.actualArrivalAt || row.actualStartAt || row.updatedAt;
      const due = new Date(anchor.getTime() + 15 * MINUTE_MS);
      signals.push(signal({
        id: `appointment:${row.id}:mechanic`,
        sourceType: "APPOINTMENT",
        sourceId: row.id,
        taskId: null,
        title: `${label}: немає відповідального механіка`,
        description: row.problem || null,
        reason: "Авто вже в операційному процесі, але механік не призначений.",
        category: "SERVICE",
        level: ageMinutes(anchor, now) >= 60 ? "CRITICAL" : "HIGH",
        bucket: "ACTION",
        dueAt: due.toISOString(),
        dueDate: due,
        occurredAt: anchor.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || null,
        action: appointmentAction,
        metadata: { status: row.status, workOrderId: row.workOrderId, plateNumber: row.plateNumber },
      }, now));
    }

    if (activeAfterArrival && !row.postId) {
      const anchor = row.actualArrivalAt || row.actualStartAt || row.updatedAt;
      const due = new Date(anchor.getTime() + 15 * MINUTE_MS);
      signals.push(signal({
        id: `appointment:${row.id}:post`,
        sourceType: "APPOINTMENT",
        sourceId: row.id,
        taskId: null,
        title: `${label}: авто не закріплене за постом`,
        description: row.problem || null,
        reason: "Авто перебуває в роботі, але сервісний пост не визначений.",
        category: "POSTS",
        level: ageMinutes(anchor, now) >= 60 ? "CRITICAL" : "HIGH",
        bucket: "ACTION",
        dueAt: due.toISOString(),
        dueDate: due,
        occurredAt: anchor.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || null,
        action: appointmentAction,
        metadata: { status: row.status, workOrderId: row.workOrderId, plateNumber: row.plateNumber },
      }, now));
    }

    if (row.status === PlannerAppointmentStatus.WAITING_PARTS && row.partsEtaAt && row.partsEtaAt < now) {
      signals.push(signal({
        id: `appointment:${row.id}:parts-eta`,
        sourceType: "PARTS_ETA",
        sourceId: row.id,
        taskId: null,
        title: `${label}: прострочена поставка запчастин`,
        description: row.problem || null,
        reason: "ETA запчастин минув, але авто все ще має статус очікування запчастин.",
        category: "PARTS",
        level: minutesLate(row.partsEtaAt, now) >= 4 * 60 ? "CRITICAL" : "HIGH",
        bucket: "ACTION",
        dueAt: row.partsEtaAt.toISOString(),
        dueDate: row.partsEtaAt,
        occurredAt: row.updatedAt.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || null,
        action: row.workOrderId
          ? { label: "Відкрити запчастини", section: "Комерційна пропозиція", params: { workOrderId: row.workOrderId, workOrderTab: "parts" } }
          : appointmentAction,
        metadata: { status: row.status, workOrderId: row.workOrderId, plateNumber: row.plateNumber },
      }, now));
    }

    if (row.status === PlannerAppointmentStatus.READY_FOR_PICKUP && row.updatedAt.getTime() + 60 * MINUTE_MS < now.getTime()) {
      const due = new Date(row.updatedAt.getTime() + 60 * MINUTE_MS);
      signals.push(signal({
        id: `appointment:${row.id}:pickup`,
        sourceType: "APPOINTMENT",
        sourceId: row.id,
        taskId: null,
        title: `${label}: готове авто очікує видачі`,
        description: null,
        reason: "Авто перебуває у статусі «Готово до видачі» більше години.",
        category: "SERVICE",
        level: ageMinutes(row.updatedAt, now) >= 4 * 60 ? "HIGH" : "MEDIUM",
        bucket: "WAITING",
        dueAt: due.toISOString(),
        dueDate: due,
        occurredAt: row.updatedAt.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || row.phone || null,
        action: appointmentAction,
        metadata: { status: row.status, workOrderId: row.workOrderId, plateNumber: row.plateNumber },
      }, now));
    }

    if (row.status === PlannerAppointmentStatus.PAUSED && row.updatedAt.getTime() + 2 * 60 * MINUTE_MS < now.getTime()) {
      const due = new Date(row.updatedAt.getTime() + 2 * 60 * MINUTE_MS);
      signals.push(signal({
        id: `appointment:${row.id}:paused`,
        sourceType: "APPOINTMENT",
        sourceId: row.id,
        taskId: null,
        title: `${label}: робота стоїть на паузі`,
        description: row.problem || null,
        reason: "Статус PAUSED не змінювався більше 2 годин. Потрібне рішення або новий план.",
        category: "SERVICE",
        level: ageMinutes(row.updatedAt, now) >= 6 * 60 ? "CRITICAL" : "HIGH",
        bucket: "ACTION",
        dueAt: due.toISOString(),
        dueDate: due,
        occurredAt: row.updatedAt.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || null,
        action: appointmentAction,
        metadata: { status: row.status, workOrderId: row.workOrderId, plateNumber: row.plateNumber },
      }, now));
    }
  }

  for (const order of supplierOrders) {
    const anchor = order.status === SupplierOrderStatus.SUBMITTED
      ? order.submittedAt || order.updatedAt
      : order.status === SupplierOrderStatus.CONFIRMED
        ? order.confirmedAt || order.updatedAt
        : order.updatedAt;
    let due = new Date(anchor.getTime() + 4 * 60 * MINUTE_MS);
    let title = `Постачальник ${order.supplier.name}: замовлення потребує контролю`;
    let reason = "Замовлення постачальнику залишається на активному етапі довше очікуваного.";
    let level: AttentionLevel = "MEDIUM";
    let bucket: AttentionBucket = "ACTION";

    if (order.status === SupplierOrderStatus.ERROR) {
      due = order.updatedAt;
      title = `Помилка замовлення у ${order.supplier.name}`;
      reason = "Постачальник або інтеграція повернули помилку. Потрібне ручне втручання.";
      level = "CRITICAL";
    } else if (order.status === SupplierOrderStatus.DRAFT) {
      due = new Date(order.createdAt.getTime() + 2 * 60 * MINUTE_MS);
      title = `Замовлення ${order.supplier.name} залишилось чернеткою`;
      reason = "Чернетка замовлення не відправлена постачальнику більше 2 годин.";
      level = ageMinutes(order.createdAt, now) >= 8 * 60 ? "CRITICAL" : "HIGH";
    } else if (order.status === SupplierOrderStatus.SUBMITTED) {
      due = new Date(anchor.getTime() + 2 * 60 * MINUTE_MS);
      title = `${order.supplier.name} не підтвердив замовлення`;
      reason = "Замовлення відправлено, але підтвердження постачальника ще немає.";
      level = ageMinutes(anchor, now) >= 8 * 60 ? "CRITICAL" : "HIGH";
      bucket = "WAITING";
    } else if (order.status === SupplierOrderStatus.CONFIRMED) {
      due = new Date(anchor.getTime() + 24 * 60 * MINUTE_MS);
      title = `Контроль поставки від ${order.supplier.name}`;
      reason = "Підтверджене замовлення не завершене протягом 24 годин.";
      level = ageMinutes(anchor, now) >= 48 * 60 ? "CRITICAL" : "HIGH";
      bucket = "WAITING";
    } else if (order.status === SupplierOrderStatus.PARTIAL) {
      due = new Date(anchor.getTime() + 8 * 60 * MINUTE_MS);
      title = `${order.supplier.name}: поставка неповна`;
      reason = "Замовлення отримано частково; решта позицій не закрита більше 8 годин.";
      level = ageMinutes(anchor, now) >= 24 * 60 ? "CRITICAL" : "HIGH";
      bucket = "WAITING";
    }

    if (due > now && order.status !== SupplierOrderStatus.ERROR) continue;
    signals.push(signal({
      id: `supplier-order:${order.id}`,
      sourceType: "SUPPLIER_ORDER",
      sourceId: order.id,
      taskId: null,
      title,
      description: order.workOrderId ? `Пов’язано із КП ${order.workOrderId}` : null,
      reason,
      category: "SUPPLIERS",
      level,
      bucket,
      dueAt: due.toISOString(),
      dueDate: due,
      occurredAt: anchor.toISOString(),
      autoGenerated: true,
      amount: order.totalPurchase ? numberOf(order.totalPurchase) : null,
      currency: order.totalPurchase ? order.currency : null,
      counterparty: order.supplier.name,
      action: { label: "Відкрити закупівлі", section: "Закупівлі та склад", params: { scope: "ordered" } },
      metadata: { status: order.status, workOrderId: order.workOrderId, supplierId: order.supplier.id },
    }, now));
  }

  for (const credential of supplierCredentials) {
    signals.push(signal({
      id: `supplier-connection:${credential.id}`,
      sourceType: "SUPPLIER_CONNECTION",
      sourceId: credential.supplier.id,
      taskId: null,
      title: `Помилка інтеграції з ${credential.supplier.name}`,
      description: credential.lastError || null,
      reason: "Підключення активного постачальника має статус ERROR. Автоматичний пошук цін або замовлення можуть не працювати.",
      category: "SUPPLIERS",
      level: "CRITICAL",
      bucket: "ACTION",
      dueAt: dateIso(credential.lastCheckedAt) || now.toISOString(),
      dueDate: credential.lastCheckedAt || now,
      occurredAt: (credential.lastCheckedAt || now).toISOString(),
      autoGenerated: true,
      amount: null,
      currency: null,
      counterparty: credential.supplier.name,
      action: { label: "Перевірити постачальника", section: "Налаштування" },
      metadata: { status: credential.status, supplierId: credential.supplier.id },
    }, now));
  }

  for (const obligation of payables) {
    const outstanding = Math.max(0, numberOf(obligation.amount) - numberOf(obligation.settledAmount));
    if (outstanding <= 0) continue;
    const overdue = obligation.status === FinancialObligationStatus.OVERDUE || Boolean(obligation.dueAt && obligation.dueAt < now);
    const dueSoon = Boolean(obligation.dueAt && obligation.dueAt <= new Date(now.getTime() + DAY_MS));
    const noDueDateOld = !obligation.dueAt && obligation.issuedAt <= new Date(now.getTime() - 7 * DAY_MS);
    const level: AttentionLevel = overdue
      ? minutesLate(obligation.dueAt || obligation.issuedAt, now) >= DAY_MS / MINUTE_MS ? "CRITICAL" : "HIGH"
      : dueSoon ? "HIGH" : noDueDateOld ? "HIGH" : "MEDIUM";
    const title = overdue
      ? `Прострочений наш платіж: ${obligation.counterpartyName || "контрагент"}`
      : noDueDateOld
        ? `Платіж без визначеного строку: ${obligation.counterpartyName || "контрагент"}`
        : `Наближається наш платіж: ${obligation.counterpartyName || "контрагент"}`;
    signals.push(signal({
      id: `payable:${obligation.id}`,
      sourceType: "PAYABLE",
      sourceId: obligation.id,
      taskId: null,
      title,
      description: obligation.description || null,
      reason: overdue
        ? "Строк нашого платежу минув, але зобов’язання не закрито."
        : noDueDateOld
          ? "Зобов’язання відкрите понад 7 днів і не має встановленого строку оплати."
          : "Платіж має бути виконаний протягом найближчих 3 днів.",
      category: "FINANCE",
      level,
      bucket: "ACTION",
      dueAt: dateIso(obligation.dueAt),
      dueDate: obligation.dueAt,
      occurredAt: obligation.issuedAt.toISOString(),
      autoGenerated: true,
      amount: outstanding,
      currency: obligation.currency,
      counterparty: obligation.counterpartyName || null,
      action: { label: "Відкрити фінанси", section: "Фінансовий центр", params: { scope: "payables" } },
      metadata: { status: obligation.status, workOrderId: obligation.workOrderId, supplierId: obligation.supplierId, locationId: obligation.locationId },
    }, now));
  }

  for (const period of payrollPeriods) {
    const posted = period.accruals
      .filter((row) => row.status === SalaryAccrualStatus.POSTED)
      .reduce((sum, row) => sum + numberOf(row.amount), 0);
    const draftCount = period.accruals.filter((row) => row.status === SalaryAccrualStatus.DRAFT).length;
    const paid = period.payments.reduce((sum, row) => sum + numberOf(row.amount), 0);
    const outstanding = Math.max(0, posted - paid);
    const periodEnded = period.periodEnd < today.start;

    if (periodEnded && outstanding > 0) {
      const lateDays = Math.max(0, Math.floor((today.start.getTime() - period.periodEnd.getTime()) / DAY_MS));
      signals.push(signal({
        id: `payroll:${period.id}:outstanding`,
        sourceType: "PAYROLL",
        sourceId: period.id,
        taskId: null,
        title: `Не закриті виплати зарплати за ${period.key}`,
        description: `Нараховано: ${round(posted, 2)} грн · виплачено: ${round(paid, 2)} грн`,
        reason: `Розрахунковий період завершено, але зафіксовані виплати менші за проведені нарахування.${lateDays ? ` Минуло ${lateDays} дн.` : ""}`,
        category: "PAYROLL",
        level: lateDays >= 5 ? "CRITICAL" : "HIGH",
        bucket: "ACTION",
        dueAt: period.periodEnd.toISOString(),
        dueDate: period.periodEnd,
        occurredAt: period.periodStart.toISOString(),
        autoGenerated: true,
        amount: outstanding,
        currency: "UAH",
        counterparty: "Персонал",
        action: { label: "Відкрити фінанси", section: "Фінансовий центр", params: { scope: "payroll" } },
        metadata: { payrollPeriodId: period.id, status: period.status, posted, paid },
      }, now));
    }

    if (periodEnded && draftCount > 0) {
      signals.push(signal({
        id: `payroll:${period.id}:drafts`,
        sourceType: "PAYROLL",
        sourceId: period.id,
        taskId: null,
        title: `Непроведені нарахування зарплати за ${period.key}`,
        description: `${draftCount} нарахувань залишаються у статусі DRAFT.`,
        reason: "Розрахунковий період уже завершився, а частина нарахувань ще не проведена.",
        category: "PAYROLL",
        level: "HIGH",
        bucket: "ACTION",
        dueAt: period.periodEnd.toISOString(),
        dueDate: period.periodEnd,
        occurredAt: period.periodStart.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: "Персонал",
        action: { label: "Відкрити фінанси", section: "Фінансовий центр", params: { scope: "payroll" } },
        metadata: { payrollPeriodId: period.id, status: period.status, draftCount },
      }, now));
    }

    if (period.status === PayrollPeriodStatus.REVIEW && !periodEnded) {
      signals.push(signal({
        id: `payroll:${period.id}:review`,
        sourceType: "PAYROLL",
        sourceId: period.id,
        taskId: null,
        title: `Зарплатний період ${period.key} очікує перевірки`,
        description: null,
        reason: "Період переведений у REVIEW і потребує фінального контролю перед закриттям.",
        category: "PAYROLL",
        level: "MEDIUM",
        bucket: "ACTION",
        dueAt: period.periodEnd.toISOString(),
        dueDate: period.periodEnd,
        occurredAt: period.periodStart.toISOString(),
        autoGenerated: true,
        amount: outstanding || null,
        currency: outstanding ? "UAH" : null,
        counterparty: "Персонал",
        action: { label: "Відкрити фінанси", section: "Фінансовий центр", params: { scope: "payroll" } },
        metadata: { payrollPeriodId: period.id, status: period.status },
      }, now));
    }
  }

  let todayLoad: PostLoadPeriod | null = null;
  let tomorrowLoad: PostLoadPeriod | null = null;
  if (options.canPlanner && locations.length) {
    todayLoad = postLoadForDay(today.start, today.end, locations, loadAppointments);
    tomorrowLoad = postLoadForDay(tomorrow.start, tomorrow.end, locations, loadAppointments);

    if (todayLoad.activePosts > 0 && (todayLoad.utilizationPct < 35 || todayLoad.utilizationPct > 100)) {
      const low = todayLoad.utilizationPct < 35;
      signals.push(signal({
        id: `post-load:${todayLoad.date}:today`,
        sourceType: "POST_LOAD",
        sourceId: todayLoad.date,
        taskId: null,
        title: low ? "Низьке завантаження постів сьогодні" : "Пости перевантажені сьогодні",
        description: `${todayLoad.bookedHours} із ${todayLoad.capacityHours} пост-годин заплановано.`,
        reason: low
          ? `Завантаження становить лише ${todayLoad.utilizationPct}%. Є невикористана виробнича потужність.`
          : `Завантаження становить ${todayLoad.utilizationPct}%. План перевищує доступну потужність постів.`,
        category: "POSTS",
        level: low ? "HIGH" : "CRITICAL",
        bucket: "ACTION",
        dueAt: today.end.toISOString(),
        dueDate: today.end,
        occurredAt: now.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: null,
        action: { label: "Відкрити планувальник", section: "Планувальник", params: { date: todayLoad.date } },
        metadata: { utilizationPct: todayLoad.utilizationPct, activePosts: todayLoad.activePosts },
      }, now));
    }

    if (tomorrowLoad.activePosts > 0 && (tomorrowLoad.utilizationPct < 50 || tomorrowLoad.utilizationPct >= 95)) {
      const low = tomorrowLoad.utilizationPct < 50;
      signals.push(signal({
        id: `post-load:${tomorrowLoad.date}:tomorrow`,
        sourceType: "POST_LOAD",
        sourceId: tomorrowLoad.date,
        taskId: null,
        title: low ? "Низьке завантаження постів на завтра" : "На завтра майже немає вільних постів",
        description: `${tomorrowLoad.bookedHours} із ${tomorrowLoad.capacityHours} пост-годин заплановано.`,
        reason: low
          ? `Завантаження на завтра — ${tomorrowLoad.utilizationPct}%. Варто дозаповнити план.`
          : `Завантаження на завтра — ${tomorrowLoad.utilizationPct}%. Потрібно контролювати нові записи та строки ремонту.`,
        category: "POSTS",
        level: tomorrowLoad.utilizationPct >= 100 ? "CRITICAL" : "HIGH",
        bucket: "MONITORING",
        dueAt: tomorrow.end.toISOString(),
        dueDate: tomorrow.end,
        occurredAt: now.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: null,
        action: { label: "Відкрити завтра", section: "Планувальник", params: { date: tomorrowLoad.date } },
        metadata: { utilizationPct: tomorrowLoad.utilizationPct, activePosts: tomorrowLoad.activePosts },
      }, now));
    }

    for (const post of todayLoad.posts.filter((item) => item.utilizationPct > 110)) {
      signals.push(signal({
        id: `post-overload:${post.id}:${todayLoad.date}`,
        sourceType: "POST_LOAD",
        sourceId: post.id,
        taskId: null,
        title: `${post.name}: перевантаження ${post.utilizationPct}%`,
        description: `${post.locationName} · ${post.bookedHours} із ${post.capacityHours} год`,
        reason: "На один пост заплановано більше часу, ніж доступно за графіком станції.",
        category: "POSTS",
        level: "CRITICAL",
        bucket: "ACTION",
        dueAt: today.end.toISOString(),
        dueDate: today.end,
        occurredAt: now.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: post.locationName,
        action: { label: "Перебудувати графік", section: "Планувальник", params: { date: todayLoad.date } },
        metadata: { postId: post.id, utilizationPct: post.utilizationPct, locationId: post.locationId },
      }, now));
    }
  }

  const sorted = collapseDuplicateInquirySignals(sortSignals(signals));
  const categories = emptyCategories();
  for (const item of sorted) categories[item.category] += 1;

  return {
    signals: sorted,
    summary: {
      total: sorted.length,
      critical: sorted.filter((item) => item.level === "CRITICAL").length,
      overdue: sorted.filter((item) => item.isOverdue).length,
      action: sorted.filter((item) => item.bucket === "ACTION").length,
      waiting: sorted.filter((item) => item.bucket === "WAITING").length,
      today: sorted.filter((item) => item.isToday).length,
    },
    categories,
    postLoad: { today: todayLoad, tomorrow: tomorrowLoad },
    generatedAt: now.toISOString(),
  };
}
