import "server-only";

import { PayrollPeriodStatus, PlannerAppointmentStatus, SalaryAccrualStatus } from "@/src/generated/prisma/client";
import { getPrisma } from "@/src/lib/prisma";
import type { AttentionCenterResult, AttentionSignal } from "@/src/services/attention-center.service";

const MINUTE_MS = 60_000;
const DAY_MS = 86_400_000;
const KYIV_TZ = "Europe/Kyiv";

type SupplementOptions = {
  canPlanner: boolean;
  plannerLocationIds: string[] | null;
  canPayrollNetwork: boolean;
};

function dayKey(date: Date) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: KYIV_TZ,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

function overdueMinutes(dueAt: Date, now: Date) {
  return dueAt < now ? Math.max(1, Math.floor((now.getTime() - dueAt.getTime()) / MINUTE_MS)) : 0;
}

function numberOf(value: unknown) {
  const number = Number(value ?? 0);
  return Number.isFinite(number) ? number : 0;
}

function rank(signal: AttentionSignal) {
  const level = signal.level === "CRITICAL" ? 0 : signal.level === "HIGH" ? 1 : signal.level === "MEDIUM" ? 2 : 3;
  const overdue = signal.isOverdue ? 0 : 1;
  const bucket = signal.bucket === "ACTION" ? 0 : signal.bucket === "WAITING" ? 1 : 2;
  const due = signal.dueAt ? new Date(signal.dueAt).getTime() : Number.MAX_SAFE_INTEGER;
  return [level, overdue, bucket, due, new Date(signal.occurredAt).getTime()] as const;
}

function sortSignals(items: AttentionSignal[]) {
  return items.sort((a, b) => {
    const ar = rank(a);
    const br = rank(b);
    for (let i = 0; i < ar.length; i += 1) {
      if (ar[i] !== br[i]) return ar[i] - br[i];
    }
    return a.id.localeCompare(b.id);
  });
}

function withDerived(signal: Omit<AttentionSignal, "isOverdue" | "overdueMinutes" | "isToday">, dueAt: Date, now: Date): AttentionSignal {
  const late = overdueMinutes(dueAt, now);
  return {
    ...signal,
    dueAt: dueAt.toISOString(),
    isOverdue: late > 0,
    overdueMinutes: late,
    isToday: dayKey(dueAt) === dayKey(now),
  };
}

export async function supplementAttentionCenter(center: AttentionCenterResult, options: SupplementOptions): Promise<AttentionCenterResult> {
  const prisma = getPrisma();
  const now = new Date();
  const extras: AttentionSignal[] = [];
  const existingKeys = new Set(center.signals.map((signal) => `${signal.sourceType}:${signal.sourceId ?? ""}:${String(signal.metadata.status ?? "")}`));

  if (options.canPlanner) {
    const noShows = await prisma.serviceAppointment.findMany({
      where: {
        status: PlannerAppointmentStatus.NO_SHOW,
        ...(options.plannerLocationIds ? { locationId: { in: options.plannerLocationIds } } : {}),
        NOT: { id: { startsWith: "demo_" } },
      },
      select: {
        id: true,
        customerName: true,
        phone: true,
        vehicleLabel: true,
        plateNumber: true,
        problem: true,
        plannedStartAt: true,
        noShowAt: true,
      },
      orderBy: { plannedStartAt: "asc" },
      take: 250,
    });

    for (const row of noShows) {
      if (existingKeys.has(`APPOINTMENT:${row.id}:NO_SHOW`)) continue;
      const due = row.noShowAt || row.plannedStartAt;
      const label = row.plateNumber || row.vehicleLabel || row.customerName || "Авто";
      extras.push(withDerived({
        id: `appointment:${row.id}:no-show`,
        sourceType: "APPOINTMENT",
        sourceId: row.id,
        taskId: null,
        title: `${label}: клієнт не приїхав`,
        description: row.problem || null,
        reason: "Запис має статус no-show. Потрібно зв’язатися з клієнтом і зафіксувати наступну дію.",
        category: "SERVICE",
        level: "CRITICAL",
        bucket: "ACTION",
        dueAt: due.toISOString(),
        occurredAt: due.toISOString(),
        autoGenerated: true,
        amount: null,
        currency: null,
        counterparty: row.customerName || row.phone || null,
        action: { label: "Відкрити запис", section: "Планувальник", params: { appointmentId: row.id, status: "NO_SHOW" } },
        metadata: { status: "NO_SHOW", plateNumber: row.plateNumber },
      }, due, now));
    }
  }

  if (options.canPayrollNetwork) {
    const closedPeriods = await prisma.payrollPeriod.findMany({
      where: { status: PayrollPeriodStatus.CLOSED },
      select: {
        id: true,
        key: true,
        periodStart: true,
        periodEnd: true,
        status: true,
        accruals: { select: { amount: true, status: true } },
        payments: { select: { amount: true } },
      },
      orderBy: { periodEnd: "desc" },
      take: 12,
    });

    for (const period of closedPeriods) {
      const posted = period.accruals
        .filter((row) => row.status === SalaryAccrualStatus.POSTED)
        .reduce((sum, row) => sum + numberOf(row.amount), 0);
      const draftCount = period.accruals.filter((row) => row.status === SalaryAccrualStatus.DRAFT).length;
      const paid = period.payments.reduce((sum, row) => sum + numberOf(row.amount), 0);
      const outstanding = Math.max(0, posted - paid);
      const lateDays = Math.max(0, Math.floor((now.getTime() - period.periodEnd.getTime()) / DAY_MS));

      if (outstanding > 0) {
        extras.push(withDerived({
          id: `payroll:${period.id}:closed-outstanding`,
          sourceType: "PAYROLL",
          sourceId: period.id,
          taskId: null,
          title: `Закритий зарплатний період ${period.key} має невиплачений залишок`,
          description: `Нараховано: ${Math.round(posted)} грн · виплачено: ${Math.round(paid)} грн`,
          reason: "Період уже закритий, але проведені нарахування перевищують зафіксовані виплати.",
          category: "PAYROLL",
          level: lateDays >= 5 ? "CRITICAL" : "HIGH",
          bucket: "ACTION",
          dueAt: period.periodEnd.toISOString(),
          occurredAt: period.periodStart.toISOString(),
          autoGenerated: true,
          amount: outstanding,
          currency: "UAH",
          counterparty: "Персонал",
          action: { label: "Відкрити фінанси", section: "Фінансовий центр", params: { scope: "payroll" } },
          metadata: { payrollPeriodId: period.id, status: period.status, posted, paid },
        }, period.periodEnd, now));
      }

      if (draftCount > 0) {
        extras.push(withDerived({
          id: `payroll:${period.id}:closed-drafts`,
          sourceType: "PAYROLL",
          sourceId: period.id,
          taskId: null,
          title: `Закритий зарплатний період ${period.key} має чернеткові нарахування`,
          description: `${draftCount} нарахувань залишаються у статусі DRAFT.`,
          reason: "Закритий період не повинен містити непроведені нарахування.",
          category: "PAYROLL",
          level: "HIGH",
          bucket: "ACTION",
          dueAt: period.periodEnd.toISOString(),
          occurredAt: period.periodStart.toISOString(),
          autoGenerated: true,
          amount: null,
          currency: null,
          counterparty: "Персонал",
          action: { label: "Відкрити фінанси", section: "Фінансовий центр", params: { scope: "payroll" } },
          metadata: { payrollPeriodId: period.id, status: period.status, draftCount },
        }, period.periodEnd, now));
      }
    }
  }

  if (!extras.length) return center;
  const signals = sortSignals([...center.signals, ...extras]);
  const categories = { ...center.categories };
  for (const item of extras) categories[item.category] += 1;

  return {
    ...center,
    signals,
    categories,
    summary: {
      total: signals.length,
      critical: signals.filter((item) => item.level === "CRITICAL").length,
      overdue: signals.filter((item) => item.isOverdue).length,
      action: signals.filter((item) => item.bucket === "ACTION").length,
      waiting: signals.filter((item) => item.bucket === "WAITING").length,
      today: signals.filter((item) => item.isToday).length,
    },
    generatedAt: now.toISOString(),
  };
}
