import "server-only";

import { getPrisma } from "@/src/lib/prisma";

export type TaskStatus = "OPEN" | "IN_PROGRESS" | "DONE" | "CANCELLED";
export type TaskPriority = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type TaskSourceType = "MANUAL" | "INQUIRY" | "LEAD" | "APPOINTMENT" | "DIAGNOSTIC" | "ESTIMATE" | "WORK_ORDER" | "PARTS_REQUEST" | "PAYMENT" | "QC" | "WARRANTY";

const statuses = new Set<TaskStatus>(["OPEN", "IN_PROGRESS", "DONE", "CANCELLED"]);
const priorities = new Set<TaskPriority>(["LOW", "MEDIUM", "HIGH", "CRITICAL"]);

function cleanTitle(value: unknown) {
  const title = String(value || "").trim();
  if (!title) throw new Error("TITLE_REQUIRED");
  return title.slice(0, 240);
}

function dateOrNull(value: unknown) {
  if (value === null || value === undefined || value === "") return null;
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) throw new Error("INVALID_DATE");
  return date;
}

export async function listTasksForUser(userId: string) {
  const prisma = getPrisma();
  const tasks = await prisma.crmTask.findMany({
    where: { assignedUserId: userId },
    orderBy: [
      { status: "asc" },
      { dueAt: { sort: "asc", nulls: "last" } },
      { createdAt: "desc" },
    ],
    take: 500,
  });
  return tasks;
}

export async function createManualTask(userId: string, input: Record<string, unknown>) {
  const prisma = getPrisma();
  const priority = priorities.has(input.priority as TaskPriority) ? input.priority as TaskPriority : "MEDIUM";
  return prisma.crmTask.create({
    data: {
      title: cleanTitle(input.title),
      description: typeof input.description === "string" && input.description.trim() ? input.description.trim().slice(0, 4000) : null,
      status: "OPEN",
      priority,
      assignedUserId: userId,
      createdByUserId: userId,
      dueAt: dateOrNull(input.dueAt),
      remindAt: dateOrNull(input.remindAt),
      sourceType: "MANUAL",
      autoGenerated: false,
    },
  });
}

export async function patchTaskForUser(userId: string, taskId: string, input: Record<string, unknown>) {
  const prisma = getPrisma();
  const current = await prisma.crmTask.findFirst({ where: { id: taskId, assignedUserId: userId } });
  if (!current) throw new Error("TASK_NOT_FOUND");
  if (current.autoGenerated) throw new Error("AUTO_TASK_READ_ONLY");

  const data: {
    title?: string;
    description?: string | null;
    status?: string;
    priority?: string;
    dueAt?: Date | null;
    remindAt?: Date | null;
    completedAt?: Date | null;
  } = {};

  if (input.title !== undefined) data.title = cleanTitle(input.title);
  if (input.description !== undefined) data.description = typeof input.description === "string" && input.description.trim() ? input.description.trim().slice(0, 4000) : null;
  if (input.priority !== undefined) {
    if (!priorities.has(input.priority as TaskPriority)) throw new Error("INVALID_PRIORITY");
    data.priority = input.priority as TaskPriority;
  }
  if (input.dueAt !== undefined) data.dueAt = dateOrNull(input.dueAt);
  if (input.remindAt !== undefined) data.remindAt = dateOrNull(input.remindAt);
  if (input.status !== undefined) {
    if (!statuses.has(input.status as TaskStatus)) throw new Error("INVALID_STATUS");
    data.status = input.status as TaskStatus;
    if (input.status === "DONE") data.completedAt = new Date();
    if (input.status === "OPEN" || input.status === "IN_PROGRESS") data.completedAt = null;
  }

  return prisma.crmTask.update({ where: { id: taskId }, data });
}
