CREATE OR REPLACE FUNCTION turbolev_work_order_location_id(p_work_order_id TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT sa."locationId"
  FROM "ServiceAppointment" sa
  WHERE sa."workOrderId" = p_work_order_id
  ORDER BY sa."updatedAt" DESC, sa."createdAt" DESC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION turbolev_work_order_responsible_user(p_work_order_id TEXT, p_role_codes TEXT[])
RETURNS TEXT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  location_id TEXT;
  target_user_id TEXT;
BEGIN
  location_id := turbolev_work_order_location_id(p_work_order_id);

  SELECT uar."userId"
    INTO target_user_id
  FROM "UserAccessRole" uar
  JOIN "AccessRole" ar ON ar."id" = uar."roleId"
  JOIN "User" u ON u."id" = uar."userId"
  WHERE uar."isActive" = TRUE
    AND ar."isActive" = TRUE
    AND u."isActive" = TRUE
    AND uar."startsAt" <= CURRENT_TIMESTAMP
    AND (uar."endsAt" IS NULL OR uar."endsAt" > CURRENT_TIMESTAMP)
    AND ar."code" = ANY(p_role_codes)
    AND (location_id IS NULL OR uar."locationId" = location_id OR uar."locationId" IS NULL)
  ORDER BY
    CASE WHEN location_id IS NOT NULL AND uar."locationId" = location_id THEN 0 ELSE 1 END,
    array_position(p_role_codes, ar."code"),
    uar."isPrimary" DESC,
    uar."createdAt" ASC
  LIMIT 1;

  IF target_user_id IS NOT NULL THEN
    RETURN target_user_id;
  END IF;

  SELECT sa."createdById"
    INTO target_user_id
  FROM "ServiceAppointment" sa
  JOIN "User" u ON u."id" = sa."createdById" AND u."isActive" = TRUE
  WHERE sa."workOrderId" = p_work_order_id
    AND sa."createdById" IS NOT NULL
  ORDER BY sa."updatedAt" DESC, sa."createdAt" DESC
  LIMIT 1;

  IF target_user_id IS NOT NULL THEN
    RETURN target_user_id;
  END IF;

  SELECT l."assignedUserId"
    INTO target_user_id
  FROM "WorkOrder" wo
  JOIN "DiagnosticRequest" dr ON dr."id" = wo."diagnosticRequestId"
  JOIN "Lead" l ON l."id" = dr."leadId"
  JOIN "User" u ON u."id" = l."assignedUserId" AND u."isActive" = TRUE
  WHERE wo."id" = p_work_order_id
    AND l."assignedUserId" IS NOT NULL
  LIMIT 1;

  RETURN target_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION turbolev_work_order_context(p_work_order_id TEXT)
RETURNS TABLE(client_id TEXT, vehicle_id TEXT)
LANGUAGE SQL
STABLE
AS $$
  SELECT wo."clientId", wo."vehicleId"
  FROM "WorkOrder" wo
  WHERE wo."id" = p_work_order_id;
$$;

CREATE OR REPLACE FUNCTION turbolev_sync_estimate_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'estimate:' || NEW."id" || ':decision';
  target_user_id TEXT;
  ctx RECORD;
BEGIN
  IF NEW."status"::text = 'SENT' THEN
    target_user_id := turbolev_work_order_responsible_user(
      NEW."workOrderId",
      ARRAY['SERVICE_ADVISOR','STATION_MANAGER','OWNER','EXECUTIVE_DIRECTOR']
    );
    SELECT * INTO ctx FROM turbolev_work_order_context(NEW."workOrderId");

    IF target_user_id IS NOT NULL THEN
      INSERT INTO "CrmTask" (
        "id", "title", "description", "status", "priority", "assignedUserId", "dueAt",
        "sourceType", "sourceId", "clientId", "vehicleId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
      ) VALUES (
        turbolev_task_id(NEW."id"),
        'Отримати погодження кошторису',
        'Кошторис відправлено клієнту. Потрібно отримати рішення та зафіксувати погодження або відмову.',
        'OPEN', 'HIGH', target_user_id,
        COALESCE(NEW."sentAt", CURRENT_TIMESTAMP) + INTERVAL '2 hours',
        'ESTIMATE', NEW."id", ctx.client_id, ctx.vehicle_id, TRUE, task_key,
        jsonb_build_object('workOrderId', NEW."workOrderId", 'workOrderTab', 'estimate', 'estimateId', NEW."id", 'revision', NEW."revision", 'status', NEW."status"::text),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
      )
      ON CONFLICT ("dedupeKey") DO UPDATE SET
        "title" = EXCLUDED."title",
        "description" = EXCLUDED."description",
        "status" = 'OPEN',
        "priority" = EXCLUDED."priority",
        "assignedUserId" = EXCLUDED."assignedUserId",
        "dueAt" = EXCLUDED."dueAt",
        "completedAt" = NULL,
        "clientId" = EXCLUDED."clientId",
        "vehicleId" = EXCLUDED."vehicleId",
        "metadata" = EXCLUDED."metadata",
        "updatedAt" = CURRENT_TIMESTAMP;
    END IF;
  ELSE
    UPDATE "CrmTask"
       SET "status" = 'DONE', "completedAt" = COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt" = CURRENT_TIMESTAMP
     WHERE "dedupeKey" = task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "WorkOrderEstimate_task_after_insert" ON "WorkOrderEstimate";
CREATE TRIGGER "WorkOrderEstimate_task_after_insert"
AFTER INSERT ON "WorkOrderEstimate"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_estimate_task();

DROP TRIGGER IF EXISTS "WorkOrderEstimate_task_after_update" ON "WorkOrderEstimate";
CREATE TRIGGER "WorkOrderEstimate_task_after_update"
AFTER UPDATE OF "status", "sentAt", "revision" ON "WorkOrderEstimate"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_estimate_task();

CREATE OR REPLACE FUNCTION turbolev_sync_parts_request_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'parts-request:' || NEW."id" || ':active';
  target_user_id TEXT;
  task_title TEXT;
  task_description TEXT;
  task_priority TEXT := 'HIGH';
  task_due TIMESTAMP(3);
  ctx RECORD;
BEGIN
  IF NEW."status"::text IN ('NEW','SELECTING','SELECTED','WAITING_APPROVAL','APPROVED','ORDER_REQUIRED','ORDERED','PARTIALLY_RECEIVED') THEN
    IF NEW."status"::text IN ('SELECTED','WAITING_APPROVAL') THEN
      target_user_id := turbolev_work_order_responsible_user(
        NEW."workOrderId",
        ARRAY['SERVICE_ADVISOR','STATION_MANAGER','OWNER','EXECUTIVE_DIRECTOR']
      );
    ELSE
      target_user_id := turbolev_work_order_responsible_user(
        NEW."workOrderId",
        ARRAY['PARTS_SPECIALIST','WAREHOUSE_KEEPER','SERVICE_ADVISOR','STATION_MANAGER','OWNER','EXECUTIVE_DIRECTOR']
      );
    END IF;

    task_title := CASE NEW."status"::text
      WHEN 'NEW' THEN 'Почати підбір запчастин'
      WHEN 'SELECTING' THEN 'Завершити підбір запчастин'
      WHEN 'SELECTED' THEN 'Погодити підібрані запчастини'
      WHEN 'WAITING_APPROVAL' THEN 'Отримати погодження запчастин'
      WHEN 'APPROVED' THEN 'Підготувати запчастини до замовлення'
      WHEN 'ORDER_REQUIRED' THEN 'Замовити запчастини'
      WHEN 'ORDERED' THEN 'Контролювати поставку запчастин'
      WHEN 'PARTIALLY_RECEIVED' THEN 'Доприйняти решту запчастин'
      ELSE 'Опрацювати запит на запчастини'
    END;
    task_description := 'Автоматична задача по запиту на запчастини. Після зміни статусу відповідальна задача оновиться автоматично.';
    task_priority := CASE WHEN NEW."status"::text IN ('NEW','ORDER_REQUIRED','PARTIALLY_RECEIVED') THEN 'HIGH' ELSE 'MEDIUM' END;
    task_due := CURRENT_TIMESTAMP + CASE NEW."status"::text
      WHEN 'NEW' THEN INTERVAL '1 hour'
      WHEN 'SELECTING' THEN INTERVAL '3 hours'
      WHEN 'SELECTED' THEN INTERVAL '2 hours'
      WHEN 'WAITING_APPROVAL' THEN INTERVAL '4 hours'
      WHEN 'APPROVED' THEN INTERVAL '2 hours'
      WHEN 'ORDER_REQUIRED' THEN INTERVAL '1 hour'
      WHEN 'ORDERED' THEN INTERVAL '1 day'
      WHEN 'PARTIALLY_RECEIVED' THEN INTERVAL '4 hours'
      ELSE INTERVAL '4 hours'
    END;
    SELECT * INTO ctx FROM turbolev_work_order_context(NEW."workOrderId");

    IF target_user_id IS NOT NULL THEN
      INSERT INTO "CrmTask" (
        "id", "title", "description", "status", "priority", "assignedUserId", "dueAt",
        "sourceType", "sourceId", "clientId", "vehicleId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
      ) VALUES (
        turbolev_task_id(NEW."id"), task_title, task_description, 'OPEN', task_priority, target_user_id, task_due,
        'PARTS_REQUEST', NEW."id", ctx.client_id, ctx.vehicle_id, TRUE, task_key,
        jsonb_build_object('workOrderId', NEW."workOrderId", 'workOrderTab', 'parts', 'partsRequestId', NEW."id", 'status', NEW."status"::text, 'paymentRequired', NEW."paymentRequired"),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
      )
      ON CONFLICT ("dedupeKey") DO UPDATE SET
        "title" = EXCLUDED."title",
        "description" = EXCLUDED."description",
        "status" = 'OPEN',
        "priority" = EXCLUDED."priority",
        "assignedUserId" = EXCLUDED."assignedUserId",
        "dueAt" = EXCLUDED."dueAt",
        "completedAt" = NULL,
        "clientId" = EXCLUDED."clientId",
        "vehicleId" = EXCLUDED."vehicleId",
        "metadata" = EXCLUDED."metadata",
        "updatedAt" = CURRENT_TIMESTAMP;
    END IF;
  ELSE
    UPDATE "CrmTask"
       SET "status" = 'DONE', "completedAt" = COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt" = CURRENT_TIMESTAMP
     WHERE "dedupeKey" = task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "PartsRequest_task_after_insert" ON "PartsRequest";
CREATE TRIGGER "PartsRequest_task_after_insert"
AFTER INSERT ON "PartsRequest"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_parts_request_task();

DROP TRIGGER IF EXISTS "PartsRequest_task_after_update" ON "PartsRequest";
CREATE TRIGGER "PartsRequest_task_after_update"
AFTER UPDATE OF "status", "paymentRequired", "paymentConfirmedAt" ON "PartsRequest"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_parts_request_task();

CREATE OR REPLACE FUNCTION turbolev_sync_payment_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'payment:' || NEW."id" || ':receivable';
  target_user_id TEXT;
  ctx RECORD;
  task_title TEXT;
  task_priority TEXT;
  task_due TIMESTAMP(3);
  outstanding NUMERIC;
BEGIN
  IF NEW."direction"::text = 'RECEIVABLE'
     AND NEW."workOrderId" IS NOT NULL
     AND NEW."status"::text IN ('OPEN','PARTIALLY_PAID','OVERDUE') THEN
    target_user_id := turbolev_work_order_responsible_user(
      NEW."workOrderId",
      ARRAY['ACCOUNTANT','STATION_MANAGER','OWNER','EXECUTIVE_DIRECTOR']
    );
    SELECT * INTO ctx FROM turbolev_work_order_context(NEW."workOrderId");
    outstanding := GREATEST(0, NEW."amount" - NEW."settledAmount");
    task_title := CASE NEW."status"::text
      WHEN 'OVERDUE' THEN 'Стягнути прострочену оплату по ЗН'
      WHEN 'PARTIALLY_PAID' THEN 'Отримати залишок оплати по ЗН'
      ELSE 'Прийняти оплату по ЗН'
    END;
    task_priority := CASE WHEN NEW."status"::text = 'OVERDUE' THEN 'CRITICAL' ELSE 'HIGH' END;
    task_due := COALESCE(NEW."dueAt", CURRENT_TIMESTAMP + INTERVAL '4 hours');

    IF target_user_id IS NOT NULL THEN
      INSERT INTO "CrmTask" (
        "id", "title", "description", "status", "priority", "assignedUserId", "dueAt",
        "sourceType", "sourceId", "clientId", "vehicleId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
      ) VALUES (
        turbolev_task_id(NEW."id"), task_title,
        'До сплати: ' || outstanding::text || ' ' || NEW."currency" || '. Після повної оплати задача закриється автоматично.',
        'OPEN', task_priority, target_user_id, task_due,
        'PAYMENT', NEW."id", COALESCE(NEW."clientId", ctx.client_id), ctx.vehicle_id, TRUE, task_key,
        jsonb_build_object('workOrderId', NEW."workOrderId", 'workOrderTab', 'payment', 'obligationId', NEW."id", 'status', NEW."status"::text, 'amount', NEW."amount", 'settledAmount', NEW."settledAmount", 'currency', NEW."currency"),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
      )
      ON CONFLICT ("dedupeKey") DO UPDATE SET
        "title" = EXCLUDED."title",
        "description" = EXCLUDED."description",
        "status" = 'OPEN',
        "priority" = EXCLUDED."priority",
        "assignedUserId" = EXCLUDED."assignedUserId",
        "dueAt" = EXCLUDED."dueAt",
        "completedAt" = NULL,
        "clientId" = EXCLUDED."clientId",
        "vehicleId" = EXCLUDED."vehicleId",
        "metadata" = EXCLUDED."metadata",
        "updatedAt" = CURRENT_TIMESTAMP;
    END IF;
  ELSE
    UPDATE "CrmTask"
       SET "status" = 'DONE', "completedAt" = COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt" = CURRENT_TIMESTAMP
     WHERE "dedupeKey" = task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "FinancialObligation_task_after_insert" ON "FinancialObligation";
CREATE TRIGGER "FinancialObligation_task_after_insert"
AFTER INSERT ON "FinancialObligation"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_payment_task();

DROP TRIGGER IF EXISTS "FinancialObligation_task_after_update" ON "FinancialObligation";
CREATE TRIGGER "FinancialObligation_task_after_update"
AFTER UPDATE OF "status", "settledAmount", "dueAt", "amount" ON "FinancialObligation"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_payment_task();

CREATE OR REPLACE FUNCTION turbolev_sync_qc_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'qc:' || NEW."id" || ':active';
  target_user_id TEXT;
  ctx RECORD;
  task_title TEXT;
  task_priority TEXT;
BEGIN
  IF NEW."status"::text IN ('PENDING','IN_PROGRESS','FAILED','RECHECK') THEN
    target_user_id := turbolev_work_order_responsible_user(
      NEW."workOrderId",
      ARRAY['STATION_MANAGER','OWNER','EXECUTIVE_DIRECTOR']
    );
    SELECT * INTO ctx FROM turbolev_work_order_context(NEW."workOrderId");
    task_title := CASE NEW."status"::text
      WHEN 'PENDING' THEN 'Провести контроль якості'
      WHEN 'IN_PROGRESS' THEN 'Завершити контроль якості'
      WHEN 'FAILED' THEN 'Опрацювати невдалий QC'
      WHEN 'RECHECK' THEN 'Повторно провести контроль якості'
      ELSE 'Опрацювати контроль якості'
    END;
    task_priority := CASE WHEN NEW."status"::text IN ('FAILED','RECHECK') THEN 'CRITICAL' ELSE 'HIGH' END;

    IF target_user_id IS NOT NULL THEN
      INSERT INTO "CrmTask" (
        "id", "title", "description", "status", "priority", "assignedUserId", "dueAt",
        "sourceType", "sourceId", "clientId", "vehicleId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
      ) VALUES (
        turbolev_task_id(NEW."id"), task_title,
        'Контроль якості прив’язаний до замовлення-наряду. Після успішного PASS задача закриється автоматично.',
        'OPEN', task_priority, target_user_id,
        CURRENT_TIMESTAMP + CASE WHEN NEW."status"::text IN ('FAILED','RECHECK') THEN INTERVAL '1 hour' ELSE INTERVAL '2 hours' END,
        'QC', NEW."id", ctx.client_id, ctx.vehicle_id, TRUE, task_key,
        jsonb_build_object('workOrderId', NEW."workOrderId", 'workOrderTab', 'qc', 'qualityControlId', NEW."id", 'attempt', NEW."attempt", 'status', NEW."status"::text),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
      )
      ON CONFLICT ("dedupeKey") DO UPDATE SET
        "title" = EXCLUDED."title",
        "description" = EXCLUDED."description",
        "status" = 'OPEN',
        "priority" = EXCLUDED."priority",
        "assignedUserId" = EXCLUDED."assignedUserId",
        "dueAt" = EXCLUDED."dueAt",
        "completedAt" = NULL,
        "clientId" = EXCLUDED."clientId",
        "vehicleId" = EXCLUDED."vehicleId",
        "metadata" = EXCLUDED."metadata",
        "updatedAt" = CURRENT_TIMESTAMP;
    END IF;
  ELSE
    UPDATE "CrmTask"
       SET "status" = 'DONE', "completedAt" = COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt" = CURRENT_TIMESTAMP
     WHERE "dedupeKey" = task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "WorkOrderQualityControl_task_after_insert" ON "WorkOrderQualityControl";
CREATE TRIGGER "WorkOrderQualityControl_task_after_insert"
AFTER INSERT ON "WorkOrderQualityControl"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_qc_task();

DROP TRIGGER IF EXISTS "WorkOrderQualityControl_task_after_update" ON "WorkOrderQualityControl";
CREATE TRIGGER "WorkOrderQualityControl_task_after_update"
AFTER UPDATE OF "status", "attempt", "startedAt", "completedAt" ON "WorkOrderQualityControl"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_qc_task();

CREATE OR REPLACE FUNCTION turbolev_sync_warranty_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'warranty:' || NEW."id" || ':active';
  work_order_id TEXT;
  target_user_id TEXT;
  ctx RECORD;
  task_title TEXT;
BEGIN
  SELECT wol."workOrderId" INTO work_order_id
  FROM "WorkOrderLine" wol
  WHERE wol."id" = NEW."workOrderLineId";

  IF work_order_id IS NOT NULL AND NEW."status"::text IN ('OPEN','REVIEW','APPROVED') THEN
    target_user_id := turbolev_work_order_responsible_user(
      work_order_id,
      ARRAY['STATION_MANAGER','OWNER','EXECUTIVE_DIRECTOR']
    );
    SELECT * INTO ctx FROM turbolev_work_order_context(work_order_id);
    task_title := CASE NEW."status"::text
      WHEN 'OPEN' THEN 'Розглянути гарантійне звернення'
      WHEN 'REVIEW' THEN 'Завершити перевірку гарантійного звернення'
      WHEN 'APPROVED' THEN 'Організувати гарантійне усунення'
      ELSE 'Опрацювати гарантійне звернення'
    END;

    IF target_user_id IS NOT NULL THEN
      INSERT INTO "CrmTask" (
        "id", "title", "description", "status", "priority", "assignedUserId", "dueAt",
        "sourceType", "sourceId", "clientId", "vehicleId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
      ) VALUES (
        turbolev_task_id(NEW."id"), task_title,
        LEFT(NEW."reason", 1000),
        'OPEN', CASE WHEN NEW."status"::text = 'OPEN' THEN 'HIGH' ELSE 'MEDIUM' END,
        target_user_id, CURRENT_TIMESTAMP + CASE WHEN NEW."status"::text = 'OPEN' THEN INTERVAL '2 hours' ELSE INTERVAL '1 day' END,
        'WARRANTY', NEW."id", ctx.client_id, ctx.vehicle_id, TRUE, task_key,
        jsonb_build_object('workOrderId', work_order_id, 'workOrderTab', 'history', 'warrantyClaimId', NEW."id", 'workOrderLineId', NEW."workOrderLineId", 'status', NEW."status"::text),
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
      )
      ON CONFLICT ("dedupeKey") DO UPDATE SET
        "title" = EXCLUDED."title",
        "description" = EXCLUDED."description",
        "status" = 'OPEN',
        "priority" = EXCLUDED."priority",
        "assignedUserId" = EXCLUDED."assignedUserId",
        "dueAt" = EXCLUDED."dueAt",
        "completedAt" = NULL,
        "clientId" = EXCLUDED."clientId",
        "vehicleId" = EXCLUDED."vehicleId",
        "metadata" = EXCLUDED."metadata",
        "updatedAt" = CURRENT_TIMESTAMP;
    END IF;
  ELSE
    UPDATE "CrmTask"
       SET "status" = 'DONE', "completedAt" = COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt" = CURRENT_TIMESTAMP
     WHERE "dedupeKey" = task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "WarrantyClaim_task_after_insert" ON "WarrantyClaim";
CREATE TRIGGER "WarrantyClaim_task_after_insert"
AFTER INSERT ON "WarrantyClaim"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_warranty_task();

DROP TRIGGER IF EXISTS "WarrantyClaim_task_after_update" ON "WarrantyClaim";
CREATE TRIGGER "WarrantyClaim_task_after_update"
AFTER UPDATE OF "status", "reason", "resolution", "closedAt" ON "WarrantyClaim"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_warranty_task();

-- Backfill active downstream workflow tasks using the same trigger functions.
UPDATE "WorkOrderEstimate"
   SET "updatedAt" = "updatedAt"
 WHERE "status"::text = 'SENT';

UPDATE "PartsRequest"
   SET "updatedAt" = "updatedAt"
 WHERE "status"::text IN ('NEW','SELECTING','SELECTED','WAITING_APPROVAL','APPROVED','ORDER_REQUIRED','ORDERED','PARTIALLY_RECEIVED');

UPDATE "FinancialObligation"
   SET "updatedAt" = "updatedAt"
 WHERE "direction"::text = 'RECEIVABLE'
   AND "workOrderId" IS NOT NULL
   AND "status"::text IN ('OPEN','PARTIALLY_PAID','OVERDUE');

UPDATE "WorkOrderQualityControl"
   SET "updatedAt" = "updatedAt"
 WHERE "status"::text IN ('PENDING','IN_PROGRESS','FAILED','RECHECK');

UPDATE "WarrantyClaim"
   SET "updatedAt" = "updatedAt"
 WHERE "status"::text IN ('OPEN','REVIEW','APPROVED');
