import type { Metadata } from "next";
import "./globals.css";
import "./theme-semantic-contract.css";
import "./scrollbars.css";
import "./theme-fixes.css";
import "./chatgpt-typography.css";
import "./pipeline-navigation.css";
import "./dashboard-actions.css";
import "./sidebar-groups.css";
import "./crm-core.css";
import "./new-request-wizard.css";
import "./new-request-wizard-v4.css";
import "./new-request-page.css";
import "./vehicle-identification-v3.css";
import "./vehicle-configuration.css";
import "./vehicle-lookup.css";
import "./vehicle-intelligence.css";
import "./vehicle-presentation.css";
import "./quick-lookup-order.css";
import "./leads.css";
import "./leads-kpi.css";
import "./lead-details.css";
import "./communications.css";
import "./communications-header-polish.css";
import "./communication-activation-diagnostics.css";
import "./clients-vehicles-rich-cards.css";
import "./client-communication-bridge.css";
import "./settings-suppliers.css";
import "./settings-integrations.css";
import "./settings-page-layout-fix.css";
import "./ui-readability.css";
import "./layout-stability.css";
import "./responsive-popups.css";
import "./personnel-wizard-polish.css";
import "./typography-final.css";
import "./auth/sidebar-rail-width-fix.css";
import "./auth/sidebar-compact-logo.css";
import "./responsive-ui-contract.css";
import "./planner-layout.css";
import "./analytics-funnel-agreed-layout.css";
import "./appearance-global.css";
import "@/src/lib/global-phone-copy.css";
import { PhoneInputNormalizer } from "./phone-input-normalizer";
import { LeadDetailsEnhancer } from "./lead-details-enhancer";
import { VehicleConfigurationEnhancer } from "./vehicle-configuration-enhancer";
import { WorkflowFilterEnhancer } from "./workflow-filter-enhancer";
import { CrmDataBridge } from "./crm-data-bridge";
import { ClientsVehiclesRichCards } from "./clients-vehicles-rich-cards";
import { WorkPriceTableEnhancer } from "./work-price-table-enhancer";
import { NewRequestContextBridge } from "./new-request-context-bridge";
import { CrmScrollReset } from "./crm-scroll-reset";
import { ActiveTerminologyBridge } from "./active-terminology-bridge";
import { TelephonyRealtimeBridge } from "./telephony-realtime-bridge";
import { PlannerEditEnhancer } from "./planner-edit-enhancer";
import { GlobalKeyboardShortcuts } from "./global-keyboard-shortcuts";
import { GlobalSmartSearchPalette } from "./global-smart-search-palette";
import { OptionalMechanicBookingBridge } from "./optional-mechanic-booking-bridge";
import { MechanicClarificationBridge } from "./mechanic-clarification-bridge";
import { CommunicationActivationDiagnosticsBridge } from "./communication-activation-diagnostics-bridge";
import { ClientCommunicationBridge } from "./client-communication-bridge";
import { CommunicationsStatusEnhancer } from "./communications-status-enhancer";
import { CommunicationsDeeplinkEnhancer } from "./communications-deeplink-enhancer";
import { BusinessFlowRouteBridge } from "./business-flow-route-bridge";
import { LegacyActiveActionBridge } from "./legacy-active-action-bridge";
import { ClientNewRequestContextEnhancer } from "./client-new-request-context-enhancer";
import { VehicleHealthEnhancer } from "./vehicle-health-enhancer";
import { WorkOrderContextLinksEnhancer } from "./work-order-context-links-enhancer";
import { VehiclePresentationBridge } from "./vehicle-presentation-bridge";
import { AnalyticsDashboardWalkInBridge } from "./analytics-dashboard-walk-in-bridge";
import { AnalyticsOwnerEconomicsBridge } from "./analytics-owner-economics-bridge";
import { GlobalPhoneCopy } from "@/src/lib/global-phone-copy";
import { AppearanceThemeBridge } from "./appearance-theme-bridge";

export const metadata: Metadata = { title: "Turbo LEV CRM", description: "Операційна CRM-система СТО Turbo LEV" };
const themeBootstrap = `(function(){try{var root=document.documentElement;var cached=window.localStorage.getItem('turbolev:appearance-cache:v1');if(cached){var a=JSON.parse(cached);var mode=a.themeMode==='light'||a.themeMode==='dark'||a.themeMode==='auto'?a.themeMode:'dark';var resolved=mode==='light'||mode==='dark'?mode:(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');var density=a.density==='compact'||a.density==='comfortable'?a.density:'standard';var radius=a.radius==='sharp'||a.radius==='soft'?a.radius:'standard';var sidebar=a.sidebar==='compact'?'compact':'expanded';var scale=a.scale==='compact'||a.scale==='comfortable'?a.scale:'standard';var scaleValues=scale==='compact'?['13px','13px','11px','12px','28px']:scale==='comfortable'?['15px','16px','13px','14px','32px']:['14px','15px','12px','13px','30px'];var radiusValues=radius==='sharp'?['6px','7px','9px']:radius==='soft'?['14px','11px','16px']:['10px','9px','12px'];var densityValues=density==='compact'?['8px','12px','38px','36px']:density==='comfortable'?['18px','22px','50px','44px']:['12px','18px','44px','40px'];var vars={'--crm-bg':a.background,'--crm-panel':a.panel,'--crm-panel-raised':a.panelRaised,'--crm-line':a.line,'--crm-text':a.text,'--crm-muted':a.muted,'--crm-accent':a.accent,'--crm-accent-strong':a.accentStrong,'--crm-success':a.success,'--crm-warning':a.warning,'--crm-danger':a.danger,'--crm-info':a.info,'--bg':a.background,'--panel':a.panel,'--panel-2':a.panelRaised,'--panel-raised':a.panelRaised,'--line':a.line,'--text':a.text,'--muted':a.muted,'--orange':a.accent,'--orange-2':a.accentStrong,'--accent':a.accent,'--accent-strong':a.accentStrong,'--green':a.success,'--yellow':a.warning,'--red':a.danger,'--blue':a.info,'--sidebar':a.panel,'--ui-font':a.font==='inter'?'Inter, "Segoe UI", sans-serif':a.font==='manrope'?'Manrope, "Segoe UI", sans-serif':'"Segoe UI Variable Text", "Segoe UI", sans-serif','--crm-body-size':scaleValues[0],'--crm-control-size':scaleValues[1],'--crm-meta-size':scaleValues[2],'--crm-font-label':scaleValues[3],'--crm-font-page-title':scaleValues[4],'--crm-radius':radiusValues[0],'--crm-control-radius':radiusValues[1],'--crm-card-radius':radiusValues[2],'--crm-density-gap':densityValues[0],'--crm-density-padding':densityValues[1],'--crm-density-row':densityValues[2],'--crm-density-control':densityValues[3],'--crm-sidebar-width':sidebar==='compact'?'214px':'265px','--crm-sidebar-logo-width':sidebar==='compact'?'170px':'196px'};root.dataset.crmAppearance='configured';root.dataset.crmPreset=a.preset||'turbo-dark';root.dataset.crmDensity=density;root.dataset.crmRadius=radius;root.dataset.crmSidebar=sidebar;root.dataset.theme=resolved;root.dataset.themeMode=mode;root.style.colorScheme=resolved;Object.keys(vars).forEach(function(k){if(typeof vars[k]==='string')root.style.setProperty(k,vars[k]);});}else{var saved=window.localStorage.getItem('turbolev-theme-mode')||window.localStorage.getItem('turbolev-theme')||'auto';if(saved!=='light'&&saved!=='dark'&&saved!=='auto')saved='auto';var resolved=saved==='light'||saved==='dark'?saved:(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');root.dataset.theme=resolved;root.dataset.themeMode=saved;root.style.colorScheme=resolved;}}catch(e){}})();`;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="uk" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{ __html: themeBootstrap }} /></head><body><AppearanceThemeBridge/><GlobalKeyboardShortcuts/><GlobalSmartSearchPalette/><GlobalPhoneCopy/><BusinessFlowRouteBridge/><MechanicClarificationBridge/><CrmScrollReset/><ActiveTerminologyBridge/><PlannerEditEnhancer/><PhoneInputNormalizer/><LeadDetailsEnhancer/><VehicleConfigurationEnhancer/><WorkflowFilterEnhancer/><CrmDataBridge/><ClientsVehiclesRichCards/><WorkPriceTableEnhancer/><NewRequestContextBridge/><OptionalMechanicBookingBridge/><TelephonyRealtimeBridge/><CommunicationActivationDiagnosticsBridge/><ClientCommunicationBridge/><CommunicationsStatusEnhancer/><CommunicationsDeeplinkEnhancer/><LegacyActiveActionBridge/><ClientNewRequestContextEnhancer/><VehicleHealthEnhancer/><WorkOrderContextLinksEnhancer/><VehiclePresentationBridge/><AnalyticsDashboardWalkInBridge/><AnalyticsOwnerEconomicsBridge/>{children}</body></html>;
}
