import type { Metadata } from "next";
import "./globals.css";
import "./theme-semantic-contract.css";
import "./scrollbars.css";
import "./theme-fixes.css";
import "./chatgpt-typography.css";
import "./pipeline-navigation.css";
import "./dashboard-actions.css";
import "./sidebar-groups.css";
import "./crm-core.css";
import "./new-request-wizard.css";
import "./new-request-wizard-v4.css";
import "./vehicle-identification-v3.css";
import "./vehicle-configuration.css";
import "./vehicle-lookup.css";
import "./vehicle-intelligence.css";
import "./quick-lookup-order.css";
import "./leads.css";
import "./leads-kpi.css";
import "./lead-details.css";
import "./communications.css";
import "./communications-header-polish.css";
import "./communication-activation-diagnostics.css";
import "./clients-vehicles-rich-cards.css";
import "./client-communication-bridge.css";
import "./settings-suppliers.css";
import "./settings-integrations.css";
import "./settings-page-layout-fix.css";
import "./ui-readability.css";
import "./layout-stability.css";
import "./responsive-popups.css";
import "./personnel-wizard-polish.css";
import "./typography-final.css";
import "./auth/sidebar-rail-width-fix.css";
import "./auth/sidebar-compact-logo.css";
import { PhoneInputNormalizer } from "./phone-input-normalizer";
import { LeadDetailsEnhancer } from "./lead-details-enhancer";
import { VehicleConfigurationEnhancer } from "./vehicle-configuration-enhancer";
import { WorkflowFilterEnhancer } from "./workflow-filter-enhancer";
import { CrmDataBridge } from "./crm-data-bridge";
import { ClientsVehiclesRichCards } from "./clients-vehicles-rich-cards";
import { WorkPriceTableEnhancer } from "./work-price-table-enhancer";
import { NewRequestContextBridge } from "./new-request-context-bridge";
import { CrmScrollReset } from "./crm-scroll-reset";
import { ActiveTerminologyBridge } from "./active-terminology-bridge";
import { TelephonyRealtimeBridge } from "./telephony-realtime-bridge";
import { PlannerEditEnhancer } from "./planner-edit-enhancer";
import { GlobalKeyboardShortcuts } from "./global-keyboard-shortcuts";
import { NewRequestVinDisplayEnhancer } from "./new-request-vin-display-enhancer";
import { DiagnosticBookingEnhancer } from "./diagnostic-booking-enhancer";
import { OptionalMechanicBookingBridge } from "./optional-mechanic-booking-bridge";
import { CabinetAutoRouter } from "./cabinet-auto-router";
import { ServiceAdvisorCabinetBridge } from "./service-advisor-cabinet-bridge";
import { MechanicClarificationBridge } from "./mechanic-clarification-bridge";
import { CommunicationActivationDiagnosticsBridge } from "./communication-activation-diagnostics-bridge";
import { ClientCommunicationBridge } from "./client-communication-bridge";

export const metadata: Metadata = { title: "Turbo LEV CRM", description: "Операційна CRM-система СТО Turbo LEV" };
const themeBootstrap = `(function(){try{var saved=window.localStorage.getItem('turbolev-theme-mode')||window.localStorage.getItem('turbolev-theme')||'auto';if(saved!=='light'&&saved!=='dark'&&saved!=='auto')saved='auto';var resolved=saved==='light'||saved==='dark'?saved:(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');var root=document.documentElement;root.dataset.theme=resolved;root.dataset.themeMode=saved;root.style.colorScheme=resolved;}catch(e){}})();`;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="uk" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{ __html: themeBootstrap }} /></head><body><GlobalKeyboardShortcuts/><CabinetAutoRouter/><ServiceAdvisorCabinetBridge/><MechanicClarificationBridge/><CrmScrollReset/><ActiveTerminologyBridge/><PlannerEditEnhancer/><PhoneInputNormalizer/><LeadDetailsEnhancer/><VehicleConfigurationEnhancer/><WorkflowFilterEnhancer/><CrmDataBridge/><ClientsVehiclesRichCards/><WorkPriceTableEnhancer/><NewRequestContextBridge/><NewRequestVinDisplayEnhancer/><DiagnosticBookingEnhancer/><OptionalMechanicBookingBridge/><TelephonyRealtimeBridge/><CommunicationActivationDiagnosticsBridge/><ClientCommunicationBridge/>{children}</body></html>;
}
