import type { Metadata } from "next";
import "./globals.css";
import "./theme-semantic-contract.css";
import "./scrollbars.css";
import "./theme-fixes.css";
import "./chatgpt-typography.css";
import "./pipeline-navigation.css";
import "./dashboard-actions.css";
import "./sidebar-groups.css";
import "./crm-core.css";
import "./new-request-wizard.css";
import "./new-request-wizard-v4.css";
import "./new-request-page.css";
import "./vehicle-identification-v3.css";
import "./vehicle-configuration.css";
import "./vehicle-lookup.css";
import "./vehicle-intelligence.css";
import "./vehicle-presentation.css";
import "./quick-lookup-order.css";
import "./leads.css";
import "./leads-kpi.css";
import "./lead-details.css";
import "./communications.css";
import "./communications-header-polish.css";
import "./communication-activation-diagnostics.css";
import "./clients-vehicles-rich-cards.css";
import "./client-communication-bridge.css";
import "./settings-suppliers.css";
import "./settings-integrations.css";
import "./settings-page-layout-fix.css";
import "./ui-readability.css";
import "./layout-stability.css";
import "./responsive-popups.css";
import "./personnel-wizard-polish.css";
import "./typography-final.css";
import "./auth/sidebar-rail-width-fix.css";
import "./auth/sidebar-compact-logo.css";
import "./responsive-ui-contract.css";
import "./planner-layout.css";
import "./analytics-funnel-agreed-layout.css";
import "./appearance-global.css";
import "@/src/lib/global-phone-copy.css";
import "./crm-responsive-standard.css";
import "./communications-visual-polish.css";
import { PhoneInputNormalizer } from "./phone-input-normalizer";
import { LeadDetailsEnhancer } from "./lead-details-enhancer";
import { VehicleConfigurationEnhancer } from "./vehicle-configuration-enhancer";
import { WorkflowFilterEnhancer } from "./workflow-filter-enhancer";
import { CrmDataBridge } from "./crm-data-bridge";
import { ClientsVehiclesRichCards } from "./clients-vehicles-rich-cards";
import { WorkPriceTableEnhancer } from "./work-price-table-enhancer";
import { NewRequestContextBridge } from "./new-request-context-bridge";
import { CrmScrollReset } from "./crm-scroll-reset";
import { ActiveTerminologyBridge } from "./active-terminology-bridge";
import { TelephonyRealtimeBridge } from "./telephony-realtime-bridge";
import { PlannerEditEnhancer } from "./planner-edit-enhancer";
import { GlobalKeyboardShortcuts } from "./global-keyboard-shortcuts";
import { GlobalSmartSearchPalette } from "./global-smart-search-palette";
import { MechanicBookingRequiredBridge } from "./optional-mechanic-booking-bridge";
import { MechanicClarificationBridge } from "./mechanic-clarification-bridge";
import { CommunicationActivationDiagnosticsBridge } from "./communication-activation-diagnostics-bridge";
import { ClientCommunicationBridge } from "./client-communication-bridge";
import { CommunicationsStatusEnhancer } from "./communications-status-enhancer";
import { CommunicationsDeeplinkEnhancer } from "./communications-deeplink-enhancer";
import { BusinessFlowRouteBridge } from "./business-flow-route-bridge";
import { LegacyActiveActionBridge } from "./legacy-active-action-bridge";
import { ClientNewRequestContextEnhancer } from "./client-new-request-context-enhancer";
import { VehicleHealthEnhancer } from "./vehicle-health-enhancer";
import { WorkOrderContextLinksEnhancer } from "./work-order-context-links-enhancer";
import { VehiclePresentationBridge } from "./vehicle-presentation-bridge";
import { AnalyticsDashboardWalkInBridge } from "./analytics-dashboard-walk-in-bridge";
import { AnalyticsOwnerEconomicsBridge } from "./analytics-owner-economics-bridge";
import { GlobalPhoneCopy } from "@/src/lib/global-phone-copy";
import { AppearanceThemeBridge } from "./appearance-theme-bridge";

export const metadata: Metadata = { title: "Turbo LEV CRM", description: "Операційна CRM-система СТО Turbo LEV" };
const themeBootstrap = `(function(){try{var root=document.documentElement;var cached=window.localStorage.getItem('turbolev:appearance-cache:v1');if(cached){var a=JSON.parse(cached);var mode=a.themeMode==='light'||a.themeMode==='dark'||a.themeMode==='auto'?a.themeMode:'dark';var resolved=mode==='light'||mode==='dark'?mode:(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');root.dataset.crmAppearance='configured';root.dataset.crmPreset=a.preset||'turbo-dark';root.dataset.crmDensity=a.density||'standard';root.dataset.crmRadius=a.radius||'standard';root.dataset.crmSidebar=a.sidebar||'expanded';root.dataset.theme=resolved;root.dataset.themeMode=mode;root.style.colorScheme=resolved;var vars={'--bg':a.background,'--panel':a.panel,'--panel-2':a.panelRaised,'--line':a.line,'--text':a.text,'--muted':a.muted,'--orange':a.accent,'--orange-2':a.accentStrong,'--green':a.success,'--yellow':a.warning,'--red':a.danger,'--blue':a.info};Object.keys(vars).forEach(function(k){if(typeof vars[k]==='string')root.style.setProperty(k,vars[k]);});}else{var saved=window.localStorage.getItem('turbolev-theme-mode')||window.localStorage.getItem('turbolev-theme')||'auto';if(saved!=='light'&&saved!=='dark'&&saved!=='auto')saved='auto';var resolved=saved==='light'||saved==='dark'?saved:(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');root.dataset.theme=resolved;root.dataset.themeMode=saved;root.style.colorScheme=resolved;}}catch(e){}})();`;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="uk" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{ __html: themeBootstrap }} /></head><body><AppearanceThemeBridge/><GlobalKeyboardShortcuts/><GlobalSmartSearchPalette/><GlobalPhoneCopy/><BusinessFlowRouteBridge/><MechanicClarificationBridge/><CrmScrollReset/><ActiveTerminologyBridge/><PlannerEditEnhancer/><PhoneInputNormalizer/><LeadDetailsEnhancer/><VehicleConfigurationEnhancer/><WorkflowFilterEnhancer/><CrmDataBridge/><ClientsVehiclesRichCards/><WorkPriceTableEnhancer/><NewRequestContextBridge/><MechanicBookingRequiredBridge/><TelephonyRealtimeBridge/><CommunicationActivationDiagnosticsBridge/><ClientCommunicationBridge/><CommunicationsStatusEnhancer/><CommunicationsDeeplinkEnhancer/><LegacyActiveActionBridge/><ClientNewRequestContextEnhancer/><VehicleHealthEnhancer/><WorkOrderContextLinksEnhancer/><VehiclePresentationBridge/><AnalyticsDashboardWalkInBridge/><AnalyticsOwnerEconomicsBridge/>{children}</body></html>;
}
