"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { isCrmSection } from "./crm-navigation";
import { navigateCrm, type CrmRouteParams } from "./crm-route";
import styles from "./my-tasks.module.css";

type Task = {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  dueAt: string | null;
  autoGenerated: boolean;
};

type AttentionCategory =
  | "COMMUNICATIONS"
  | "SERVICE"
  | "DIAGNOSTICS"
  | "PARTS"
  | "SUPPLIERS"
  | "FINANCE"
  | "PAYROLL"
  | "POSTS"
  | "QUALITY"
  | "WARRANTY"
  | "MANUAL";

type AttentionLevel = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
type AttentionBucket = "ACTION" | "WAITING" | "MONITORING";
type AttentionAction = { label: string; section: string; params?: Record<string, string> };

type AttentionSignal = {
  id: string;
  sourceType: string;
  sourceId: string | null;
  taskId: string | null;
  title: string;
  description: string | null;
  reason: string;
  category: AttentionCategory;
  level: AttentionLevel;
  bucket: AttentionBucket;
  dueAt: string | null;
  occurredAt: string;
  isOverdue: boolean;
  overdueMinutes: number;
  isToday: boolean;
  autoGenerated: boolean;
  amount: number | null;
  currency: string | null;
  counterparty: string | null;
  action: AttentionAction | null;
  metadata: Record<string, unknown>;
};

type PostLoadPeriod = {
  date: string;
  utilizationPct: number;
  bookedHours: number;
  capacityHours: number;
  activePosts: number;
  posts: Array<{
    id: string;
    name: string;
    locationName: string;
    utilizationPct: number;
    bookedHours: number;
    capacityHours: number;
  }>;
};

type AttentionCenter = {
  signals: AttentionSignal[];
  summary: { total: number; critical: number; overdue: number; action: number; waiting: number; today: number };
  categories: Record<AttentionCategory, number>;
  postLoad: { today: PostLoadPeriod | null; tomorrow: PostLoadPeriod | null };
  generatedAt: string;
};

type Payload = { ok?: boolean; tasks?: Task[]; attention?: AttentionCenter; error?: string };
type ViewFilter = "ALL" | "CRITICAL" | "OVERDUE" | "ACTION" | "WAITING" | "TODAY" | "ARCHIVE";
type CategoryFilter = "ALL" | AttentionCategory;

const EMPTY_ATTENTION: AttentionCenter = {
  signals: [],
  summary: { total: 0, critical: 0, overdue: 0, action: 0, waiting: 0, today: 0 },
  categories: {
    COMMUNICATIONS: 0,
    SERVICE: 0,
    DIAGNOSTICS: 0,
    PARTS: 0,
    SUPPLIERS: 0,
    FINANCE: 0,
    PAYROLL: 0,
    POSTS: 0,
    QUALITY: 0,
    WARRANTY: 0,
    MANUAL: 0,
  },
  postLoad: { today: null, tomorrow: null },
  generatedAt: new Date(0).toISOString(),
};

const CATEGORY_LABEL: Record<AttentionCategory, string> = {
  COMMUNICATIONS: "Звернення",
  SERVICE: "СТО",
  DIAGNOSTICS: "Діагностика",
  PARTS: "Запчастини",
  SUPPLIERS: "Постачальники",
  FINANCE: "Фінанси",
  PAYROLL: "Зарплата",
  POSTS: "Пости",
  QUALITY: "Якість",
  WARRANTY: "Гарантії",
  MANUAL: "Мої задачі",
};

const LEVEL_LABEL: Record<AttentionLevel, string> = {
  CRITICAL: "Критично",
  HIGH: "Високий",
  MEDIUM: "Середній",
  LOW: "Низький",
};

const BUCKET_LABEL: Record<AttentionBucket, string> = {
  ACTION: "Потрібна дія",
  WAITING: "Очікуємо",
  MONITORING: "На контролі",
};

const CATEGORY_ORDER: AttentionCategory[] = [
  "COMMUNICATIONS",
  "SERVICE",
  "DIAGNOSTICS",
  "PARTS",
  "SUPPLIERS",
  "FINANCE",
  "PAYROLL",
  "POSTS",
  "QUALITY",
  "WARRANTY",
  "MANUAL",
];

function safeDate(value: string | null | undefined) {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function formatDateTime(value: string | null) {
  const date = safeDate(value);
  if (!date) return "Без дедлайну";
  return new Intl.DateTimeFormat("uk-UA", {
    day: "2-digit",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
}

function durationText(minutes: number) {
  if (minutes < 60) return `${Math.max(1, Math.round(minutes))} хв`;
  if (minutes < 24 * 60) {
    const hours = Math.floor(minutes / 60);
    const rest = Math.round(minutes % 60);
    return rest ? `${hours} год ${rest} хв` : `${hours} год`;
  }
  const days = Math.floor(minutes / (24 * 60));
  const hours = Math.floor((minutes % (24 * 60)) / 60);
  return hours ? `${days} дн ${hours} год` : `${days} дн`;
}

function signalTime(signal: AttentionSignal) {
  if (signal.isOverdue) return `прострочено ${durationText(signal.overdueMinutes)}`;
  if (signal.dueAt) return `до ${formatDateTime(signal.dueAt)}`;
  const occurred = safeDate(signal.occurredAt);
  if (!occurred) return "";
  const age = Math.max(0, Math.floor((Date.now() - occurred.getTime()) / 60_000));
  return age < 1 ? "щойно" : `${durationText(age)} тому`;
}

function formatMoney(value: number | null, currency: string | null) {
  if (value === null) return null;
  try {
    return new Intl.NumberFormat("uk-UA", {
      style: "currency",
      currency: currency || "UAH",
      maximumFractionDigits: 0,
    }).format(value);
  } catch {
    return `${Math.round(value).toLocaleString("uk-UA")} ${currency || "UAH"}`;
  }
}

function openAction(action: AttentionAction | null) {
  if (!action || !isCrmSection(action.section)) return;
  navigateCrm(action.section, (action.params || {}) as CrmRouteParams);
}

function isMissedCallSignal(signal: AttentionSignal) {
  const channel = typeof signal.metadata.channel === "string" ? signal.metadata.channel.toUpperCase() : "";
  const title = signal.title.toLocaleLowerCase("uk-UA");
  return signal.sourceType === "INQUIRY" && (channel === "BINOTEL" || title.includes("пропущ"));
}

function formatAttentionPhone(signal: AttentionSignal) {
  const raw = typeof signal.metadata.phone === "string" ? signal.metadata.phone : signal.counterparty;
  const value = raw?.trim() || "";
  const digits = value.replace(/\D/g, "");
  if (digits.length === 12 && digits.startsWith("380")) {
    return "+380 " + digits.slice(3, 5) + " " + digits.slice(5, 8) + " " + digits.slice(8, 10) + " " + digits.slice(10, 12);
  }
  return value || "Невідомий номер";
}

function compactSignalTime(signal: AttentionSignal) {
  return signal.isOverdue ? durationText(signal.overdueMinutes) + " без реакції" : signalTime(signal);
}

function matchesView(signal: AttentionSignal, filter: ViewFilter) {
  if (filter === "CRITICAL") return signal.level === "CRITICAL";
  if (filter === "OVERDUE") return signal.isOverdue;
  if (filter === "ACTION") return signal.bucket === "ACTION";
  if (filter === "WAITING") return signal.bucket === "WAITING";
  if (filter === "TODAY") return signal.isToday;
  return true;
}

function loadState(period: PostLoadPeriod | null) {
  if (!period || period.activePosts === 0) return "Немає активних постів";
  if (period.utilizationPct > 100) return "Перевантаження";
  if (period.utilizationPct >= 90) return "Майже повне";
  if (period.utilizationPct < 35) return "Низьке";
  if (period.utilizationPct < 55) return "Є резерв";
  return "Робоче";
}

export function MyTasks() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [attention, setAttention] = useState<AttentionCenter>(EMPTY_ATTENTION);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [title, setTitle] = useState("");
  const [dueAt, setDueAt] = useState("");
  const [priority, setPriority] = useState("MEDIUM");
  const [viewFilter, setViewFilter] = useState<ViewFilter>("ALL");
  const [categoryFilter, setCategoryFilter] = useState<CategoryFilter>("ALL");
  const [decisionSignal, setDecisionSignal] = useState<AttentionSignal | null>(null);

  const load = useCallback(async (initial = false) => {
    if (initial) setLoading(true);
    else setRefreshing(true);
    setError("");
    try {
      const response = await fetch("/api/tasks", { cache: "no-store", credentials: "include" });
      const body = await response.json() as Payload;
      if (!response.ok || !body.ok) throw new Error(body.error || "Не вдалося завантажити центр уваги");
      setTasks(body.tasks || []);
      setAttention(body.attention || EMPTY_ATTENTION);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Не вдалося завантажити центр уваги");
    } finally {
      if (initial) setLoading(false);
      else setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    void load(true);
    const refresh = () => { if (document.visibilityState === "visible") void load(false); };
    const onVisibility = () => { if (document.visibilityState === "visible") void load(false); };
    const interval = window.setInterval(refresh, 60_000);
    window.addEventListener("focus", refresh);
    window.addEventListener("turbolev:attention-refresh", refresh);
    document.addEventListener("visibilitychange", onVisibility);
    return () => {
      window.clearInterval(interval);
      window.removeEventListener("focus", refresh);
      window.removeEventListener("turbolev:attention-refresh", refresh);
      document.removeEventListener("visibilitychange", onVisibility);
    };
  }, [load]);

  const filteredSignals = useMemo(() => attention.signals.filter((signal) => {
    if (viewFilter === "ARCHIVE") return false;
    if (!matchesView(signal, viewFilter)) return false;
    if (categoryFilter !== "ALL" && signal.category !== categoryFilter) return false;
    return true;
  }), [attention.signals, categoryFilter, viewFilter]);

  const archivedTasks = useMemo(() => tasks
    .filter((task) => task.status === "DONE" || task.status === "CANCELLED")
    .slice(0, 100), [tasks]);

  const upcoming = useMemo(() => {
    const now = Date.now();
    return attention.signals
      .filter((signal) => !signal.isOverdue && signal.dueAt && new Date(signal.dueAt).getTime() >= now)
      .sort((a, b) => new Date(a.dueAt!).getTime() - new Date(b.dueAt!).getTime())
      .slice(0, 8);
  }, [attention.signals]);

  const visibleCategories = useMemo(() => CATEGORY_ORDER.filter((category) => attention.categories[category] > 0), [attention.categories]);

  async function patchTask(id: string, status: string) {
    setBusyId(id);
    setError("");
    try {
      const response = await fetch(`/api/tasks/${encodeURIComponent(id)}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ status }),
      });
      const body = await response.json() as { ok?: boolean; task?: Task; error?: string };
      if (!response.ok || !body.ok || !body.task) throw new Error(body.error || "Не вдалося оновити задачу");
      setTasks((current) => current.map((task) => task.id === id ? body.task! : task));
      await load(false);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Не вдалося оновити задачу");
    } finally {
      setBusyId(null);
    }
  }

  async function createTask(event: FormEvent) {
    event.preventDefault();
    if (!title.trim()) return;
    setBusyId("create");
    setError("");
    try {
      const response = await fetch("/api/tasks", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ title: title.trim(), priority, dueAt: dueAt ? new Date(dueAt).toISOString() : null }),
      });
      const body = await response.json() as { ok?: boolean; task?: Task; error?: string };
      if (!response.ok || !body.ok || !body.task) throw new Error(body.error || "Не вдалося створити задачу");
      setTitle("");
      setDueAt("");
      setPriority("MEDIUM");
      setShowCreate(false);
      await load(false);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Не вдалося створити задачу");
    } finally {
      setBusyId(null);
    }
  }

  async function resolveSignal(signal: AttentionSignal, action: "RESOLVE" | "SPAM" | "NO_SHOW" | "CANCEL") {
    setBusyId(signal.id);
    setError("");
    try {
      const response = await fetch("/api/attention/action", {
        method: "POST",
        headers: { "content-type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ action, sourceType: signal.sourceType, sourceId: signal.sourceId, taskId: signal.taskId }),
      });
      const body = await response.json() as { ok?: boolean; error?: string };
      if (!response.ok || !body.ok) throw new Error(body.error || "Не вдалося виконати рішення");
      setDecisionSignal(null);
      await load(false);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Не вдалося виконати рішення");
    } finally {
      setBusyId(null);
    }
  }

  const setKpiFilter = (filter: ViewFilter) => {
    setViewFilter((current) => current === filter ? "ALL" : filter);
  };

  const renderSignal = (signal: AttentionSignal) => {
    const taskStatus = typeof signal.metadata.status === "string" ? signal.metadata.status : "";
    const money = formatMoney(signal.amount, signal.currency);
    const isMissedCall = isMissedCallSignal(signal);
    const rowClass = styles.signalRow + " " + (styles["level" + signal.level] || "");

    if (isMissedCall) {
      return <article className={rowClass + " " + styles.compactSignalRow} key={signal.id}>
        <div className={styles.signalMarker} aria-hidden="true" />
        <div className={styles.signalBody}>
          <div className={styles.signalTitleLine}>
            <strong>Пропущений дзвінок</strong>
            {signal.level === "CRITICAL" && <span className={styles.criticalBadge}>Критично</span>}
          </div>
          <p className={styles.compactDetails}>
            <span>{formatAttentionPhone(signal)}</span>
            <i aria-hidden="true">•</i>
            <span className={signal.isOverdue ? styles.overdueText : ""}>{compactSignalTime(signal)}</span>
          </p>
          <div className={styles.compactFooter}>
            <span className={styles.compactBucket}>{BUCKET_LABEL[signal.bucket]}</span>
            <div className={styles.signalActions}>
              {signal.action && <button className={styles.contextButton} type="button" onClick={() => openAction(signal.action)}>Опрацювати</button>}
              <button type="button" disabled={busyId === signal.id} onClick={() => setDecisionSignal(signal)}>Рішення</button>
            </div>
          </div>
        </div>
      </article>;
    }

    return <article className={rowClass} key={signal.id}>
      <div className={styles.signalMarker} aria-hidden="true" />
      <div className={styles.signalBody}>
        <div className={styles.signalTitleLine}>
          <strong>{signal.title}</strong>
          <span className={styles.categoryBadge + " " + (styles["category" + signal.category] || "")}>{CATEGORY_LABEL[signal.category]}</span>
          {signal.level === "CRITICAL" && <span className={styles.criticalBadge}>Критично</span>}
        </div>
        <p className={styles.reason}>{signal.reason}</p>
        {signal.description && <p className={styles.description}>{signal.description}</p>}
        <div className={styles.signalMeta}>
          <span className={styles.bucket + " " + (styles["bucket" + signal.bucket] || "")}>{BUCKET_LABEL[signal.bucket]}</span>
          <span className={signal.isOverdue ? styles.overdueText : ""}>{signalTime(signal)}</span>
          {signal.counterparty && <><i>•</i><span>{signal.counterparty}</span></>}
          {money && <><i>•</i><strong className={styles.money}>{money}</strong></>}
          <i>•</i><span>{signal.autoGenerated ? "автоконтроль" : "ручна задача"}</span>
          {Number(signal.metadata.relatedSignalCount || 0) > 1 && <><i>•</i><span>{Number(signal.metadata.relatedSignalCount)} повідомлення об’єднано</span></>}
        </div>
      </div>
      <div className={styles.signalActions}>
        {signal.action && <button className={styles.contextButton} type="button" onClick={() => openAction(signal.action)}>{signal.action.label}</button>}
        {(signal.sourceType === "INQUIRY" || signal.sourceType === "APPOINTMENT" || (signal.taskId && !signal.autoGenerated)) && <button type="button" disabled={busyId === signal.id} onClick={() => setDecisionSignal(signal)}>Рішення</button>}
        {!signal.autoGenerated && signal.taskId && taskStatus === "OPEN" && <button type="button" disabled={busyId === signal.taskId} onClick={() => void patchTask(signal.taskId!, "IN_PROGRESS")}>В роботу</button>}
        {!signal.autoGenerated && signal.taskId && <button type="button" disabled={busyId === signal.taskId} onClick={() => void patchTask(signal.taskId!, "DONE")}>Виконано</button>}
      </div>
    </article>;
  };

  const renderPostLoad = (label: string, period: PostLoadPeriod | null) => {
    if (!period) return <div className={styles.loadEmpty}>{label}: немає доступних даних.</div>;
    return <div className={styles.loadPeriod}>
      <div className={styles.loadHeading}>
        <div><span>{label}</span><strong>{period.utilizationPct}%</strong></div>
        <small>{loadState(period)}</small>
      </div>
      <div className={styles.loadTrack}><span style={{ width: `${Math.min(100, Math.max(0, period.utilizationPct))}%` }} /></div>
      <p>{period.bookedHours} / {period.capacityHours} пост-год · {period.activePosts} постів</p>
      <div className={styles.postMiniList}>
        {period.posts.slice(0, 4).map((post) => <div key={post.id}>
          <span>{post.name}</span><strong className={post.utilizationPct > 100 ? styles.overdueText : ""}>{post.utilizationPct}%</strong>
        </div>)}
      </div>
      <button type="button" onClick={() => navigateCrm("Планувальник", { date: period.date })}>Відкрити планувальник</button>
    </div>;
  };

  return <div className={styles.page}>
    <header className={styles.header}>
      <div>
        <p className={styles.eyebrow}>ОПЕРАЦІЙНИЙ КОНТРОЛЬ</p>
        <h1>Центр уваги</h1>
        <p>Єдина черга всього, що прострочено, зависло, відхилилося від норми або потребує рішення.</p>
      </div>
      <div className={styles.headerActions}>
        <div className={styles.headerTools}>
          <button className={viewFilter === "ARCHIVE" ? styles.archiveActive : styles.archiveButton} type="button" onClick={() => setViewFilter((current) => current === "ARCHIVE" ? "ALL" : "ARCHIVE")}>Архів ({archivedTasks.length})</button>
          <span className={styles.refreshState}>{refreshing ? "Оновлюю…" : `Сигналів: ${attention.summary.total}`}</span>
        </div>
        <button className={styles.primary} type="button" onClick={() => setShowCreate((value) => !value)}>+ Створити задачу</button>
      </div>
    </header>

    {error && <div className={styles.error}>{error}</div>}
    {showCreate && <form className={styles.createForm} onSubmit={createTask}>
      <input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Що потрібно зробити?" autoFocus />
      <select value={priority} onChange={(event) => setPriority(event.target.value)}>
        <option value="LOW">Низький</option>
        <option value="MEDIUM">Середній</option>
        <option value="HIGH">Високий</option>
        <option value="CRITICAL">Критичний</option>
      </select>
      <input type="datetime-local" value={dueAt} onChange={(event) => setDueAt(event.target.value)} />
      <button className={styles.primary} disabled={busyId === "create"}>Зберегти</button>
    </form>}

    <section className={styles.kpis} aria-label="Фільтри центру уваги">
      <button className={viewFilter === "CRITICAL" ? styles.kpiActive : ""} type="button" onClick={() => setKpiFilter("CRITICAL")}>
        <span>Критично</span><strong className={attention.summary.critical ? styles.criticalText : ""}>{attention.summary.critical}</strong><small>потрібне втручання</small>
      </button>
      <button className={viewFilter === "OVERDUE" ? styles.kpiActive : ""} type="button" onClick={() => setKpiFilter("OVERDUE")}>
        <span>Прострочено</span><strong className={attention.summary.overdue ? styles.overdueText : ""}>{attention.summary.overdue}</strong><small>вийшло за дедлайн</small>
      </button>
      <button className={viewFilter === "ACTION" ? styles.kpiActive : ""} type="button" onClick={() => setKpiFilter("ACTION")}>
        <span>Моя дія</span><strong>{attention.summary.action}</strong><small>можна вирішити зараз</small>
      </button>
      <button className={viewFilter === "WAITING" ? styles.kpiActive : ""} type="button" onClick={() => setKpiFilter("WAITING")}>
        <span>Очікуємо</span><strong>{attention.summary.waiting}</strong><small>клієнта або партнера</small>
      </button>
      <button className={viewFilter === "TODAY" ? styles.kpiActive : ""} type="button" onClick={() => setKpiFilter("TODAY")}>
        <span>Сьогодні</span><strong>{attention.summary.today}</strong><small>контроль до кінця дня</small>
      </button>
    </section>

    <section className={styles.categoryBar} aria-label="Напрямки контролю">
      <button className={categoryFilter === "ALL" ? styles.categoryActive : ""} type="button" onClick={() => setCategoryFilter("ALL")}>Усе <b>{attention.summary.total}</b></button>
      {visibleCategories.map((category) => <button className={categoryFilter === category ? styles.categoryActive : ""} type="button" key={category} onClick={() => setCategoryFilter(category)}>
        {CATEGORY_LABEL[category]} <b>{attention.categories[category]}</b>
      </button>)}
    </section>

    {loading ? <div className={styles.loading}>Збираємо всі сигнали CRM…</div> : viewFilter === "ARCHIVE" ? <section className={styles.panel}>
      <div className={styles.panelHead}><div><h2>Архів рішень</h2><p>Завершені або скасовані задачі зберігаються для історії.</p></div><span>{archivedTasks.length}</span></div>
      {archivedTasks.length ? <div className={styles.archiveList}>{archivedTasks.map((task) => <article className={styles.archiveRow} key={task.id}><div><strong>{task.title}</strong>{task.description && <p>{task.description}</p>}<small>{task.status === "DONE" ? "Виконано" : "Скасовано"} · {formatDateTime(task.dueAt)}</small></div><span>{task.priority}</span></article>)}</div> : <div className={styles.empty}><strong>Архів поки порожній.</strong><span>Після рішення повідомлення залишатимуться тут як історія.</span></div>}
    </section> : <div className={styles.grid}>
      <main className={styles.mainColumn}>
        <section className={styles.panel}>
          <div className={styles.panelHead}>
            <div><h2>Потребує уваги зараз</h2><p>Сигнали з клієнтів, СТО, запчастин, постачальників, фінансів і персоналу.</p></div>
            <span>{filteredSignals.length}</span>
          </div>
          {filteredSignals.length
            ? <div className={styles.signalList}>{filteredSignals.map(renderSignal)}</div>
            : <div className={styles.empty}><strong>За цим фільтром проблем немає.</strong><span>Система продовжує контролювати бізнес-процеси автоматично.</span></div>}
        </section>
      </main>

      <aside className={styles.sideColumn}>
        <section className={styles.panel}>
          <div className={styles.panelHead}><div><h2>Завантаженість постів</h2><p>Поточна виробнича потужність.</p></div></div>
          <div className={styles.loadBox}>
            {renderPostLoad("Сьогодні", attention.postLoad.today)}
            {renderPostLoad("Завтра", attention.postLoad.tomorrow)}
          </div>
        </section>

        <section className={styles.panel}>
          <div className={styles.panelHead}><div><h2>Наступні</h2><p>Що найближчим часом стане критичним.</p></div><span>{upcoming.length}</span></div>
          {upcoming.length ? <div className={styles.upcomingList}>{upcoming.map((signal) => <button className={styles.upcoming} key={signal.id} type="button" disabled={!signal.action} onClick={() => openAction(signal.action)}>
            <span><strong>{signal.title}</strong><small>{CATEGORY_LABEL[signal.category]}</small></span>
            <em>{formatDateTime(signal.dueAt)}</em>
          </button>)}</div> : <div className={styles.emptySmall}>Найближчих дедлайнів немає.</div>}
        </section>
      </aside>
    </div>}
    {decisionSignal && <div className={styles.modalBackdrop} role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) setDecisionSignal(null); }}>
      <section className={styles.decisionModal} role="dialog" aria-modal="true" aria-labelledby="attention-decision-title">
        <div className={styles.modalHead}><div><p className={styles.eyebrow}>РІШЕННЯ ПО СИГНАЛУ</p><h2 id="attention-decision-title">{decisionSignal.title}</h2></div><button type="button" onClick={() => setDecisionSignal(null)} aria-label="Закрити">×</button></div>
        <p className={styles.modalText}>Оберіть фактичну дію. Після зміни першоджерела повідомлення зникне з активного центру уваги, але залишиться в історії.</p>
        <div className={styles.decisionOptions}>
          {decisionSignal.sourceType === "INQUIRY" && <><button type="button" disabled={busyId === decisionSignal.id} onClick={() => void resolveSignal(decisionSignal, "RESOLVE")}>Контакт опрацьовано</button><button type="button" disabled={busyId === decisionSignal.id} onClick={() => void resolveSignal(decisionSignal, "SPAM")}>Спам / помилкове звернення</button></>}
          {decisionSignal.sourceType === "APPOINTMENT" && <><button type="button" disabled={busyId === decisionSignal.id} onClick={() => void resolveSignal(decisionSignal, "NO_SHOW")}>Клієнт не приїхав</button><button type="button" disabled={busyId === decisionSignal.id} onClick={() => void resolveSignal(decisionSignal, "CANCEL")}>Скасувати запис</button></>}
          {decisionSignal.taskId && decisionSignal.sourceType !== "INQUIRY" && decisionSignal.sourceType !== "APPOINTMENT" && <button type="button" disabled={busyId === decisionSignal.id} onClick={() => void resolveSignal(decisionSignal, "RESOLVE")}>Позначити виконаним</button>}
        </div>
      </section>
    </div>}
  </div>;
}
