"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { CrmSectionLabel } from "./crm-navigation";
import { navigateCrm, type CrmRouteParams } from "./crm-route";
import styles from "./my-tasks.module.css";

type TaskMetadata = Record<string, unknown>;

type Task = {
  id: string;
  title: string;
  description: string | null;
  status: "OPEN" | "IN_PROGRESS" | "DONE" | "CANCELLED" | string;
  priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | string;
  dueAt: string | null;
  completedAt: string | null;
  sourceType: string;
  sourceId: string | null;
  clientId: string | null;
  vehicleId: string | null;
  metadata: TaskMetadata | null;
  autoGenerated: boolean;
  createdAt: string;
};

type Payload = { ok?: boolean; tasks?: Task[]; error?: string };
type TaskContext = { section: CrmSectionLabel; params?: CrmRouteParams };

const priorityLabel: Record<string, string> = { LOW: "Низький", MEDIUM: "Середній", HIGH: "Високий", CRITICAL: "Критичний" };
const sourceLabel: Record<string, string> = {
  MANUAL: "Ручна задача", INQUIRY: "Звернення", LEAD: "Лід", APPOINTMENT: "Запис", DIAGNOSTIC: "Діагностика",
  ESTIMATE: "Кошторис", WORK_ORDER: "Замовлення-наряд", PARTS_REQUEST: "Запчастини", PAYMENT: "Оплата", QC: "Контроль якості", WARRANTY: "Гарантія",
};

function isOpen(task: Task) { return task.status === "OPEN" || task.status === "IN_PROGRESS"; }
function dayKey(value: Date) { return `${value.getFullYear()}-${value.getMonth()}-${value.getDate()}`; }
function sameDay(a: Date, b: Date) { return dayKey(a) === dayKey(b); }
function safeDate(value: string | null) { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
function dueLabel(value: string | null) {
  const date = safeDate(value);
  if (!date) return "Без дедлайну";
  return new Intl.DateTimeFormat("uk-UA", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(date);
}
function navigate(section: CrmSectionLabel) { window.dispatchEvent(new CustomEvent("turbolev:navigate", { detail: section })); }
function metadataText(task: Task, key: string) {
  const value = task.metadata?.[key];
  return typeof value === "string" && value.trim() ? value.trim() : null;
}
function workOrderContext(task: Task, fallbackTab: string): TaskContext | null {
  const workOrderId = metadataText(task, "workOrderId") || (task.sourceType === "WORK_ORDER" ? task.sourceId : null);
  if (!workOrderId) return null;
  return {
    section: "Замовлення-наряди",
    params: {
      workOrderId,
      workOrderTab: metadataText(task, "workOrderTab") || fallbackTab,
    },
  };
}
function taskContext(task: Task): TaskContext | null {
  if (task.sourceType === "INQUIRY") return { section: "Нові звернення" };
  if (task.sourceType === "LEAD") return { section: "Ліди" };
  if (task.sourceType === "APPOINTMENT") return { section: "Планувальник", params: task.sourceId ? { appointmentId: task.sourceId } : {} };
  if (task.sourceType === "DIAGNOSTIC") return workOrderContext(task, "diagnostic") || { section: "Діагностика", params: task.vehicleId ? { vehicleId: task.vehicleId } : {} };
  if (task.sourceType === "ESTIMATE") return workOrderContext(task, "estimate") || { section: "Замовлення-наряди" };
  if (task.sourceType === "WORK_ORDER") return workOrderContext(task, "overview") || { section: "Замовлення-наряди" };
  if (task.sourceType === "PARTS_REQUEST") return workOrderContext(task, "parts") || { section: "Підбір запчастин", params: task.vehicleId ? { vehicleId: task.vehicleId } : {} };
  if (task.sourceType === "PAYMENT") return workOrderContext(task, "payment") || { section: "Оплати" };
  if (task.sourceType === "QC") return workOrderContext(task, "qc") || { section: "Замовлення-наряди", params: { scope: "qc" } };
  if (task.sourceType === "WARRANTY") return workOrderContext(task, "history") || { section: "Гарантії" };
  return null;
}
function openTaskContext(task: Task) {
  const target = taskContext(task);
  if (!target) return;
  navigateCrm(target.section, target.params || {});
}

export function MyTasks() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [title, setTitle] = useState("");
  const [dueAt, setDueAt] = useState("");
  const [priority, setPriority] = useState("MEDIUM");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch("/api/tasks", { cache: "no-store" });
      const body = await response.json() as Payload;
      if (!response.ok || !body.ok) throw new Error(body.error || "Не вдалося завантажити задачі");
      setTasks(body.tasks || []);
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Не вдалося завантажити задачі");
    } finally { setLoading(false); }
  }, []);

  useEffect(() => { void load(); }, [load]);

  const stats = useMemo(() => {
    const now = new Date();
    const open = tasks.filter(isOpen);
    const today = open.filter((task) => { const due = safeDate(task.dueAt); return due ? sameDay(due, now) : false; });
    const overdue = open.filter((task) => { const due = safeDate(task.dueAt); return Boolean(due && due.getTime() < now.getTime() && !sameDay(due, now)); });
    const weekAgo = new Date(now.getTime() - 7 * 86400000);
    const completedWeek = tasks.filter((task) => task.status === "DONE" && safeDate(task.completedAt) && safeDate(task.completedAt)!.getTime() >= weekAgo.getTime());
    const recent = tasks.filter((task) => new Date(task.createdAt).getTime() >= weekAgo.getTime());
    const completion = recent.length ? Math.round((completedWeek.length / recent.length) * 100) : 100;
    return { open, today, overdue, completedWeek, completion };
  }, [tasks]);

  const upcoming = useMemo(() => {
    const now = new Date();
    return stats.open.filter((task) => { const due = safeDate(task.dueAt); return !due || (due.getTime() >= now.getTime() && !sameDay(due, now)); }).slice(0, 12);
  }, [stats.open]);

  async function patchTask(id: string, status: string) {
    setBusyId(id); setError("");
    try {
      const response = await fetch(`/api/tasks/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) });
      const body = await response.json() as { ok?: boolean; task?: Task; error?: string };
      if (!response.ok || !body.ok || !body.task) throw new Error(body.error || "Не вдалося оновити задачу");
      setTasks((current) => current.map((task) => task.id === id ? body.task! : task));
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Не вдалося оновити задачу"); }
    finally { setBusyId(null); }
  }

  async function createTask(event: FormEvent) {
    event.preventDefault(); if (!title.trim()) return;
    setBusyId("create"); setError("");
    try {
      const response = await fetch("/api/tasks", {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ title: title.trim(), priority, dueAt: dueAt ? new Date(dueAt).toISOString() : null }),
      });
      const body = await response.json() as { ok?: boolean; task?: Task; error?: string };
      if (!response.ok || !body.ok || !body.task) throw new Error(body.error || "Не вдалося створити задачу");
      setTasks((current) => [body.task!, ...current]); setTitle(""); setDueAt(""); setPriority("MEDIUM"); setShowCreate(false);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Не вдалося створити задачу"); }
    finally { setBusyId(null); }
  }

  const renderTask = (task: Task, overdue = false) => {
    const target = taskContext(task);
    return <article className={`${styles.taskRow} ${overdue ? styles.taskOverdue : ""}`} key={task.id}>
      <button className={styles.check} type="button" aria-label="Виконати задачу" disabled={busyId === task.id} onClick={() => void patchTask(task.id, "DONE")}>✓</button>
      <div className={styles.taskBody}>
        <div className={styles.taskTitleLine}><strong>{task.title}</strong><span className={`${styles.priority} ${styles[`priority${task.priority}`] || ""}`}>{priorityLabel[task.priority] || task.priority}</span></div>
        <div className={styles.taskMeta}><span>{sourceLabel[task.sourceType] || task.sourceType}</span><span>•</span><span className={overdue ? styles.dangerText : ""}>{dueLabel(task.dueAt)}</span>{task.autoGenerated && <><span>•</span><span>автоматично</span></>}</div>
        {task.description && <p>{task.description}</p>}
      </div>
      <div className={styles.taskActions}>
        {task.status === "OPEN" && <button type="button" onClick={() => void patchTask(task.id, "IN_PROGRESS")}>В роботу</button>}
        {target && <button type="button" onClick={() => openTaskContext(task)}>Відкрити контекст</button>}
      </div>
    </article>;
  };

  return <div className={styles.page}>
    <header className={styles.header}>
      <div><p className={styles.eyebrow}>РОБОЧИЙ СТІЛ</p><h1>Мої задачі</h1><p>Особиста черга дій із лідів, звернень та сервісних процесів.</p></div>
      <button className={styles.primary} type="button" onClick={() => setShowCreate((value) => !value)}>+ Створити задачу</button>
    </header>

    {error && <div className={styles.error}>{error}</div>}
    {showCreate && <form className={styles.createForm} onSubmit={createTask}>
      <input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Що потрібно зробити?" autoFocus />
      <select value={priority} onChange={(event) => setPriority(event.target.value)}><option value="LOW">Низький</option><option value="MEDIUM">Середній</option><option value="HIGH">Високий</option><option value="CRITICAL">Критичний</option></select>
      <input type="datetime-local" value={dueAt} onChange={(event) => setDueAt(event.target.value)} />
      <button className={styles.primary} disabled={busyId === "create"}>Зберегти</button>
    </form>}

    <section className={styles.kpis}>
      <div><span>Всього задач</span><strong>{stats.open.length}</strong><small>відкритих</small></div>
      <div><span>Сьогодні</span><strong>{stats.today.length}</strong><small>до кінця дня</small></div>
      <div><span>Прострочено</span><strong className={stats.overdue.length ? styles.dangerText : ""}>{stats.overdue.length}</strong><small>потребують уваги</small></div>
      <div><span>Завершено</span><strong>{stats.completedWeek.length}</strong><small>за 7 днів</small></div>
      <div><span>Виконання</span><strong>{Math.min(100, stats.completion)}%</strong><small>за тиждень</small></div>
    </section>

    {loading ? <div className={styles.loading}>Завантажуємо задачі…</div> : <div className={styles.grid}>
      <main className={styles.mainColumn}>
        <section className={styles.panel}><div className={styles.panelHead}><h2>Задачі на сьогодні</h2><span>{stats.today.length}</span></div>{stats.today.length ? stats.today.map((task) => renderTask(task)) : <div className={styles.empty}>На сьогодні задач немає.</div>}</section>
        <section className={styles.panel}><div className={styles.panelHead}><h2>Прострочені задачі</h2><span className={styles.dangerText}>{stats.overdue.length}</span></div>{stats.overdue.length ? stats.overdue.map((task) => renderTask(task, true)) : <div className={styles.empty}>Прострочених задач немає.</div>}</section>
      </main>
      <aside className={styles.sideColumn}>
        <section className={styles.panel}><div className={styles.panelHead}><h2>Наступні</h2><span>{upcoming.length}</span></div>{upcoming.length ? upcoming.map((task) => <button className={styles.upcoming} key={task.id} type="button" onClick={() => openTaskContext(task)}><strong>{task.title}</strong><span>{dueLabel(task.dueAt)}</span></button>) : <div className={styles.empty}>Черга вільна.</div>}</section>
        <section className={styles.panel}><div className={styles.panelHead}><h2>Швидкі дії</h2></div><div className={styles.quick}><button onClick={() => navigate("Нові звернення")}>Нові звернення</button><button onClick={() => navigate("Ліди")}>Ліди</button><button onClick={() => navigate("Комунікації")}>Комунікації</button><button onClick={() => navigate("Планувальник")}>Запис на СТО</button></div></section>
      </aside>
    </div>}
  </div>;
}
