"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  classifyVehicle,
  inferEngineVolume,
  TURBO_LEV_CLASS_COEFFICIENTS,
  TURBO_LEV_CLASS_LABELS,
  type TurboLevClass,
  type VehicleType,
} from "@/src/domain/vehicle-intelligence";

type LookupState = "idle" | "searching" | "found" | "not-found" | "unavailable";
type VehicleDataStatus = "UNKNOWN" | "AUTO" | "MANUAL" | "CONFIRMED";
type RequestForm = {
  customerName:string; phone:string; source:string; responsible:string;
  plate:string; vin:string; make:string; model:string; year:string; mileage:string;
  engine:string; engineVolume:string; fuelType:string; bodyType:string; grossWeight:string; driveType:string;
  vehicleType:VehicleType; turboLevClass:TurboLevClass; priceCoefficient:string;
  classificationSource:string; classificationConfidence:string; classificationReason:string; manualClassOverride:boolean;
  vehicleDataSource:string; vehicleDataConfidence:string; vehicleDataStatus:VehicleDataStatus;
  category:string; complaint:string; urgency:string; appointmentDate:string; appointmentTime:string; preliminaryAmount:string; comment:string;
};
type VehicleCandidate = Partial<RequestForm> & { id?:string|null; clientId?:string|null; clientName?:string|null; clientPhone?:string|null };
type ClientVehicle = { id:string; plateNumber?:string|null; vin?:string|null; brand?:string|null; model?:string|null; year?:number|null; mileageKm?:number|null; engineName?:string|null; engineVolumeCm3?:number|null; fuelType?:string|null; bodyType?:string|null; grossWeightKg?:number|null; driveType?:string|null; vehicleType?:string|null; turboLevClass?:string|null; priceCoefficient?:number|string|null; classificationSource?:string|null; classificationConfidence?:number|null; manualClassOverride?:boolean|null; vehicleDataSource?:string|null; vehicleDataConfidence?:number|null };
type ClientLookup = { id:string; name?:string|null; phone:string; vehicles:ClientVehicle[] };
type MakeOption = { id:number|null; name:string };
type ModelOption = { id:number|null; name:string; makeName:string };
type OpenRequestDetail = { name?:string; phone?:string; source?:string; responsible?:string; plate?:string; vin?:string; appointmentDate?:string; appointmentTime?:string; inquiryId?:string };
type UserOption = { id:string; name:string };
type VinApiResponse = { status:"FOUND"|"NOT_FOUND"|"INVALID_VIN"|"LOOKUP_UNAVAILABLE"; source?:string; sourceDetail?:string; confidence?:number; warning?:string|null; message?:string; vehicle?:{ make?:string|null; model?:string|null; year?:number|null; trim?:string|null; series?:string|null; bodyType?:string|null; vehicleType?:string|null; engine?:string|null; engineVolumeL?:number|null; fuelType?:string|null; secondaryFuelType?:string|null; driveType?:string|null; transmission?:string|null }|null };

type Props = { showButton?:boolean };

const STORAGE_KEY="turbolev-manual-requests-v1";
const MANAGER_KEY="turbolev-current-manager";
const categories=["Ходова","Гальма","Двигун","Електрика","ТО / мастило","Комп. діагностика","Кондиціонер","Інше"];
const sources=["Інше","Телефон","Binotel","Instagram","Facebook","TikTok","OLX","Сайт","Google Maps","Viber","WhatsApp","Рекомендація","Заїхав без запису"];
const years=Array.from({length:new Date().getFullYear()-1979+2},(_,i)=>String(new Date().getFullYear()+1-i));
const initialForm:RequestForm={
  customerName:"",phone:"",source:"Інше",responsible:"",plate:"",vin:"",make:"",model:"",year:"",mileage:"",engine:"",engineVolume:"",fuelType:"",bodyType:"",grossWeight:"",driveType:"",
  vehicleType:"UNKNOWN",turboLevClass:"UNKNOWN",priceCoefficient:"1.00",classificationSource:"UNKNOWN",classificationConfidence:"0",classificationReason:"Очікуємо дані автомобіля",manualClassOverride:false,
  vehicleDataSource:"UNKNOWN",vehicleDataConfidence:"0",vehicleDataStatus:"UNKNOWN",category:"",complaint:"",urgency:"Звичайна",appointmentDate:"",appointmentTime:"",preliminaryAmount:"",comment:"",
};
const vehicleTypeLabels:Record<VehicleType,string>={PASSENGER:"Легковий",CROSSOVER:"Кросовер",SUV:"Позашляховик / SUV",MINIVAN:"Мінівен / MPV",VAN_SMALL:"Малий бус",VAN:"Бус",VAN_LARGE:"Великий бус",COMMERCIAL_HEAVY:"Великий комерційний",UNKNOWN:"Не визначено"};

function normalizePlate(value:string){return value.toUpperCase().replace(/[^A-ZА-ЯІЇЄ0-9]/g,"").slice(0,10)}
function normalizeVin(value:string){return value.toUpperCase().replace(/[^A-HJ-NPR-Z0-9]/g,"").slice(0,17)}
function normalizePhone(value:string){const digits=value.replace(/\D/g,"");if(digits.startsWith("380"))return digits.slice(0,12);if(digits.startsWith("0"))return `38${digits}`.slice(0,12);if(digits.length<=9)return `380${digits}`.slice(0,12);return digits.slice(0,12)}
function formatPhone(value:string){const digits=normalizePhone(value);if(!digits)return"";const local=digits.startsWith("380")?digits.slice(3,12):digits;return `+380 ${local.slice(0,2)} ${local.slice(2,5)} ${local.slice(5,7)} ${local.slice(7,9)}`.trim()}
function sourceLabel(source:string){if(source.includes("NHTSA")||source.includes("VPIC"))return"VIN Decoder · NHTSA vPIC";if(source.includes("MVS"))return"Реєстр МВС";if(source==="MANUAL")return"Введено вручну";if(source==="CRM")return"База Turbo LEV";return source||"Джерело не визначено"}
function classificationPatch(input:Partial<RequestForm>){const result=classifyVehicle({make:input.make,model:input.model,year:input.year,engine:input.engine,engineVolume:input.engineVolume||inferEngineVolume(input.engine),fuelType:input.fuelType,bodyType:input.bodyType,grossWeight:input.grossWeight,driveType:input.driveType,vehicleType:input.vehicleType});return{vehicleType:result.vehicleType,turboLevClass:result.turboLevClass,priceCoefficient:result.priceCoefficient.toFixed(2),classificationSource:result.source,classificationConfidence:String(result.confidence),classificationReason:result.reason}}
function candidateFromClientVehicle(v:ClientVehicle):VehicleCandidate{return{id:v.id,plate:v.plateNumber||"",vin:v.vin||"",make:v.brand||"",model:v.model||"",year:v.year?String(v.year):"",mileage:v.mileageKm?String(v.mileageKm):"",engine:v.engineName||"",engineVolume:v.engineVolumeCm3?String(v.engineVolumeCm3/1000):"",fuelType:v.fuelType||"",bodyType:v.bodyType||"",grossWeight:v.grossWeightKg?String(v.grossWeightKg):"",driveType:v.driveType||"",vehicleType:(v.vehicleType as VehicleType)||"UNKNOWN",turboLevClass:(v.turboLevClass as TurboLevClass)||"UNKNOWN",priceCoefficient:v.priceCoefficient?Number(v.priceCoefficient).toFixed(2):"1.00",classificationSource:v.classificationSource||"CRM",classificationConfidence:String(v.classificationConfidence??100),classificationReason:"Дані з карти клієнта",manualClassOverride:Boolean(v.manualClassOverride),vehicleDataSource:v.vehicleDataSource||"CRM",vehicleDataConfidence:String(v.vehicleDataConfidence??100),vehicleDataStatus:"AUTO"}}

export function NewRequestWizardV4({showButton=true}:Props){
  const [open,setOpen]=useState(false);const[step,setStep]=useState(1);const[form,setForm]=useState<RequestForm>(initialForm);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[saving,setSaving]=useState(false);
  const[plateLookupState,setPlateLookupState]=useState<LookupState>("idle");const[phoneLookupState,setPhoneLookupState]=useState<LookupState>("idle");const[vinLookupState,setVinLookupState]=useState<LookupState>("idle");const[vinMessage,setVinMessage]=useState("");
  const[foundClient,setFoundClient]=useState<ClientLookup|null>(null);const[selectedClientId,setSelectedClientId]=useState<string|null>(null);const[foundVehicle,setFoundVehicle]=useState<VehicleCandidate|null>(null);const[vehicleConflict,setVehicleConflict]=useState<VehicleCandidate|null>(null);const[allowReassign,setAllowReassign]=useState(false);
  const[makes,setMakes]=useState<MakeOption[]>([]);const[models,setModels]=useState<ModelOption[]>([]);const[catalogLoading,setCatalogLoading]=useState(false);const[users,setUsers]=useState<UserOption[]>([]);
  const status="BOOKED";
  const canLeaveClient=normalizePhone(form.phone).length===12;

  function update<K extends keyof RequestForm>(field:K,value:RequestForm[K]){setForm(current=>({...current,[field]:value}));setError("")}
  function updatePhone(value:string){update("phone",formatPhone(value));if(phoneLookupState!=="idle"){setPhoneLookupState("idle");setFoundClient(null);setSelectedClientId(null)}}
  function updatePlate(value:string){update("plate",normalizePlate(value));setPlateLookupState("idle");setFoundVehicle(null);setVehicleConflict(null);setAllowReassign(false)}
  function markManual(field:"make"|"model"|"year",value:string){setForm(current=>({...current,[field]:value,vehicleDataSource:"MANUAL",vehicleDataConfidence:"100",vehicleDataStatus:"MANUAL"}));setError("")}
  function applyVehicle(candidate:VehicleCandidate){setFoundVehicle(candidate);setForm(current=>{const merged:RequestForm={...current,plate:normalizePlate(candidate.plate||current.plate),vin:normalizeVin(candidate.vin||current.vin),make:candidate.make||current.make,model:candidate.model||current.model,year:candidate.year?String(candidate.year):current.year,mileage:candidate.mileage?String(candidate.mileage):current.mileage,engine:candidate.engine||current.engine,engineVolume:candidate.engineVolume||inferEngineVolume(candidate.engine)||current.engineVolume,fuelType:candidate.fuelType||current.fuelType,bodyType:candidate.bodyType||current.bodyType,grossWeight:candidate.grossWeight||current.grossWeight,driveType:candidate.driveType||current.driveType,vehicleType:(candidate.vehicleType as VehicleType)||current.vehicleType,turboLevClass:(candidate.turboLevClass as TurboLevClass)||current.turboLevClass,priceCoefficient:candidate.priceCoefficient||current.priceCoefficient,classificationSource:candidate.classificationSource||current.classificationSource,classificationConfidence:candidate.classificationConfidence||current.classificationConfidence,classificationReason:candidate.classificationReason||current.classificationReason,manualClassOverride:Boolean(candidate.manualClassOverride),vehicleDataSource:candidate.vehicleDataSource||current.vehicleDataSource||"CRM",vehicleDataConfidence:candidate.vehicleDataConfidence||current.vehicleDataConfidence||"100",vehicleDataStatus:candidate.vehicleDataStatus||"AUTO"};if(!merged.manualClassOverride)Object.assign(merged,classificationPatch(merged));return merged})}
  function setManualClass(value:TurboLevClass){setForm(current=>({...current,turboLevClass:value,priceCoefficient:TURBO_LEV_CLASS_COEFFICIENTS[value].toFixed(2),manualClassOverride:true,classificationSource:"MANUAL",classificationConfidence:"100",classificationReason:"Клас підтверджено менеджером"}))}

  async function loadUsers(){try{const response=await fetch("/api/users/active",{cache:"no-store"});const data=await response.json();const items=Array.isArray(data.items)?data.items as UserOption[]:[];setUsers(items);setForm(current=>{if(current.responsible)return current;const stored=window.localStorage.getItem(MANAGER_KEY)||"";const resolved=items.some(item=>item.name===stored)?stored:items[0]?.name||"Продавник";return{...current,responsible:resolved}})}catch{setUsers([]);setForm(current=>current.responsible?current:{...current,responsible:"Продавник"})}}
  async function loadMakes(){if(makes.length)return;setCatalogLoading(true);try{const response=await fetch("/api/vehicles/catalog",{cache:"force-cache"});const data=await response.json();setMakes(Array.isArray(data.items)?data.items:[])}catch{setMakes([])}finally{setCatalogLoading(false)}}
  async function loadModels(make:string){const value=make.trim();setModels([]);if(!value)return;setCatalogLoading(true);try{const response=await fetch(`/api/vehicles/catalog?make=${encodeURIComponent(value)}`,{cache:"force-cache"});const data=await response.json();setModels(Array.isArray(data.items)?data.items:[])}catch{setModels([])}finally{setCatalogLoading(false)}}

  function openWith(detail:OpenRequestDetail={}){const stored=typeof window!=="undefined"?window.localStorage.getItem(MANAGER_KEY)||"":"";setForm({...initialForm,customerName:detail.name?.trim()||"",phone:detail.phone?formatPhone(detail.phone):"",source:detail.source?.trim()||"Інше",responsible:detail.responsible?.trim()||stored,plate:detail.plate?normalizePlate(detail.plate):"",vin:detail.vin?normalizeVin(detail.vin):"",appointmentDate:detail.appointmentDate||"",appointmentTime:detail.appointmentTime||""});setStep(1);setError("");setSuccess("");setFoundClient(null);setSelectedClientId(null);setFoundVehicle(null);setVehicleConflict(null);setAllowReassign(false);setPlateLookupState("idle");setPhoneLookupState("idle");setVinLookupState("idle");setVinMessage("");setOpen(true)}
  function close(){setOpen(false);setStep(1);setError("");setSuccess("")}

  useEffect(()=>{void loadUsers()},[]);
  useEffect(()=>{const handler=(event:Event)=>openWith((event as CustomEvent<OpenRequestDetail>).detail||{});window.addEventListener("turbolev:open-new-request",handler as EventListener);return()=>window.removeEventListener("turbolev:open-new-request",handler as EventListener)},[]);
  useEffect(()=>{if(open)void loadMakes()},[open]);

  async function lookupPhone(){const phone=normalizePhone(form.phone);setFoundClient(null);setSelectedClientId(null);if(phone.length!==12){setPhoneLookupState("not-found");return}setPhoneLookupState("searching");try{const response=await fetch(`/api/client-card?phone=${encodeURIComponent(formatPhone(phone))}`,{cache:"no-store"});const data=await response.json();if(!response.ok||!data.client){setPhoneLookupState("not-found");return}setFoundClient(data.client as ClientLookup);setPhoneLookupState("found")}catch{setPhoneLookupState("unavailable")}}
  function useClient(client:ClientLookup){setSelectedClientId(client.id);setForm(current=>({...current,customerName:client.name?.trim()||current.customerName||"Невідомий клієнт",phone:formatPhone(client.phone)}));setError("")}
  function useClientVehicle(vehicle:ClientVehicle){if(foundClient)useClient(foundClient);applyVehicle(candidateFromClientVehicle(vehicle));setPlateLookupState("found")}

  async function lookupPlate(){const plate=normalizePlate(form.plate);if(plate.length<6){setPlateLookupState("not-found");return}setPlateLookupState("searching");setFoundVehicle(null);setVehicleConflict(null);setAllowReassign(false);try{const response=await fetch(`/api/vehicles/lookup?plate=${encodeURIComponent(plate)}`,{cache:"no-store"});const data=await response.json();if(!response.ok||data.status!=="FOUND"||!data.vehicle){setPlateLookupState("not-found");return}const v=data.vehicle;const candidate:VehicleCandidate={id:v.id,clientId:v.clientId,clientName:v.clientName,clientPhone:v.clientPhone,plate,vin:v.vin||"",make:v.make||"",model:v.model||"",year:v.year?String(v.year):"",mileage:v.mileageKm?String(v.mileageKm):"",engine:v.engine||"",engineVolume:v.engineVolumeL?String(v.engineVolumeL):"",fuelType:v.fuelType||"",bodyType:v.bodyType||"",grossWeight:v.grossWeightKg?String(v.grossWeightKg):"",driveType:v.driveType||"",vehicleType:v.vehicleType||"UNKNOWN",turboLevClass:v.turboLevClass||"UNKNOWN",priceCoefficient:Number(v.priceCoefficient||1).toFixed(2),classificationSource:v.classificationSource||"CRM",classificationConfidence:String(v.classificationConfidence??100),classificationReason:v.classificationReason||"Дані автомобіля знайдено",manualClassOverride:Boolean(v.manualClassOverride),vehicleDataSource:v.vehicleDataSource||data.lookupLevel||"CRM",vehicleDataConfidence:String(v.vehicleDataConfidence??100),vehicleDataStatus:"AUTO"};applyVehicle(candidate);setPlateLookupState("found");const currentPhone=normalizePhone(form.phone);const ownerPhone=normalizePhone(String(v.clientPhone||""));if(v.clientId&&((selectedClientId&&v.clientId!==selectedClientId)||(!selectedClientId&&currentPhone&&ownerPhone&&currentPhone!==ownerPhone)))setVehicleConflict(candidate)}catch{setPlateLookupState("unavailable")}}

  async function lookupVin(){const vin=normalizeVin(form.vin);setVinMessage("");if(vin.length!==17){setVinLookupState("not-found");return}setVinLookupState("searching");try{const response=await fetch(`/api/vehicles/vin?vin=${encodeURIComponent(vin)}`,{cache:"no-store"});const data=await response.json() as VinApiResponse;if(!response.ok||data.status!=="FOUND"||!data.vehicle){setVinLookupState("not-found");setVinMessage(data.message||"VIN не знайдено. Дані можна ввести вручну.");return}const v=data.vehicle;applyVehicle({vin,make:v.make||"",model:v.model||"",year:v.year?String(v.year):"",engine:[v.engine,v.trim,v.series].filter(Boolean).join(" · "),engineVolume:v.engineVolumeL?String(v.engineVolumeL):"",fuelType:[v.fuelType,v.secondaryFuelType].filter(Boolean).join(" / "),bodyType:v.bodyType||"",driveType:v.driveType||"",vehicleDataSource:data.sourceDetail||data.source||"NHTSA_VPIC_API",vehicleDataConfidence:String(data.confidence??80),vehicleDataStatus:"AUTO"});setVinLookupState("found");setVinMessage(data.warning||"VIN успішно розшифровано.");if(v.make)void loadModels(v.make)}catch{setVinLookupState("unavailable");setVinMessage("VIN-декодер тимчасово недоступний. Дані можна заповнити вручну.")}}

  function goNext(){if(step===1){if(!canLeaveClient)return setError("Вкажіть коректний номер телефону.");if(!form.customerName.trim())setForm(current=>({...current,customerName:"Невідомий клієнт"}));setStep(2);setError("");return}if(step===2){if(!form.plate.trim()&&!form.vin.trim())return setError("Вкажіть державний номер або VIN автомобіля.");if(form.vin&&normalizeVin(form.vin).length!==17)return setError("VIN має містити 17 символів.");if(!form.make.trim()||!form.model.trim()||!form.year.trim())return setError("Вкажіть марку, модель і рік автомобіля.");if(vehicleConflict&&!allowReassign)return setError("Автомобіль прив’язаний до іншого клієнта. Оберіть поточного власника або підтвердьте ручне переприв’язування.");setStep(3);setError("");return}if(step===3){if(!form.complaint.trim())return setError("Опишіть проблему або потребу клієнта.");setStep(4);setError("")}}

  async function saveRequest(event:FormEvent){event.preventDefault();if(!form.appointmentDate||!form.appointmentTime)return setError("Для створення запису в Планувальнику вкажіть дату та час заїзду.");if(!canLeaveClient)return setError("Вкажіть коректний номер телефону.");if(vehicleConflict&&!allowReassign)return setError("Потрібно підтвердити переприв’язування автомобіля.");setSaving(true);setError("");try{const payload={...form,customerName:form.customerName.trim()||"Невідомий клієнт",phone:formatPhone(form.phone),plate:normalizePlate(form.plate),vin:normalizeVin(form.vin),forceReassignVehicle:allowReassign};const response=await fetch("/api/intake",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Не вдалося створити заявку");const request={...payload,id:`REQ-${Date.now()}`,createdAt:new Date().toISOString(),status:"BOOKED",serverSaved:true,serverResult:{clientId:data.client?.id,vehicleId:data.vehicle?.id,leadId:data.lead?.id,appointmentId:data.appointment?.id}};try{const list=JSON.parse(window.localStorage.getItem(STORAGE_KEY)||"[]");window.localStorage.setItem(STORAGE_KEY,JSON.stringify([request,...(Array.isArray(list)?list:[])]))}catch{}window.dispatchEvent(new CustomEvent("turbolev:new-request",{detail:request}));window.dispatchEvent(new CustomEvent("turbolev:data-changed",{detail:{entity:"intake",...data}}));setSuccess("Заявку створено і додано в Планувальник.");window.setTimeout(()=>close(),1000)}catch(reason){setError(reason instanceof Error?reason.message:"Помилка створення заявки")}finally{setSaving(false)}}

  const phoneButton=phoneLookupState==="searching"?"Шукаю…":phoneLookupState==="found"?"✓ Успішно":phoneLookupState==="not-found"?"Не знайдено":phoneLookupState==="unavailable"?"Недоступно":"Знайти";
  const plateButton=plateLookupState==="searching"?"Шукаю…":plateLookupState==="found"?"✓ Успішно":plateLookupState==="not-found"?"Не знайдено":plateLookupState==="unavailable"?"Недоступно":"Знайти";
  const responsibleOptions=useMemo(()=>{const names=users.map(item=>item.name);if(form.responsible&&!names.includes(form.responsible))names.unshift(form.responsible);return names.length?names:["Продавник","РОП","Завідуючий"]},[users,form.responsible]);

  return <>
    {showButton&&<button className="primary" type="button" onClick={()=>openWith()}>+ Нова заявка</button>}
    {open&&<div className="requestModalBackdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&close()}>
      <form className="requestModal requestModalV4" onSubmit={saveRequest}>
        <div className="requestModalHead"><div><p className="eyebrow">TURBO LEV · НОВА ЗАЯВКА</p><h2>Клієнт + автомобіль</h2><span>Клієнт → автомобіль → проблема → запис у Планувальник</span></div><button className="requestClose" type="button" onClick={close} aria-label="Закрити">×</button></div>
        <div className="requestScroll">
          <div className="requestStepper requestStepperV4">{["Клієнт","Автомобіль","Проблема","Запис"].map((label,index)=>{const n=index+1;const done=n<step;return <button type="button" key={label} className={n===step?"active":done?"done":"locked"} onClick={()=>done&&setStep(n)} aria-disabled={!done&&n!==step}><b>{done?"✓":n}</b><span>{label}</span></button>})}</div>
          <div className="quickLookupGrid quickLookupGridV4">
            <div className="plateQuickLookup"><div className="plateQuickCopy"><b>Пошук по держномеру</b><span>CRM → реєстр МВС → технічний профіль</span></div><div className="plateQuickControls"><input value={form.plate} onChange={e=>updatePlate(e.target.value)} placeholder="AA1234BB"/><button type="button" className={`lookupState-${plateLookupState}`} onClick={()=>void lookupPlate()} disabled={plateLookupState==="searching"}>{plateButton}</button></div></div>
            <div className="phoneQuickLookup"><div className="plateQuickCopy"><b>Клієнт по телефону</b><span>Пошук повторного клієнта та його авто</span></div><div className="plateQuickControls"><input value={form.phone} onChange={e=>updatePhone(e.target.value)} placeholder="0 67 123 45 67" inputMode="tel"/><button type="button" className={`lookupState-${phoneLookupState}`} onClick={()=>void lookupPhone()} disabled={phoneLookupState==="searching"}>{phoneButton}</button></div>{phoneLookupState==="found"&&foundClient&&<div className="clientLookupCompact"><div><b>{foundClient.name||"Невідомий клієнт"}</b><span>{formatPhone(foundClient.phone)} · авто: {foundClient.vehicles?.length||0}</span></div><button type="button" onClick={()=>useClient(foundClient)}>Використати</button>{foundClient.vehicles?.length>0&&<div className="clientVehicleCompactList">{foundClient.vehicles.map(v=><button type="button" key={v.id} onClick={()=>useClientVehicle(v)}><b>{v.plateNumber||"Без номера"}</b><span>{[v.brand,v.model,v.year].filter(Boolean).join(" ")}</span></button>)}</div>}</div>}</div>
          </div>
          <div className="requestBody">
            {step===1&&<section className="requestStep"><div className="requestStepTitle"><div><small>КРОК 1</small><h3>Картка клієнта</h3></div><span className="requestHint">Телефон обов’язковий · ім’я можна уточнити пізніше</span></div><div className="requestGrid two"><label><span>Ім’я клієнта</span><input value={form.customerName} onChange={e=>update("customerName",e.target.value)} placeholder="Невідомий клієнт"/></label><label><span>Телефон *</span><input value={form.phone} onChange={e=>updatePhone(e.target.value)} inputMode="tel"/></label><label><span>Джерело</span><select value={form.source} onChange={e=>update("source",e.target.value)}>{sources.map(item=><option key={item}>{item}</option>)}</select></label><label><span>Відповідальний</span><select value={form.responsible} onChange={e=>{update("responsible",e.target.value);window.localStorage.setItem(MANAGER_KEY,e.target.value)}}>{responsibleOptions.map(item=><option key={item}>{item}</option>)}</select></label></div></section>}
            {step===2&&<section className="requestStep vehicleIdentityStep"><div className="requestStepTitle"><div><small>КРОК 2</small><h3>Ідентифікація автомобіля</h3></div><span className="requestHint">Номер / VIN / ручний каталог</span></div>{vehicleConflict&&<div className={`vehicleOwnerConflict ${allowReassign?"confirmed":""}`}><div><b>Автомобіль уже прив’язаний до іншого клієнта</b><span>{vehicleConflict.clientName||"Інший клієнт"}{vehicleConflict.clientPhone?` · ${formatPhone(vehicleConflict.clientPhone)}`:""}</span></div><div><button type="button" onClick={()=>{setForm(current=>({...current,customerName:vehicleConflict.clientName||"Невідомий клієнт",phone:vehicleConflict.clientPhone?formatPhone(vehicleConflict.clientPhone):current.phone}));setSelectedClientId(vehicleConflict.clientId||null);setVehicleConflict(null);setAllowReassign(false)}}>Використати поточного власника</button><button type="button" className="danger" onClick={()=>setAllowReassign(true)}>{allowReassign?"✓ Переприв’язування підтверджено":"Переприв’язати вручну"}</button></div></div>}
              <div className="requestVehicleMain vehicleIdentityMain"><label className="plateField"><span>Державний номер</span><input value={form.plate} onChange={e=>updatePlate(e.target.value)} placeholder="AA1234BB"/></label><label className="vinField vinLookupField"><span>VIN</span><div className="vinLookupControl"><input value={form.vin} onChange={e=>{update("vin",normalizeVin(e.target.value));setVinLookupState("idle")}} placeholder="17 символів"/><button type="button" disabled={form.vin.length!==17||vinLookupState==="searching"} onClick={()=>void lookupVin()}>{vinLookupState==="searching"?"Шукаю…":vinLookupState==="found"?"✓ VIN знайдено":"Розшифрувати VIN"}</button></div><small>{form.vin?`${form.vin.length}/17`:"VIN можна вводити без держномера"}</small></label></div>
              {vinMessage&&<div className={`vinLookupResult vin-${vinLookupState}`}><div><b>{vinLookupState==="found"?"VIN розшифровано":"VIN"}</b><span>{vinMessage}</span></div></div>}
              <div className="vehicleManualHeader"><div><small>РУЧНИЙ КАТАЛОГ</small><h4>Марка → модель → рік</h4></div><span>{catalogLoading?"Оновлюю довідник…":"Дані з пошуку вже підставляються сюди автоматично"}</span></div>
              <div className="requestGrid three vehicleCatalogGrid"><label><span>Марка *</span><input list="turboLevMakesV4" value={form.make} onFocus={()=>void loadMakes()} onChange={e=>{markManual("make",e.target.value);update("model","");void loadModels(e.target.value)}} placeholder="Напр. Volvo"/><datalist id="turboLevMakesV4">{makes.map(item=><option key={`${item.id}-${item.name}`} value={item.name}/>)}</datalist></label><label><span>Модель *</span><input list="turboLevModelsV4" value={form.model} onFocus={()=>form.make&&void loadModels(form.make)} onChange={e=>markManual("model",e.target.value)} disabled={!form.make.trim()} placeholder="Модель"/><datalist id="turboLevModelsV4">{models.map(item=><option key={`${item.id}-${item.name}`} value={item.name}/>)}</datalist></label><label><span>Рік *</span><select value={form.year} onChange={e=>markManual("year",e.target.value)}><option value="">Оберіть рік</option>{years.map(year=><option key={year}>{year}</option>)}</select></label><label><span>Двигун / модифікація</span><input value={form.engine} onChange={e=>update("engine",e.target.value)}/></label><label><span>Об’єм двигуна, л</span><input value={form.engineVolume} onChange={e=>update("engineVolume",e.target.value.replace(/[^0-9.,]/g,""))}/></label><label><span>Паливо</span><input value={form.fuelType} onChange={e=>update("fuelType",e.target.value)}/></label><label><span>Тип кузова</span><input value={form.bodyType} onChange={e=>update("bodyType",e.target.value)}/></label><label><span>Повна маса, кг</span><input value={form.grossWeight} onChange={e=>update("grossWeight",e.target.value.replace(/\D/g,""))}/></label><label><span>Привід</span><input value={form.driveType} onChange={e=>update("driveType",e.target.value)}/></label><label><span>Пробіг, км</span><input value={form.mileage} onChange={e=>update("mileage",e.target.value.replace(/\D/g,""))}/></label><label><span>Тип ТЗ</span><select value={form.vehicleType} onChange={e=>update("vehicleType",e.target.value as VehicleType)}>{Object.entries(vehicleTypeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
              <div className="vehicleDataTrust"><div><small>ДАНІ АВТОМОБІЛЯ</small><strong>{form.vehicleDataStatus}</strong><span>{sourceLabel(form.vehicleDataSource)}</span></div><div><small>Довіра</small><b>{form.vehicleDataConfidence}%</b><button type="button" onClick={()=>setForm(current=>({...current,vehicleDataStatus:"CONFIRMED",vehicleDataConfidence:"100"}))}>Підтвердити менеджером</button></div></div>
              <div className="vehicleIntelligenceCard"><div><small>КЛАС TURBO LEV</small><strong>{TURBO_LEV_CLASS_LABELS[form.turboLevClass]}</strong><span>{form.classificationReason}</span></div><div className="vehicleCoefficient"><small>Коефіцієнт прайсу</small><b>×{form.priceCoefficient}</b><span>Впевненість {form.classificationConfidence}%</span></div><label><span>Змінити вручну</span><select value={form.turboLevClass} onChange={e=>setManualClass(e.target.value as TurboLevClass)}>{Object.entries(TURBO_LEV_CLASS_LABELS).map(([value,label])=><option key={value} value={value}>{value} — {label}</option>)}</select></label></div>
            </section>}
            {step===3&&<section className="requestStep"><div className="requestStepTitle"><div><small>КРОК 3</small><h3>Що турбує клієнта</h3></div></div><label className="requestFullField"><span>Категорія звернення</span><input value={form.category} onChange={e=>update("category",e.target.value)}/></label><div className="requestTags">{categories.map(item=><button type="button" key={item} className={form.category===item?"selected":""} onClick={()=>update("category",item)}>{item}</button>)}</div><label className="requestFullField"><span>Проблема / побажання клієнта *</span><textarea value={form.complaint} onChange={e=>update("complaint",e.target.value)}/></label><div className="requestGrid two compactTop"><label><span>Пріоритет</span><select value={form.urgency} onChange={e=>update("urgency",e.target.value)}><option>Звичайна</option><option>Терміново</option><option>Авто не на ходу</option></select></label><label><span>Внутрішній коментар</span><input value={form.comment} onChange={e=>update("comment",e.target.value)}/></label></div></section>}
            {step===4&&<section className="requestStep"><div className="requestStepTitle"><div><small>КРОК 4</small><h3>Запис і підтвердження</h3></div><span className="requestStatus booked">Записаний</span></div><div className="requestGrid three"><label><span>Дата заїзду *</span><input type="date" value={form.appointmentDate} onChange={e=>update("appointmentDate",e.target.value)}/></label><label><span>Час *</span><input type="time" value={form.appointmentTime} onChange={e=>update("appointmentTime",e.target.value)}/></label><label><span>Попередня сума, грн</span><input value={form.preliminaryAmount} onChange={e=>update("preliminaryAmount",e.target.value.replace(/[^0-9.,]/g,""))}/></label></div><div className="requestSummary"><article><small>Клієнт</small><strong>{form.customerName||"Невідомий клієнт"}</strong><span>{form.phone}</span></article><article><small>Автомобіль</small><strong>{[form.make,form.model,form.year].filter(Boolean).join(" ")||form.plate||form.vin}</strong><span>{form.plate||form.vin}</span></article><article><small>Джерело</small><strong>{form.source}</strong><span>Відповідальний: {form.responsible}</span></article><article><small>Клас / прайс</small><strong>{TURBO_LEV_CLASS_LABELS[form.turboLevClass]}</strong><span>Коефіцієнт ×{form.priceCoefficient}</span></article><article><small>Звернення</small><strong>{form.category||"Без категорії"}</strong><span>{form.complaint}</span></article></div></section>}
            {error&&<div className="requestMessage error">{error}</div>}{success&&<div className="requestMessage success">{success}</div>}
          </div>
        </div>
        <div className="requestActions"><button type="button" className="ghost" onClick={close}>Скасувати</button><div>{step>1&&<button type="button" className="ghost" onClick={()=>{setStep(current=>Math.max(1,current-1));setError("")}}>← Назад</button>}{step<4?<button type="button" className="primary" onClick={goNext}>{step===1&&!canLeaveClient?"Заповніть телефон":"Далі →"}</button>:<button type="submit" className="primary" disabled={saving}>{saving?"Створюю…":"Створити заявку + запис"}</button>}</div></div>
      </form>
    </div>}
  </>;
}
