"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./personnel.module.css";

type EmployeeDoc={id?:string;type:string;name:string;status:string;fileUrl?:string|null};
type CabinetStatus="NOT_OPENED"|"WAITING_ACTIVATION"|"ACTIVE"|"SUSPENDED";
type EmployeeAccess={roleCode:string|null;roleName:string|null;location:{id:string;name:string}|null;cabinetStatus:CabinetStatus;cabinetEnabled:boolean;userId:string|null;authLinked:boolean;lastLoginAt:string|null;mechanicResource:{id:string;name:string;locationId:string;isActive:boolean}|null};
type Employee={id:string;firstName:string;lastName:string;birthDate:string|null;email:string|null;phone:string|null;phoneCountry:string|null;address:string|null;photoUrl:string|null;personnelCategory:string|null;position:string|null;crmLogin:string|null;isActive:boolean;baseSalary:string|number|null;minimumSalary:string|number|null;workPercent:string|number|null;partsSalesPercent:string|number|null;partsMarginPercent:string|number|null;netProfitPercent:string|number|null;payrollRuleNote:string|null;documents:EmployeeDoc[];access?:EmployeeAccess;compensationRestricted?:boolean};
type RoleOption={code:string;name:string;category:string|null;requiresLocation:boolean;accessDescription:string|null};
type LocationOption={id:string;name:string};
type MechanicOption={id:string;name:string;locationId:string};
type AccessCatalog={grantedScope:string|null;managerRoles:string[];roles:RoleOption[];locations:LocationOption[];unlinkedMechanics:MechanicOption[]};
type FormState={id?:string;firstName:string;lastName:string;birthDate:string;email:string;phone:string;phoneCountry:string;address:string;photoUrl:string;personnelCategory:string;position:string;isActive:boolean;baseSalary:string;minimumSalary:string;workPercent:string;partsSalesPercent:string;partsMarginPercent:string;netProfitPercent:string;payrollRuleNote:string;documents:EmployeeDoc[];roleCode:string;locationId:string;cabinetEnabled:boolean;cabinetStatus:CabinetStatus;mechanicResourceId:string};

const categories=["Керівництво","Продажі","Підбір запчастин","Майстри","Автомеханіки","Адміністрація","Маркетинг","Інше"];
const fallbackPositions=["Виконавчий директор","РОП","Продавець","Підборщик","Завідувач станцією","Майстер","Автомеханік","Маркетинг-директор","SMM-маркетолог","Performance-маркетолог","Бухгалтер","HR","IT / Адміністратор"];
const docs=["Паспорт","ІПН","Диплом","Трудова","Резюме","Договір підряду","Договір про найм","Договір МВ"];
const empty:FormState={firstName:"",lastName:"",birthDate:"",email:"",phone:"+380",phoneCountry:"UA",address:"",photoUrl:"",personnelCategory:"",position:"",isActive:true,baseSalary:"",minimumSalary:"",workPercent:"",partsSalesPercent:"",partsMarginPercent:"",netProfitPercent:"",payrollRuleNote:"",documents:docs.map(name=>({type:name.toUpperCase().replaceAll(" ","_"),name,status:"MISSING"})),roleCode:"",locationId:"",cabinetEnabled:false,cabinetStatus:"NOT_OPENED",mechanicResourceId:""};
const cabinetLabels:Record<CabinetStatus,string>={NOT_OPENED:"Кабінет не відкритий",WAITING_ACTIVATION:"Очікує активації",ACTIVE:"Кабінет активний",SUSPENDED:"Доступ призупинений"};
function num(v:string|number|null){return v==null?"":String(v)}
function toForm(e:Employee):FormState{return{id:e.id,firstName:e.firstName,lastName:e.lastName,birthDate:e.birthDate?e.birthDate.slice(0,10):"",email:e.email||"",phone:e.phone||"+380",phoneCountry:e.phoneCountry||"UA",address:e.address||"",photoUrl:e.photoUrl||"",personnelCategory:e.personnelCategory||"",position:e.position||"",isActive:e.isActive,baseSalary:num(e.baseSalary),minimumSalary:num(e.minimumSalary),workPercent:num(e.workPercent),partsSalesPercent:num(e.partsSalesPercent),partsMarginPercent:num(e.partsMarginPercent),netProfitPercent:num(e.netProfitPercent),payrollRuleNote:e.payrollRuleNote||"",documents:docs.map(name=>e.documents.find(d=>d.name===name)||{type:name.toUpperCase().replaceAll(" ","_"),name,status:"MISSING"}),roleCode:e.access?.roleCode||"",locationId:e.access?.location?.id||"",cabinetEnabled:Boolean(e.access?.cabinetEnabled),cabinetStatus:e.access?.cabinetStatus||"NOT_OPENED",mechanicResourceId:e.access?.mechanicResource?.id||""}}
function initials(e:{firstName:string;lastName:string}){return `${e.firstName?.[0]||""}${e.lastName?.[0]||""}`.toUpperCase()||"HR"}

export function Personnel(){
 const [items,setItems]=useState<Employee[]>([]);const [query,setQuery]=useState("");const [category,setCategory]=useState("");const [form,setForm]=useState<FormState|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [accessCatalog,setAccessCatalog]=useState<AccessCatalog|null>(null);const [accessMessage,setAccessMessage]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/personnel",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Не вдалося завантажити персонал");setItems(d.items||[])}catch(e){setError(e instanceof Error?e.message:"Помилка")}finally{setLoading(false)}}
 async function loadAccess(){try{const r=await fetch("/api/personnel/access-catalog",{cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok){setAccessCatalog(null);setAccessMessage(r.status===401?"Увійдіть як Власник, Виконавчий директор або Завідувач станцією, щоб керувати кабінетами.":d?.message||"Керування доступами для Вашої ролі не дозволене.");return}setAccessCatalog(d);setAccessMessage("")}catch{setAccessCatalog(null);setAccessMessage("Не вдалося завантажити матрицю посад і станцій.")}}
 useEffect(()=>{void load();void loadAccess()},[]);
 const filtered=useMemo(()=>items.filter(e=>{const hay=`${e.firstName} ${e.lastName} ${e.email||""} ${e.phone||""} ${e.position||""} ${e.access?.location?.name||""}`.toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(!category||e.personnelCategory===category)}),[items,query,category]);
 const selectedRole=form&&accessCatalog?accessCatalog.roles.find(role=>role.code===form.roleCode)||null:null;
 const roleManageable=Boolean(form&&accessCatalog&&accessCatalog.roles.some(role=>role.code===form.roleCode));
 const availableMechanics=useMemo(()=>accessCatalog?.unlinkedMechanics.filter(mechanic=>!form?.locationId||mechanic.locationId===form.locationId)||[],[accessCatalog,form?.locationId]);
 async function save(){if(!form)return;setError("");setNotice("");if(accessCatalog&&form.roleCode){const role=accessCatalog.roles.find(item=>item.code===form.roleCode);if(role?.requiresLocation&&!form.locationId){setError("Оберіть станцію для цієї посади.");return}if(form.cabinetEnabled&&!form.email.trim()){setError("Щоб відкрити кабінет CRM, вкажіть e-mail працівника.");return}}setSaving(true);try{const method=form.id?"PUT":"POST";const canManageSelected=!form.id||roleManageable;const body={...form,...(!canManageSelected?{roleCode:undefined,locationId:undefined,cabinetEnabled:undefined,mechanicResourceId:undefined}:{})};const r=await fetch("/api/personnel",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||d.error||"Не вдалося зберегти");setNotice(form.cabinetEnabled?"Працівника збережено. Кабінет підготовлено до входу.":"Працівника збережено.");setForm(null);await load();await loadAccess()}catch(e){setError(e instanceof Error?e.message:"Помилка збереження")}finally{setSaving(false)}}
 async function remove(){if(!form?.id)return;if(!window.confirm("Деактивувати співробітника та закрити його доступ до CRM? Історія KPI, нарахувань і робіт буде збережена."))return;const r=await fetch(`/api/personnel?id=${encodeURIComponent(form.id)}`,{method:"DELETE"});const d=await r.json().catch(()=>null);if(r.ok){setForm(null);setNotice("Працівника деактивовано, кабінет закрито, історію збережено.");await load()}else setError(d?.message||d?.error||"Не вдалося деактивувати")}
 function update<K extends keyof FormState>(key:K,value:FormState[K]){setForm(f=>f?{...f,[key]:value}:f)}
 function selectRole(code:string){const role=accessCatalog?.roles.find(item=>item.code===code);setForm(f=>f?{...f,roleCode:code,position:role?.name||f.position,locationId:role?.requiresLocation?f.locationId:"",mechanicResourceId:code==="MECHANIC"?f.mechanicResourceId:""}:f)}
 function newEmployee(){const firstRole=accessCatalog?.roles[0];const location=firstRole?.requiresLocation&&accessCatalog?.locations.length===1?accessCatalog.locations[0].id:"";setForm({...empty,documents:empty.documents.map(d=>({...d})),roleCode:firstRole?.code||"",position:firstRole?.name||"",locationId:location})}
 async function copyLogin(){try{await navigator.clipboard.writeText(`${window.location.origin}/auth/sign-in`);setNotice("Адресу входу скопійовано.")}catch{setNotice("Адреса входу: /auth/sign-in")}}

 if(form) return <div className={styles.editorPage}>
   <header className={styles.editorTop}>
     <div><button className={styles.backLink} onClick={()=>setForm(null)}>← Персонал</button><p className={styles.eyebrow}>{form.id?"КАРТКА СПІВРОБІТНИКА":"НОВИЙ СПІВРОБІТНИК"}</p><h1>{form.firstName||"Новий"} {form.lastName||"працівник"}</h1><span className={styles.muted}>Кадровий профіль, системна посада, станція, кабінет CRM, документи та мотивація — в одній картці.</span></div>
     <div className={styles.topActions}><span className={`${styles.statusPill} ${form.isActive?styles.statusActive:""}`}>{form.isActive?"Активний":"Неактивний"}</span><button className={styles.secondary} onClick={()=>setForm(null)}>Закрити</button><button className={styles.save} disabled={saving} onClick={()=>void save()}>{saving?"Зберігаю…":"✓ Зберегти"}</button></div>
   </header>
   {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}

   <section className={styles.profileSheet}>
     <div className={styles.profileGrid}>
       <Field label="Ім’я *"><input value={form.firstName} onChange={e=>update("firstName",e.target.value)} placeholder="Тарас"/></Field>
       <Field label="Прізвище *"><input value={form.lastName} onChange={e=>update("lastName",e.target.value)} placeholder="Шевченко"/></Field>
       <Field label="Дата народження"><input type="date" value={form.birthDate} onChange={e=>update("birthDate",e.target.value)}/></Field>
       <Field label="E-mail для контакту та входу"><input type="email" value={form.email} onChange={e=>update("email",e.target.value)} placeholder="name@turbolev.ua"/></Field>
       <Field label="Телефон *"><div className={styles.phoneInput}><span>🇺🇦</span><input value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="+380"/></div></Field>
       <div className={styles.photoCell}><label>Фото</label><div className={styles.photoRow}><label className={styles.photoUpload}><span className={styles.photo}>{form.photoUrl?<img src={form.photoUrl} alt=""/>:initials({firstName:form.firstName,lastName:form.lastName})}</span><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)update("photoUrl",URL.createObjectURL(file))}}/><b>↑</b></label></div></div>
       <Field label="Категорія персоналу"><select value={form.personnelCategory} onChange={e=>update("personnelCategory",e.target.value)}><option value="">Оберіть категорію</option>{categories.map(c=><option key={c}>{c}</option>)}</select></Field>
       <Field label="Статус працівника"><select value={form.isActive?"1":"0"} onChange={e=>update("isActive",e.target.value==="1")}><option value="1">Активний</option><option value="0">Неактивний / звільнений</option></select></Field>
       <Field label="Місце проживання" wide><input value={form.address} onChange={e=>update("address",e.target.value)} placeholder="Місто, вулиця, будинок"/></Field>
       {!accessCatalog?<Field label="Посада"><select value={form.position} onChange={e=>update("position",e.target.value)}><option value="">Оберіть посаду</option>{fallbackPositions.map(p=><option key={p}>{p}</option>)}</select></Field>:null}
     </div>

     <section className={styles.accessManager}>
       <div className={styles.accessManagerHead}><div><p className={styles.eyebrow}>PERSONNEL → ACCESS → CABINET</p><h2>Посада, станція та кабінет CRM</h2><p>Посада визначає набір дозволів. Станція обмежує дані. Кабінет відкривається на e-mail працівника без ручного створення дубльованого користувача в Security.</p></div><span className={`${styles.cabinetBadge} ${form.cabinetStatus==="ACTIVE"?styles.cabinetActive:form.cabinetStatus==="WAITING_ACTIVATION"?styles.cabinetWaiting:""}`}>{cabinetLabels[form.cabinetStatus]}</span></div>
       {accessCatalog?<>
         {form.id&&form.roleCode&&!roleManageable?<div className={styles.accessWarning}>Ви можете бачити цей профіль, але Ваша роль не має права змінювати його системну посаду або кабінет.</div>:null}
         <div className={styles.accessGrid}>
           <Field label="Системна посада"><select value={form.roleCode} disabled={Boolean(form.id&&form.roleCode&&!roleManageable)} onChange={e=>selectRole(e.target.value)}><option value="">Оберіть посаду</option>{accessCatalog.roles.map(role=><option key={role.code} value={role.code}>{role.name}</option>)}</select></Field>
           <Field label="Станція"><select value={form.locationId} disabled={!selectedRole?.requiresLocation||Boolean(form.id&&form.roleCode&&!roleManageable)} onChange={e=>{update("locationId",e.target.value);update("mechanicResourceId","")}}><option value="">{selectedRole?.requiresLocation?"Оберіть станцію":"Не потрібна для цієї ролі"}</option>{accessCatalog.locations.map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</select></Field>
           {form.roleCode==="MECHANIC"?<Field label="Ресурс у Планувальнику"><select value={form.mechanicResourceId} disabled={Boolean(form.id&&form.roleCode&&!roleManageable)} onChange={e=>update("mechanicResourceId",e.target.value)}><option value="">Створити новий ресурс автоматично</option>{form.mechanicResourceId&&!availableMechanics.some(m=>m.id===form.mechanicResourceId)?<option value={form.mechanicResourceId}>Поточний ресурс механіка</option>:null}{availableMechanics.map(mechanic=><option key={mechanic.id} value={mechanic.id}>{mechanic.name}</option>)}</select></Field>:<div/>}
           <label className={styles.cabinetToggle}><input type="checkbox" checked={form.cabinetEnabled} disabled={Boolean(form.id&&form.roleCode&&!roleManageable)} onChange={e=>update("cabinetEnabled",e.target.checked)}/><span><b>Відкрити кабінет CRM</b><small>{form.cabinetEnabled?"Працівник зможе активувати доступ або увійти через Google на вказаний e-mail.":"Кадровий профіль збережеться без входу в CRM."}</small></span></label>
         </div>
         {selectedRole?.accessDescription?<p className={styles.roleDescription}>{selectedRole.accessDescription}</p>:null}
         {form.cabinetEnabled?<div className={styles.activationRow}><div><b>{form.cabinetStatus==="ACTIVE"?"Доступ уже активований":form.cabinetStatus==="WAITING_ACTIVATION"?"Очікуємо першого входу працівника":"Після збереження CRM підготує доступ"}</b><span>Вхід: Google або «Перший вхід · активувати email і пароль» на сторінці авторизації.</span></div><button type="button" className={styles.secondary} onClick={()=>void copyLogin()}>Скопіювати адресу входу</button></div>:null}
       </>:<div className={styles.accessUnavailable}>{accessMessage||"Керування кабінетами недоступне для поточної сесії."}</div>}
     </section>

     <div className={styles.documentsArea}>
       <div className={styles.docColumn}>{form.documents.slice(0,2).map((d,i)=><DocRow key={d.name} doc={d} onFile={file=>{const next=[...form.documents];next[i]={...next[i],status:"UPLOADED",fileUrl:file.name};update("documents",next)}}/>)}</div>
       <div className={styles.docColumn}>{form.documents.slice(2,5).map((d,j)=>{const i=j+2;return <DocRow key={d.name} doc={d} onFile={file=>{const next=[...form.documents];next[i]={...next[i],status:"UPLOADED",fileUrl:file.name};update("documents",next)}}/>})}</div>
       <div className={styles.docColumn}>{form.documents.slice(5).map((d,j)=>{const i=j+5;return <DocRow key={d.name} doc={d} onFile={file=>{const next=[...form.documents];next[i]={...next[i],status:"UPLOADED",fileUrl:file.name};update("documents",next)}}/>})}</div>
     </div>

     <div className={styles.salarySection}>
       <div className={styles.salaryTitle}><div><strong>Чернетка параметрів мотивації</strong><span>Формула зарплати ще не активна; поля збережені для майбутнього налаштування</span></div></div>
       <div className={styles.salaryFormula}>
         <SalaryField label="Ставка" value={form.baseSalary} suffix="₴" onChange={v=>update("baseSalary",v)}/><span className={styles.mathSign}>+</span>
         <SalaryField label="СР · сума робіт" value={form.workPercent} suffix="%" onChange={v=>update("workPercent",v)}/><SalaryField label="СЗ · продаж запчастин" value={form.partsSalesPercent} suffix="%" onChange={v=>update("partsSalesPercent",v)}/><SalaryField label="НЗ · маржа запчастин" value={form.partsMarginPercent} suffix="%" onChange={v=>update("partsMarginPercent",v)}/><SalaryField label="ЧП · чистий прибуток" value={form.netProfitPercent} suffix="%" onChange={v=>update("netProfitPercent",v)}/>
       </div>
       <div className={styles.salaryBottom}><Field label="Мінімальна гарантована зарплата"><input type="number" value={form.minimumSalary} onChange={e=>update("minimumSalary",e.target.value)} placeholder="8000"/></Field><Field label="Примітка до правила" wide><textarea value={form.payrollRuleNote} onChange={e=>update("payrollRuleNote",e.target.value)} placeholder="Наприклад: ставка + 40% від робіт, виплата двічі на місяць"/></Field></div>
     </div>
   </section>

   <footer className={styles.editorFooter}>{form.id&&<button className={styles.danger} onClick={()=>void remove()}>Деактивувати працівника та закрити кабінет</button>}<div className={styles.footerRight}><button className={styles.secondary} onClick={()=>setForm(null)}>Закрити</button><button className={styles.save} disabled={saving} onClick={()=>void save()}>{saving?"Зберігаю…":"✓ Зберегти"}</button></div></footer>
 </div>;

 return <div className={styles.page}><header className={styles.head}><div><p className={styles.eyebrow}>TURBO LEV · HR + ACCESS</p><h1>Персонал</h1><span className={styles.muted}>Одна точка керування працівниками: кадрові картки, системні посади, станції, CRM-кабінети, документи та мотивація.</span></div><button className={styles.primary} onClick={newEmployee}>+ Додати співробітника</button></header>
 {notice&&<div className={styles.notice}>{notice}</div>}{accessMessage&&<div className={styles.accessInfo}>{accessMessage}</div>}
 <div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук за ПІБ, телефоном, e-mail, посадою або станцією..."/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Усі категорії</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>{error&&<div className={styles.error}>{error}</div>}
 {loading?<div className={styles.empty}>Завантаження…</div>:filtered.length?<div className={styles.grid}>{filtered.map(e=><article className={styles.card} key={e.id}><button className={styles.identity} onClick={()=>setForm(toForm(e))}><span className={styles.avatar}>{e.photoUrl?<img src={e.photoUrl} alt=""/>:initials(e)}</span><span><strong>{e.firstName} {e.lastName}</strong><small>{e.access?.roleName||e.position||"Посада не вказана"}</small><small>{e.access?.location?.name||e.phone||e.email||"Станція не вказана"}</small></span><span className={`${styles.status} ${e.isActive?styles.active:""}`}>{e.isActive?"Активний":"Неактивний"}</span></button><div className={styles.facts}><div><span>Кабінет</span><b>{cabinetLabels[e.access?.cabinetStatus||"NOT_OPENED"]}</b></div><div><span>Станція</span><b>{e.access?.location?.name||"—"}</b></div><div><span>Ставка</span><b>{e.compensationRestricted?"Обмежено":e.baseSalary?`${Number(e.baseSalary).toLocaleString("uk-UA")} ₴`:"—"}</b></div><div><span>Документи</span><b>{e.documents.filter(d=>d.status!=="MISSING").length}/{docs.length}</b></div></div></article>)}</div>:<div className={styles.empty}>Співробітників не знайдено.</div>}
 </div>
}

function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={`${styles.field} ${wide?styles.wide:""}`}><label>{label}</label>{children}</div>}
function DocRow({doc,onFile}:{doc:EmployeeDoc;onFile:(file:File)=>void}){return <label className={`${styles.docRow} ${doc.status!=="MISSING"?styles.docReady:""}`}><input type="file" onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f)}}/><span>{doc.status!=="MISSING"?"✓":"↑"}</span><b>{doc.name}</b><small>{doc.status!=="MISSING"?"Додано":"Завантажити"}</small></label>}
function SalaryField({label,value,suffix,onChange}:{label:string;value:string;suffix:string;onChange:(v:string)=>void}){return <div className={styles.salaryField}><label>{label}</label><div><input type="number" step="0.01" value={value} onChange={e=>onChange(e.target.value)}/><span>{suffix}</span></div></div>}
