"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./personnel.module.css";

type EmployeeDoc={id?:string;type:string;name:string;status:string;fileUrl?:string|null};
type Employee={id:string;firstName:string;lastName:string;birthDate:string|null;email:string|null;phone:string|null;phoneCountry:string|null;address:string|null;photoUrl:string|null;personnelCategory:string|null;position:string|null;crmLogin:string|null;isActive:boolean;baseSalary:string|number|null;minimumSalary:string|number|null;workPercent:string|number|null;partsSalesPercent:string|number|null;partsMarginPercent:string|number|null;netProfitPercent:string|number|null;payrollRuleNote:string|null;documents:EmployeeDoc[]};

type FormState={id?:string;firstName:string;lastName:string;birthDate:string;email:string;phone:string;phoneCountry:string;address:string;photoUrl:string;personnelCategory:string;position:string;crmLogin:string;password:string;isActive:boolean;baseSalary:string;minimumSalary:string;workPercent:string;partsSalesPercent:string;partsMarginPercent:string;netProfitPercent:string;payrollRuleNote:string;documents:EmployeeDoc[]};

const categories=["Керівництво","Продажі","Підбір запчастин","Майстри","Автомеханіки","Адміністрація","Маркетинг","Інше"];
const positions=["Виконавчий директор","РОП","Продавник","Підборщик","Завідувач станцією","Майстер","Автомеханік","Маркетинг-директор","SMM-маркетолог","Performance-маркетолог","Бухгалтер","HR","IT / Адміністратор"];
const docs=["Паспорт","ІПН","Диплом","Трудова","Резюме","Договір підряду","Договір про найм","Договір МВ"];
const empty:FormState={firstName:"",lastName:"",birthDate:"",email:"",phone:"+380",phoneCountry:"UA",address:"",photoUrl:"",personnelCategory:"",position:"",crmLogin:"",password:"",isActive:true,baseSalary:"",minimumSalary:"",workPercent:"",partsSalesPercent:"",partsMarginPercent:"",netProfitPercent:"",payrollRuleNote:"",documents:docs.map(name=>({type:name.toUpperCase().replaceAll(" ","_"),name,status:"MISSING"}))};
function num(v:string|number|null){return v==null?"":String(v)}
function toForm(e:Employee):FormState{return{id:e.id,firstName:e.firstName,lastName:e.lastName,birthDate:e.birthDate?e.birthDate.slice(0,10):"",email:e.email||"",phone:e.phone||"+380",phoneCountry:e.phoneCountry||"UA",address:e.address||"",photoUrl:e.photoUrl||"",personnelCategory:e.personnelCategory||"",position:e.position||"",crmLogin:e.crmLogin||"",password:"",isActive:e.isActive,baseSalary:num(e.baseSalary),minimumSalary:num(e.minimumSalary),workPercent:num(e.workPercent),partsSalesPercent:num(e.partsSalesPercent),partsMarginPercent:num(e.partsMarginPercent),netProfitPercent:num(e.netProfitPercent),payrollRuleNote:e.payrollRuleNote||"",documents:docs.map(name=>e.documents.find(d=>d.name===name)||{type:name.toUpperCase().replaceAll(" ","_"),name,status:"MISSING"})}}
function initials(e:Pick<Employee,"firstName"|"lastName">){return `${e.firstName?.[0]||""}${e.lastName?.[0]||""}`.toUpperCase()||"HR"}

export function Personnel(){
 const [items,setItems]=useState<Employee[]>([]);const [query,setQuery]=useState("");const [category,setCategory]=useState("");const [form,setForm]=useState<FormState|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/personnel",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Не вдалося завантажити персонал");setItems(d.items||[])}catch(e){setError(e instanceof Error?e.message:"Помилка")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>items.filter(e=>{const hay=`${e.firstName} ${e.lastName} ${e.email||""} ${e.phone||""} ${e.position||""}`.toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(!category||e.personnelCategory===category)}),[items,query,category]);
 async function save(){if(!form)return;setError("");try{const method=form.id?"PUT":"POST";const r=await fetch("/api/personnel",{method,headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Не вдалося зберегти");setForm(null);await load()}catch(e){setError(e instanceof Error?e.message:"Помилка збереження")}}
 async function remove(){if(!form?.id)return;if(!window.confirm("Видалити співробітника?"))return;const r=await fetch(`/api/personnel?id=${encodeURIComponent(form.id)}`,{method:"DELETE"});if(r.ok){setForm(null);await load()}}
 function generate(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";let p="";for(let i=0;i<14;i++)p+=chars[Math.floor(Math.random()*chars.length)];setForm(f=>f?{...f,password:p}:f)}
 return <div className={styles.page}><header className={styles.head}><div><p className={styles.eyebrow}>TURBO LEV · HR</p><h1>Персонал</h1><span className={styles.muted}>Співробітники, посади, документи, CRM-доступ і правила нарахування зарплати</span></div><button className={styles.primary} onClick={()=>setForm({...empty,documents:empty.documents.map(d=>({...d}))})}>+ Додати співробітника</button></header>
 <div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук за ПІБ, телефоном, e-mail або посадою..."/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Усі категорії</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>{error&&<div className={styles.error}>{error}</div>}
 {loading?<div className={styles.empty}>Завантаження…</div>:filtered.length?<div className={styles.grid}>{filtered.map(e=><article className={styles.card} key={e.id}><button className={styles.identity} onClick={()=>setForm(toForm(e))}><span className={styles.avatar}>{e.photoUrl?<img src={e.photoUrl} alt=""/>:initials(e)}</span><span><strong>{e.firstName} {e.lastName}</strong><small>{e.position||"Посада не вказана"}</small><small>{e.phone||e.email||"Контакти не вказані"}</small></span><span className={`${styles.status} ${e.isActive?styles.active:""}`}>{e.isActive?"Активний":"Неактивний"}</span></button><div className={styles.facts}><div><span>Категорія</span><b>{e.personnelCategory||"—"}</b></div><div><span>Ставка</span><b>{e.baseSalary?`${Number(e.baseSalary).toLocaleString("uk-UA")} ₴`:"—"}</b></div><div><span>% робіт</span><b>{e.workPercent?`${e.workPercent}%`:"—"}</b></div><div><span>Документи</span><b>{e.documents.filter(d=>d.status!=="MISSING").length}/{docs.length}</b></div></div></article>)}</div>:<div className={styles.empty}>Співробітників не знайдено.</div>}
 {form&&<div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setForm(null)}}><aside className={styles.drawer}><header className={styles.drawerHead}><div><p className={styles.eyebrow}>{form.id?"КАРТКА СПІВРОБІТНИКА":"НОВИЙ СПІВРОБІТНИК"}</p><h2>{form.firstName||"Ім’я"} {form.lastName||"Прізвище"}</h2></div><button className={styles.close} onClick={()=>setForm(null)}>×</button></header><div className={styles.body}>
 <section className={styles.section}><div className={styles.sectionTitle}><strong>Особисті дані</strong><span>базова інформація</span></div><div className={styles.formGrid}>{[["Ім’я *","firstName"],["Прізвище *","lastName"],["Дата народження","birthDate"],["E-mail","email"],["Телефон","phone"],["Місце проживання","address"]].map(([label,key])=><div className={`${styles.field} ${key==="address"?styles.wide:""}`} key={key}><label>{label}</label><input type={key==="birthDate"?"date":"text"} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}</div></section>
 <section className={styles.section}><div className={styles.sectionTitle}><strong>Робота в Turbo LEV</strong><span>категорія та посада</span></div><div className={styles.formGrid}><div className={styles.field}><label>Категорія персоналу</label><select value={form.personnelCategory} onChange={e=>setForm({...form,personnelCategory:e.target.value})}><option value="">Оберіть категорію</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className={styles.field}><label>Посада</label><select value={form.position} onChange={e=>setForm({...form,position:e.target.value})}><option value="">Оберіть посаду</option>{positions.map(p=><option key={p}>{p}</option>)}</select></div><div className={styles.field}><label>Статус</label><select value={form.isActive?"1":"0"} onChange={e=>setForm({...form,isActive:e.target.value==="1"})}><option value="1">Активний</option><option value="0">Неактивний</option></select></div></div></section>
 <section className={styles.section}><div className={styles.sectionTitle}><strong>Доступ до CRM</strong><span>пароль назад не відображається</span></div><div className={styles.formGrid}><div className={styles.field}><label>Логін / e-mail</label><input value={form.crmLogin} onChange={e=>setForm({...form,crmLogin:e.target.value})}/></div><div className={`${styles.field} ${styles.wide}`}><label>{form.id?"Новий пароль":"Пароль"}</label><div className={styles.passwordRow}><input value={form.password} onChange={e=>setForm({...form,password:e.target.value})} type="text" placeholder={form.id?"Залиште порожнім, щоб не змінювати":""}/><button className={styles.secondary} onClick={generate}>Згенерувати</button></div></div></div></section>
 <section className={styles.section}><div className={styles.sectionTitle}><strong>Документи</strong><span>паспорт, ІПН, договори та інше</span></div><div className={styles.docs}>{form.documents.map((d,i)=><div className={styles.doc} key={d.name}><label><b>☁ {d.name}</b><span>{d.status==="MISSING"?"Не завантажено":d.name+" додано"}</span><input type="file" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const next=[...form.documents];next[i]={...next[i],status:"UPLOADED",fileUrl:null};setForm({...form,documents:next})}}/></label></div>)}</div></section>
 <section className={styles.section}><div className={styles.sectionTitle}><strong>Правила нарахування зарплати</strong><span>індивідуальна формула співробітника</span></div><div className={styles.payGrid}>{[["Ставка","baseSalary"],["Мінімальна","minimumSalary"],["% робіт","workPercent"],["% продажу запчастин","partsSalesPercent"],["% маржі запчастин","partsMarginPercent"],["% чистого прибутку","netProfitPercent"]].map(([label,key])=><div className={styles.field} key={key}><label>{label}</label><input type="number" step="0.01" value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}</div><div className={styles.field} style={{marginTop:12}}><label>Примітка до правила</label><textarea value={form.payrollRuleNote} onChange={e=>setForm({...form,payrollRuleNote:e.target.value})} placeholder="Наприклад: ставка + 40% від робіт, виплата двічі на місяць"/></div><div className={styles.formula}>Формула: ставка + % робіт + % продажу запчастин + % маржі запчастин + % чистого прибутку. Нульові поля просто не беруть участі у розрахунку.</div></section>
 </div><footer className={styles.footer}>{form.id&&<button className={styles.danger} onClick={()=>void remove()}>Видалити</button>}<button className={styles.secondary} onClick={()=>setForm(null)}>Закрити</button><button className={styles.save} onClick={()=>void save()}>✓ Зберегти</button></footer></aside></div>}
 </div>
}
