"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./personnel.module.css";

type EmployeeDoc={id?:string;type:string;name:string;status:string;fileUrl?:string|null};
type RoleAssignment={id:string;isPrimary:boolean;role:{code:string;name:string;category:string|null};location:{id:string;name:string}|null};
type CabinetStatus="NOT_OPENED"|"WAITING_ACTIVATION"|"ACTIVE"|"SUSPENDED";
type EmployeeAccess={roleCode:string|null;roleName:string|null;location:{id:string;name:string}|null;cabinetStatus:CabinetStatus;cabinetEnabled:boolean;userId:string|null;authLinked:boolean;lastLoginAt:string|null;mechanicResource:{id:string;name:string;locationId:string;isActive:boolean;userId:string|null}|null};
type Employee={id:string;firstName:string;lastName:string;birthDate:string|null;email:string|null;phone:string|null;phoneCountry:string|null;address:string|null;photoUrl:string|null;personnelCategory:string|null;position:string|null;crmLogin:string|null;isActive:boolean;baseSalary:string|number|null;minimumSalary:string|number|null;workPercent:string|number|null;partsSalesPercent:string|number|null;partsMarginPercent:string|number|null;netProfitPercent:string|number|null;payrollRuleNote:string|null;compensationRestricted?:boolean;documents:EmployeeDoc[];roleAssignments:RoleAssignment[];access?:EmployeeAccess};
type StaffRole={code:string;name:string;category:string|null;economicsMode:string;sortOrder:number};
type Location={id:string;name:string;sortOrder:number};
type PersonnelMeta={roles:StaffRole[];locations:Location[]};
type RoleOption={code:string;name:string;category:string|null;requiresLocation:boolean;accessDescription:string|null};
type AccessCatalog={grantedScope:string|null;managerRoles:string[];roles:RoleOption[];locations:Array<{id:string;name:string}>};
type FormState={id?:string;firstName:string;lastName:string;birthDate:string;email:string;phone:string;phoneCountry:string;address:string;photoUrl:string;personnelCategory:string;position:string;isActive:boolean;baseSalary:string;minimumSalary:string;workPercent:string;partsSalesPercent:string;partsMarginPercent:string;netProfitPercent:string;payrollRuleNote:string;documents:EmployeeDoc[];staffRoleCode:string;locationId:string;cabinetEnabled:boolean;cabinetStatus:CabinetStatus};

const categories=["Керівництво","Продажі","Підбір запчастин","Майстри","Автомеханіки","Адміністрація","Маркетинг","Інше"];
const docs=["Паспорт","ІПН","Диплом","Трудова","Резюме","Договір підряду","Договір про найм","Договір МВ"];
const roleCategory:Record<string,string>={OWNER:"Керівництво",EXECUTIVE_DIRECTOR:"Керівництво",HEAD_OF_SALES:"Продажі",SALES:"Продажі",PARTS_SPECIALIST:"Підбір запчастин",STATION_MANAGER:"Майстри",MECHANIC:"Автомеханіки",ACCOUNTANT:"Адміністрація",ADMINISTRATOR:"Адміністрація"};
const cabinetLabels:Record<CabinetStatus,string>={NOT_OPENED:"Кабінет не відкритий",WAITING_ACTIVATION:"Очікує активації",ACTIVE:"Кабінет активний",SUSPENDED:"Доступ призупинений"};
const empty:FormState={firstName:"",lastName:"",birthDate:"",email:"",phone:"+380",phoneCountry:"UA",address:"",photoUrl:"",personnelCategory:"",position:"",isActive:true,baseSalary:"",minimumSalary:"",workPercent:"",partsSalesPercent:"",partsMarginPercent:"",netProfitPercent:"",payrollRuleNote:"",documents:docs.map(name=>({type:name.toUpperCase().replaceAll(" ","_"),name,status:"MISSING"})),staffRoleCode:"",locationId:"",cabinetEnabled:false,cabinetStatus:"NOT_OPENED"};

function num(v:string|number|null){return v==null?"":String(v)}
function primaryAssignment(e:Employee){return e.roleAssignments?.find(item=>item.isPrimary)||e.roleAssignments?.[0]||null}
function roleName(e:Employee){return e.access?.roleName||primaryAssignment(e)?.role.name||e.position||"Роль не вказана"}
function locationName(e:Employee){return e.access?.location?.name||primaryAssignment(e)?.location?.name||"—"}
function initials(e:{firstName:string;lastName:string}){return `${e.firstName?.[0]||""}${e.lastName?.[0]||""}`.toUpperCase()||"HR"}
function toForm(e:Employee):FormState{const assignment=primaryAssignment(e);return{id:e.id,firstName:e.firstName,lastName:e.lastName,birthDate:e.birthDate?e.birthDate.slice(0,10):"",email:e.email||"",phone:e.phone||"+380",phoneCountry:e.phoneCountry||"UA",address:e.address||"",photoUrl:e.photoUrl||"",personnelCategory:e.personnelCategory||"",position:e.position||"",isActive:e.isActive,baseSalary:num(e.baseSalary),minimumSalary:num(e.minimumSalary),workPercent:num(e.workPercent),partsSalesPercent:num(e.partsSalesPercent),partsMarginPercent:num(e.partsMarginPercent),netProfitPercent:num(e.netProfitPercent),payrollRuleNote:e.payrollRuleNote||"",documents:docs.map(name=>e.documents.find(d=>d.name===name)||{type:name.toUpperCase().replaceAll(" ","_"),name,status:"MISSING"}),staffRoleCode:e.access?.roleCode||assignment?.role.code||"",locationId:e.access?.location?.id||assignment?.location?.id||"",cabinetEnabled:Boolean(e.access?.cabinetEnabled),cabinetStatus:e.access?.cabinetStatus||"NOT_OPENED"}}

export function Personnel(){
 const [items,setItems]=useState<Employee[]>([]);const [meta,setMeta]=useState<PersonnelMeta>({roles:[],locations:[]});const [accessCatalog,setAccessCatalog]=useState<AccessCatalog|null>(null);const [accessMessage,setAccessMessage]=useState("");const [query,setQuery]=useState("");const [category,setCategory]=useState("");const [roleFilter,setRoleFilter]=useState("");const [statusFilter,setStatusFilter]=useState("active");const [form,setForm]=useState<FormState|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [compensationRestricted,setCompensationRestricted]=useState(false);

 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/personnel",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||d.error||"Не вдалося завантажити персонал");setItems(d.items||[]);setMeta({roles:Array.isArray(d.meta?.roles)?d.meta.roles:[],locations:Array.isArray(d.meta?.locations)?d.meta.locations:[]});setCompensationRestricted(Boolean(d.security?.compensationRestricted))}catch(e){setError(e instanceof Error?e.message:"Помилка")}finally{setLoading(false)}}
 async function loadAccess(){try{const r=await fetch("/api/personnel/access-catalog",{cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok){setAccessCatalog(null);setAccessMessage(r.status===401?"Увійдіть як Власник, Виконавчий директор або Завідувач станцією, щоб додавати працівників і відкривати їм кабінети.":d?.message||"Для Вашої ролі керування персоналом не дозволене.");return}setAccessCatalog(d);setAccessMessage("")}catch{setAccessCatalog(null);setAccessMessage("Не вдалося завантажити права на керування персоналом.")}}
 useEffect(()=>{void load();void loadAccess()},[]);

 const filtered=useMemo(()=>items.filter(e=>{const assignment=primaryAssignment(e);const hay=`${e.firstName} ${e.lastName} ${e.email||""} ${e.phone||""} ${roleName(e)} ${locationName(e)}`.toLowerCase();const statusOk=statusFilter==="all"||(statusFilter==="active"?e.isActive:!e.isActive);return(!query||hay.includes(query.toLowerCase()))&&(!category||e.personnelCategory===category)&&(!roleFilter||(e.access?.roleCode||assignment?.role.code)===roleFilter)&&statusOk}),[items,query,category,roleFilter,statusFilter]);
 const stats=useMemo(()=>({total:items.length,active:items.filter(e=>e.isActive).length,mechanics:items.filter(e=>e.isActive&&(e.access?.roleCode||primaryAssignment(e)?.role.code)==="MECHANIC").length,cabinets:items.filter(e=>e.access?.cabinetEnabled).length}),[items]);
 const selectedRole=form&&accessCatalog?accessCatalog.roles.find(role=>role.code===form.staffRoleCode)||null:null;
 const roleManageable=Boolean(form&&accessCatalog&&accessCatalog.roles.some(role=>role.code===form.staffRoleCode));

 function update<K extends keyof FormState>(key:K,value:FormState[K]){setForm(f=>f?{...f,[key]:value}:f)}
 function selectRole(code:string){const role=accessCatalog?.roles.find(item=>item.code===code);setForm(f=>f?{...f,staffRoleCode:code,position:role?.name||f.position,personnelCategory:roleCategory[code]||f.personnelCategory,locationId:role?.requiresLocation?f.locationId:""}:f)}
 function newEmployee(){if(!accessCatalog){setError(accessMessage||"Для додавання працівників потрібен авторизований керівник.");return}const first=accessCatalog.roles[0];setForm({...empty,documents:empty.documents.map(d=>({...d})),staffRoleCode:first?.code||"",position:first?.name||"",personnelCategory:first?roleCategory[first.code]||"":"",locationId:first?.requiresLocation&&accessCatalog.locations.length===1?accessCatalog.locations[0].id:""})}
 async function copyLogin(){try{await navigator.clipboard.writeText(`${window.location.origin}/auth/sign-in`);setNotice("Адресу входу скопійовано.")}catch{setNotice("Сторінка входу: /auth/sign-in")}}

 async function save(){if(!form||!accessCatalog)return;setError("");setNotice("");const role=accessCatalog.roles.find(item=>item.code===form.staffRoleCode);if(!role){setError("Оберіть системну посаду, яку Ваша роль має право призначати.");return}if(role.requiresLocation&&!form.locationId){setError("Оберіть станцію для цієї посади.");return}if(form.cabinetEnabled&&!form.email.trim()){setError("Щоб відкрити кабінет CRM, вкажіть e-mail працівника.");return}if(form.id&&!roleManageable){setError("Ваша роль не може змінювати цього працівника.");return}setSaving(true);try{const method=form.id?"PUT":"POST";const r=await fetch("/api/personnel",{method,headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.message||d?.error||"Не вдалося зберегти");setForm(null);setNotice(form.cabinetEnabled?"Працівника збережено. Кабінет підготовлено до входу.":"Працівника збережено. Робочий профіль активний без CRM-кабінету.");await load();await loadAccess()}catch(e){setError(e instanceof Error?e.message:"Помилка збереження")}finally{setSaving(false)}}
 async function remove(){if(!form?.id)return;if(!window.confirm("Деактивувати працівника та закрити його кабінет? Історія робіт, KPI, зарплати та аудиту збережеться."))return;setSaving(true);try{const r=await fetch(`/api/personnel?id=${encodeURIComponent(form.id)}`,{method:"DELETE"});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.message||d?.error||"Не вдалося деактивувати");setForm(null);setNotice("Працівника деактивовано. Кабінет і нові призначення закриті, історію збережено.");await load()}catch(e){setError(e instanceof Error?e.message:"Помилка")}finally{setSaving(false)}}

 if(form)return <div className={styles.editorPage}>
   <header className={styles.editorTop}><div><button className={styles.backLink} onClick={()=>setForm(null)}>← Персонал</button><p className={styles.eyebrow}>{form.id?"КАРТКА СПІВРОБІТНИКА":"НОВИЙ СПІВРОБІТНИК"}</p><h1>{form.firstName||"Новий"} {form.lastName||"працівник"}</h1><span className={styles.muted}>Кадровий профіль, системна посада, станція, Планувальник і CRM-кабінет — в одній картці.</span></div><div className={styles.topActions}><span className={`${styles.statusPill} ${form.isActive?styles.statusActive:""}`}>{form.isActive?"Активний":"Неактивний"}</span><button className={styles.secondary} onClick={()=>setForm(null)}>Закрити</button><button className={styles.save} disabled={saving||Boolean(form.id&&form.staffRoleCode&&!roleManageable)} onClick={()=>void save()}>{saving?"Зберігаю…":"✓ Зберегти"}</button></div></header>
   {error&&<div className={styles.error}>{error}</div>}
   <section className={styles.profileSheet}>
     <div className={styles.sectionHeading}><div><b>Основні дані</b><span>Контакти та кадрова інформація</span></div></div>
     <div className={styles.profileGrid}>
       <Field label="Ім’я *"><input value={form.firstName} onChange={e=>update("firstName",e.target.value)} placeholder="Тарас"/></Field><Field label="Прізвище *"><input value={form.lastName} onChange={e=>update("lastName",e.target.value)} placeholder="Шевченко"/></Field><Field label="Дата народження"><input type="date" value={form.birthDate} onChange={e=>update("birthDate",e.target.value)}/></Field><Field label="E-mail для контакту та входу"><input type="email" value={form.email} onChange={e=>update("email",e.target.value)} placeholder="name@turbolev.ua"/></Field>
       <Field label="Телефон"><div className={styles.phoneInput}><span>🇺🇦</span><input value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="+380"/></div></Field><div className={styles.photoCell}><label>Фото</label><div className={styles.photoRow}><label className={styles.photoUpload}><span className={styles.photo}>{form.photoUrl?<img src={form.photoUrl} alt=""/>:initials(form)}</span><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)update("photoUrl",URL.createObjectURL(file))}}/><b>↑</b></label></div></div><Field label="Категорія"><select value={form.personnelCategory} onChange={e=>update("personnelCategory",e.target.value)}><option value="">Оберіть категорію</option>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Статус працівника"><select value={form.isActive?"1":"0"} onChange={e=>update("isActive",e.target.value==="1")}><option value="1">Активний</option><option value="0">Неактивний / звільнений</option></select></Field><Field label="Місце проживання" wide><input value={form.address} onChange={e=>update("address",e.target.value)} placeholder="Місто, вулиця, будинок"/></Field>
     </div>

     <section className={styles.accessManager}>
       <div className={styles.accessManagerHead}><div><p className={styles.eyebrow}>PERSONNEL → ACCESS → CABINET</p><h2>Посада, станція та кабінет CRM</h2><p>Посада визначає дозволи, станція — межу даних. Планувальник формується з кадрового профілю, а кабінет лише відкриває працівнику вхід у CRM.</p></div><span className={`${styles.cabinetBadge} ${form.cabinetStatus==="ACTIVE"?styles.cabinetActive:form.cabinetStatus==="WAITING_ACTIVATION"?styles.cabinetWaiting:""}`}>{cabinetLabels[form.cabinetStatus]}</span></div>
       {!accessCatalog?<div className={styles.accessUnavailable}>{accessMessage||"Керування доступами недоступне для поточної сесії."}</div>:<>
         {form.id&&form.staffRoleCode&&!roleManageable?<div className={styles.accessWarning}>Ви бачите цього працівника, але Ваша роль не має права змінювати його посаду, станцію або кабінет.</div>:null}
         <div className={styles.accessGrid}>
           <Field label="Системна посада"><select value={form.staffRoleCode} disabled={Boolean(form.id&&form.staffRoleCode&&!roleManageable)} onChange={e=>selectRole(e.target.value)}><option value="">Оберіть посаду</option>{accessCatalog.roles.map(role=><option key={role.code} value={role.code}>{role.name}</option>)}</select></Field>
           <Field label="Станція"><select value={form.locationId} disabled={!selectedRole?.requiresLocation||Boolean(form.id&&form.staffRoleCode&&!roleManageable)} onChange={e=>update("locationId",e.target.value)}><option value="">{selectedRole?.requiresLocation?"Оберіть станцію":"Не потрібна для цієї ролі"}</option>{accessCatalog.locations.map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</select></Field>
           <label className={styles.cabinetToggle}><input type="checkbox" checked={form.cabinetEnabled} disabled={Boolean(form.id&&form.staffRoleCode&&!roleManageable)||!form.isActive} onChange={e=>update("cabinetEnabled",e.target.checked)}/><span><b>Відкрити кабінет CRM</b><small>{form.cabinetEnabled?"Створимо доступ на вказаний e-mail. Працівник активує його під час першого входу.":"Працівник залишається у штаті та Планувальнику, але не може входити в CRM."}</small></span></label>
         </div>
         {selectedRole?.accessDescription?<p className={styles.roleDescription}>{selectedRole.accessDescription}</p>:null}
         {form.staffRoleCode==="MECHANIC"?<div className={styles.mechanicNotice}><span>🔧</span><div><b>Автомеханік автоматично синхронізується з Планувальником</b><p>Навіть без кабінету CRM працівник залишається доступним по ПІБ для призначення робіт на своїй станції.</p></div></div>:null}
         {form.cabinetEnabled?<div className={styles.activationRow}><div><b>{form.cabinetStatus==="ACTIVE"?"Кабінет уже активований":form.cabinetStatus==="WAITING_ACTIVATION"?"Очікує першого входу":"Після збереження кабінет буде підготовлено"}</b><span>Працівник входить через Google або активує email/password на сторінці входу.</span></div><button type="button" className={styles.secondary} onClick={()=>void copyLogin()}>Скопіювати адресу входу</button></div>:null}
       </>}
     </section>

     <div className={styles.documentsArea}><div className={styles.docColumn}>{form.documents.slice(0,2).map((d,i)=><DocRow key={d.name} doc={d} onFile={file=>{const next=[...form.documents];next[i]={...next[i],status:"UPLOADED",fileUrl:file.name};update("documents",next)}}/>)}</div><div className={styles.docColumn}>{form.documents.slice(2,5).map((d,j)=>{const i=j+2;return <DocRow key={d.name} doc={d} onFile={file=>{const next=[...form.documents];next[i]={...next[i],status:"UPLOADED",fileUrl:file.name};update("documents",next)}}/>})}</div><div className={styles.docColumn}>{form.documents.slice(5).map((d,j)=>{const i=j+5;return <DocRow key={d.name} doc={d} onFile={file=>{const next=[...form.documents];next[i]={...next[i],status:"UPLOADED",fileUrl:file.name};update("documents",next)}}/>})}</div></div>

     {!compensationRestricted&&<div className={styles.salarySection}><div className={styles.salaryTitle}><div><strong>Чернетка параметрів мотивації</strong><span>Формула зарплати ще не активна; поля збережені для майбутнього налаштування</span></div></div><div className={styles.salaryFormula}><SalaryField label="Ставка" value={form.baseSalary} suffix="₴" onChange={v=>update("baseSalary",v)}/><span className={styles.mathSign}>+</span><SalaryField label="СР · сума робіт" value={form.workPercent} suffix="%" onChange={v=>update("workPercent",v)}/><SalaryField label="СЗ · продаж запчастин" value={form.partsSalesPercent} suffix="%" onChange={v=>update("partsSalesPercent",v)}/><SalaryField label="НЗ · маржа запчастин" value={form.partsMarginPercent} suffix="%" onChange={v=>update("partsMarginPercent",v)}/><SalaryField label="ЧП · чистий прибуток" value={form.netProfitPercent} suffix="%" onChange={v=>update("netProfitPercent",v)}/></div><div className={styles.salaryBottom}><Field label="Мінімальна гарантована зарплата"><input type="number" value={form.minimumSalary} onChange={e=>update("minimumSalary",e.target.value)} placeholder="8000"/></Field><Field label="Примітка до правила" wide><textarea value={form.payrollRuleNote} onChange={e=>update("payrollRuleNote",e.target.value)} placeholder="Наприклад: ставка + 40% від робіт"/></Field></div></div>}
   </section>
   <footer className={styles.editorFooter}>{form.id&&roleManageable?<button className={styles.danger} disabled={saving} onClick={()=>void remove()}>Деактивувати працівника та закрити кабінет</button>:<span/>}<div className={styles.footerRight}><button className={styles.secondary} onClick={()=>setForm(null)}>Закрити</button><button className={styles.save} disabled={saving||!accessCatalog||Boolean(form.id&&form.staffRoleCode&&!roleManageable)} onClick={()=>void save()}>{saving?"Зберігаю…":"✓ Зберегти"}</button></div></footer>
 </div>;

 return <div className={styles.page}>
   <header className={styles.head}><div><p className={styles.eyebrow}>TURBO LEV · HR + ACCESS</p><h1>Персонал</h1><span className={styles.muted}>Єдина точка керування людьми: посади, станції, кабінети CRM, Планувальник, документи та мотивація.</span></div><button className={styles.primary} disabled={!accessCatalog} title={!accessCatalog?accessMessage:""} onClick={newEmployee}>+ Додати співробітника</button></header>
   {notice&&<div className={styles.notice}>{notice}</div>}{accessMessage&&<div className={styles.accessInfo}>{accessMessage}</div>}
   <div className={styles.stats}><Stat label="Всього" value={stats.total}/><Stat label="Активні" value={stats.active}/><Stat label="Автомеханіки" value={stats.mechanics}/><Stat label="Відкриті кабінети" value={stats.cabinets}/></div>
   <div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Пошук за ПІБ, телефоном, e-mail, посадою або станцією..."/><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="">Усі ролі</option>{meta.roles.map(role=><option value={role.code} key={role.code}>{role.name}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Усі категорії</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="active">Активні</option><option value="all">Усі</option><option value="inactive">Неактивні</option></select></div>
   {error&&<div className={styles.error}>{error}</div>}
   {loading?<div className={styles.empty}>Завантаження персоналу…</div>:items.length===0?<div className={styles.emptyState}><div className={styles.emptyIcon}>👥</div><h3>Команду ще не додано</h3><p>Авторизований керівник може додати першого співробітника, призначити станцію та одразу відкрити його кабінет.</p><button className={styles.primary} disabled={!accessCatalog} onClick={newEmployee}>+ Додати першого співробітника</button></div>:filtered.length?<div className={styles.grid}>{filtered.map(e=>{const assignment=primaryAssignment(e);const cabinet=e.access?.cabinetStatus||"NOT_OPENED";return <article className={styles.card} key={e.id}><button className={styles.identity} onClick={()=>setForm(toForm(e))}><span className={styles.avatar}>{e.photoUrl?<img src={e.photoUrl} alt=""/>:initials(e)}</span><span className={styles.identityText}><strong>{e.firstName} {e.lastName}</strong><small>{roleName(e)}</small><small>{e.phone||e.email||"Контакти не вказані"}</small></span><span className={`${styles.status} ${e.isActive?styles.active:""}`}>{e.isActive?"Активний":"Неактивний"}</span></button><div className={styles.facts}><div><span>Роль / KPI</span><b>{e.access?.roleName||assignment?.role.name||"—"}</b></div><div><span>Локація</span><b>{locationName(e)}</b></div><div><span>Планувальник</span><b>{e.isActive&&(e.access?.roleCode||assignment?.role.code)==="MECHANIC"?"Автомеханік":"—"}</b></div><div><span>Кабінет</span><b>{cabinetLabels[cabinet]}</b></div></div></article>})}</div>:<div className={styles.empty}>За обраними фільтрами співробітників не знайдено.</div>}
 </div>
}

function Stat({label,value}:{label:string;value:number}){return <div className={styles.stat}><span>{label}</span><b>{value}</b></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={`${styles.field} ${wide?styles.wide:""}`}><label>{label}</label>{children}</div>}
function DocRow({doc,onFile}:{doc:EmployeeDoc;onFile:(file:File)=>void}){return <label className={`${styles.docRow} ${doc.status!=="MISSING"?styles.docReady:""}`}><input type="file" onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f)}}/><span>{doc.status!=="MISSING"?"✓":"↑"}</span><b>{doc.name}</b><small>{doc.status!=="MISSING"?"Додано":"Завантажити"}</small></label>}
function SalaryField({label,value,suffix,onChange}:{label:string;value:string;suffix:string;onChange:(v:string)=>void}){return <div className={styles.salaryField}><label>{label}</label><div><input type="number" step="0.01" value={value} onChange={e=>onChange(e.target.value)}/><span>{suffix}</span></div></div>}
