"use client";

import { CrmPageHeader } from "./crm-page-header";

import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type DragEvent } from "react";
import type {
  PlannerAppointmentContract as Appointment,
  PlannerLocationContract as Location,
  PlannerPostContract as Post,
  PlannerStatusContract as Status,
} from "@/src/lib/contracts/planner";
import { parsePlannerBoardPayload, plannerPayloadMessage } from "@/src/lib/contracts/planner-payload.parsers";
import { zonedDateTimeToDate } from "@/src/lib/zoned-time";
import { AvailabilityPicker } from "./availability-picker";
import { navigateCrm, readCrmRoute } from "./crm-route";
import { PlannerDayView, type PlannerDayMetrics } from "./planner-day-view";
import { PlannerDetailDrawer } from "./planner-detail-drawer";
import layoutStyles from "./planner-layout.module.css";
import styles from "./planner-v2.module.css";

type ViewMode="day"|"week";
type QuickFilter="ALL"|"COMPLETED"|"IN_PROGRESS"|"WAITING"|"OVERDUE"|"ATTENTION";
type MoveSuggestion={appointmentId:string;day:string;time:string;postId:string;postName:string;durationMinutes:number};
type PlannerEditableStatus="BOOKED"|"ARRIVED"|"NO_SHOW"|"CANCELLED"|"RESERVE";
type EditState={id:string;date:string;status:Status;postId:string;mechanicId:string;start:string;duration:string;comment:string};type DetailEditSection="POST"|"MECHANIC"|"DATETIME"|"TASK";type DetailDraft=EditState&{problem:string};

const KYIV_TZ="Europe/Kyiv";
// Keep the WALK-IN truth labels in the planner contract: the drawer renders actual, not planned, timing.
const WALK_IN_TIME_LABEL="ФАКТИЧНІ ДАТА ТА ЧАС";
const WALK_IN_DETAIL_HINT="позаплановий заїзд";
void WALK_IN_TIME_LABEL; void WALK_IN_DETAIL_HINT;
const STATUS_META:Record<Status,{label:string;tone:string}>={BOOKED:{label:"Записаний",tone:"blue"},ARRIVED:{label:"Приїхав",tone:"green"},DIAGNOSTICS:{label:"Діагностика",tone:"violet"},WAITING_PARTS_SELECTION:{label:"Підбір деталей",tone:"amber"},WAITING_CALCULATION:{label:"Калькуляція",tone:"amber"},WAITING_APPROVAL:{label:"Погодження",tone:"orange"},WAITING_PARTS:{label:"Очікує деталі",tone:"amber"},READY_FOR_REPAIR:{label:"Готовий до ремонту",tone:"green"},IN_REPAIR:{label:"У ремонті",tone:"orange"},WAITING_QC:{label:"Контроль якості",tone:"cyan"},WAITING_PAYMENT:{label:"Очікує оплату",tone:"amber"},READY_FOR_PICKUP:{label:"Готовий до видачі",tone:"green"},COMPLETED:{label:"Виданий",tone:"gray"},WARRANTY:{label:"Гарантія",tone:"pink"},PAUSED:{label:"Пауза",tone:"gray"},NO_SHOW:{label:"Не приїхав",tone:"red"},CANCELLED:{label:"Скасований",tone:"gray"},RESERVE:{label:"Резерв",tone:"gray"}};
const PLANNER_STATUS_OPTIONS:PlannerEditableStatus[]=["BOOKED","ARRIVED","NO_SHOW","CANCELLED","RESERVE"];
const PLANNER_STATUS_SET=new Set<PlannerEditableStatus>(PLANNER_STATUS_OPTIONS);
const FALLBACK_COLORS=["#FF5A1F","#2F80ED","#7C3AED","#16A34A","#D97706","#0891B2","#DB2777"];
const pad=(n:number)=>String(n).padStart(2,"0");
function dateKey(date=new Date(),timeZone=KYIV_TZ){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${map.year}-${map.month}-${map.day}`;}
function addDays(day:string,count:number){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+count);return `${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`;}
function formatDate(day:string){return new Intl.DateTimeFormat("uk-UA",{timeZone:"UTC",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${day}T12:00:00Z`));}
function dayName(day:string){return new Intl.DateTimeFormat("uk-UA",{timeZone:"UTC",weekday:"short"}).format(new Date(`${day}T12:00:00Z`)).replace(".","");}
function longDay(day:string){return new Intl.DateTimeFormat("uk-UA",{timeZone:"UTC",weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${day}T12:00:00Z`));}
function clock(iso:string,timeZone=KYIV_TZ){return new Intl.DateTimeFormat("uk-UA",{timeZone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(iso));}
function duration(item:Appointment){return Math.max(30,Math.round((+new Date(item.plannedEndAt)-+new Date(item.plannedStartAt))/60000));}
function isActualWalkIn(item:Appointment){return item.source==="WALK_IN"&&Boolean(item.actualStartAt||item.actualArrivalAt);}
function displayStartAt(item:Appointment){return isActualWalkIn(item)?(item.actualStartAt||item.actualArrivalAt||item.plannedStartAt):item.plannedStartAt;}
function displayEndAt(item:Appointment){return isActualWalkIn(item)?new Date(+new Date(displayStartAt(item))+duration(item)*60000).toISOString():item.plannedEndAt;}
function displayDay(item:Appointment,timeZone:string){return dateKey(new Date(displayStartAt(item)),timeZone);}
function amount(value:Appointment["estimatedAmount"]){const n=Number(value);return value!=null&&value!==""&&Number.isFinite(n)?new Intl.NumberFormat("uk-UA",{style:"currency",currency:"UAH",maximumFractionDigits:0}).format(n):"";}
function colorFromPost(post:Post,index:number){return post.capabilities.find(x=>x.startsWith("COLOR:"))?.slice(6)||FALLBACK_COLORS[index%FALLBACK_COLORS.length];}
function postType(post:Post){const type=post.capabilities.find(x=>x.startsWith("TYPE:"))?.slice(5);return type==="PIT"?"Яма":type==="ALIGNMENT"?"Розвал-сходження":type==="NO_LIFT"?"Без підйомника":"Підйомник";}
function paymentLabel(status:Appointment["payment"]["status"]){return ({NOT_FORMED:"Не сформовано",UNPAID:"Не оплачено",PARTIAL:"Часткова оплата",PAID:"Оплачено",OVERDUE:"Прострочено",CANCELLED:"Скасовано"})[status];}
function timelineStamp(iso:string|null,timeZone:string){return iso?`${new Intl.DateTimeFormat("uk-UA",{timeZone,day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(iso))}, ${clock(iso,timeZone)}`:"—";}
function isPlannerStatus(value:string|undefined):value is PlannerEditableStatus{return Boolean(value&&PLANNER_STATUS_SET.has(value as PlannerEditableStatus));}
function editState(item:Appointment,timeZone:string):EditState{return{id:item.id,date:dateKey(new Date(item.plannedStartAt),timeZone),status:item.status,postId:item.postId||"",mechanicId:item.mechanicId||"",start:clock(item.plannedStartAt,timeZone),duration:String(duration(item)),comment:item.comment||""};}

export function PlannerV2(){
 const [anchorDay,setAnchorDay]=useState(()=>dateKey());const [view,setView]=useState<ViewMode>("day");const [locations,setLocations]=useState<Location[]>([]);const [locationId,setLocationId]=useState("");const [appointments,setAppointments]=useState<Appointment[]>([]);const [statusFilter,setStatusFilter]=useState("");const [mechanicFilter,setMechanicFilter]=useState("");const [postFilter,setPostFilter]=useState("");const [searchDraft,setSearchDraft]=useState("");const [search,setSearch]=useState("");const [message,setMessage]=useState("План робіт готовий.");const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<Appointment|null>(null);const [edit,setEdit]=useState<EditState|null>(null);const [detailEdit,setDetailEdit]=useState<DetailEditSection|null>(null);const [detailDraft,setDetailDraft]=useState<DetailDraft|null>(null);const [saving,setSaving]=useState(false);const [dayMetrics,setDayMetrics]=useState<PlannerDayMetrics|null>(null);const [quickFilter,setQuickFilter]=useState<QuickFilter>("ALL");const [suggestion,setSuggestion]=useState<MoveSuggestion|null>(null);const [blockPost,setBlockPost]=useState<{postId:string;start:string;duration:string;reason:string}|null>(null);
 const suppressClickRef=useRef(false);const moveMutationRef=useRef(0);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(anchorDay,i)),[anchorDay]);
 const location=useMemo(()=>locations.find(x=>x.id===locationId)??locations[0]??null,[locations,locationId]);
 const timeZone=location?.timezone||KYIV_TZ;
 const today=dateKey(new Date(),timeZone);
 const isOverdue=(item:Appointment)=>!["COMPLETED","NO_SHOW","CANCELLED","RESERVE"].includes(item.status)&&+new Date(item.plannedEndAt)<Date.now();
 const isAttention=(item:Appointment)=>isOverdue(item)||["WAITING_PARTS_SELECTION","WAITING_APPROVAL","WAITING_PARTS","WAITING_PAYMENT","PAUSED"].includes(item.status)||(item.status==="COMPLETED"&&Number(item.payment.outstanding||0)>0);
 const load=useCallback(async(nextLocationId?:string)=>{setBusy(true);try{const selectedLocationId=nextLocationId??locationId;const zone=locations.find(x=>x.id===selectedLocationId)?.timezone||timeZone;const fromDay=anchorDay;const toDay=view==="day"?addDays(anchorDay,1):addDays(anchorDay,7);const params=new URLSearchParams({from:zonedDateTimeToDate(fromDay,"00:00",zone).toISOString(),to:zonedDateTimeToDate(toDay,"00:00",zone).toISOString()});if(selectedLocationId)params.set("locationId",selectedLocationId);const route=readCrmRoute();if(route.appointmentId)params.set("appointmentId",route.appointmentId);const response=await fetch(`/api/planner?${params}`,{cache:"no-store"});const raw=await response.json().catch(()=>null);const data=parsePlannerBoardPayload(raw);if(!response.ok||!data)throw new Error(plannerPayloadMessage(raw)||"Не вдалося завантажити План робіт.");setLocations(data.locations);setLocationId(data.activeLocationId||selectedLocationId||"");setAppointments(data.appointments);setMessage("План робіт синхронізовано з сервером.");}catch(error){setMessage(error instanceof Error?error.message:"План робіт недоступний.");}finally{setBusy(false);}},[anchorDay,locationId,locations,timeZone,view]);
 useEffect(()=>{void load();},[anchorDay,view]);useEffect(()=>{const timer=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(timer);},[load]);
 useEffect(()=>{const sync=()=>{const route=readCrmRoute();const nextView:ViewMode=route.scope==="week"?"week":"day";setView(nextView);if(route.date&&route.date!==anchorDay)setAnchorDay(route.date);setStatusFilter(isPlannerStatus(route.status)?route.status:"");if(route.appointmentId){const item=appointments.find(x=>x.id===route.appointmentId);if(item){const itemDay=displayDay(item,timeZone);if(itemDay!==anchorDay)setAnchorDay(itemDay);setSelected(item);}}else{setSelected(null);setEdit(null);}};sync();window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[appointments,anchorDay,timeZone]);
 const baseFiltered=useMemo(()=>{const q=search.trim().toLocaleLowerCase("uk-UA");return appointments.filter(x=>statusFilter?x.status===statusFilter:x.status!=="CANCELLED").filter(x=>!mechanicFilter||x.mechanicId===mechanicFilter).filter(x=>!postFilter||(postFilter==="__RECEPTION__"?!x.postId:x.postId===postFilter)).filter(x=>!q||[x.id,x.workOrderId,x.customerName,x.phone,x.vehicleLabel,x.plateNumber,x.problem].filter(Boolean).join(" ").toLocaleLowerCase("uk-UA").includes(q));},[appointments,statusFilter,mechanicFilter,postFilter,search]);
 const filtered=useMemo(()=>baseFiltered.filter(x=>quickFilter==="ALL"?true:quickFilter==="COMPLETED"?x.status==="COMPLETED":quickFilter==="IN_PROGRESS"?["DIAGNOSTICS","IN_REPAIR","WAITING_QC"].includes(x.status):quickFilter==="WAITING"?["ARRIVED","WAITING_PARTS_SELECTION","WAITING_CALCULATION","WAITING_APPROVAL","WAITING_PARTS","READY_FOR_REPAIR","READY_FOR_PICKUP","PAUSED"].includes(x.status):quickFilter==="OVERDUE"?isOverdue(x):isAttention(x)),[baseFiltered,quickFilter]);
 const dayAll=useMemo(()=>appointments.filter(x=>!["CANCELLED","RESERVE"].includes(x.status)&&displayDay(x,timeZone)===anchorDay),[appointments,timeZone,anchorDay]);
 const daySnapshot=useMemo(()=>{const completed=dayAll.filter(x=>x.status==="COMPLETED").length;const inProgress=dayAll.filter(x=>["DIAGNOSTICS","IN_REPAIR","WAITING_QC"].includes(x.status)).length;const waiting=dayAll.filter(x=>["ARRIVED","WAITING_PARTS_SELECTION","WAITING_CALCULATION","WAITING_APPROVAL","WAITING_PARTS","READY_FOR_REPAIR","READY_FOR_PICKUP","PAUSED"].includes(x.status)).length;const overdue=dayAll.filter(isOverdue).length;const attention=dayAll.filter(isAttention).length;const planned=dayAll.reduce((sum,x)=>sum+Number(x.payment.amount??x.estimatedAmount??0),0);const paid=dayAll.reduce((sum,x)=>sum+Number(x.payment.paid??0),0);return{total:dayAll.length,completed,inProgress,waiting,overdue,attention,planned,paid};},[dayAll]);
 function items(day:string){const source=view==="week"?appointments.filter(x=>x.status!=="CANCELLED"):filtered;return source.filter(x=>displayDay(x,timeZone)===day).sort((a,b)=>+new Date(displayStartAt(a))-(+new Date(displayStartAt(b))));}
 function color(postId:string|null){if(!postId||!location)return"#64748B";const index=location.posts.findIndex(x=>x.id===postId);if(index<0)return"#64748B";return colorFromPost(location.posts[index],index);}
 function openNewRequest(day=anchorDay,time="",postId=""){window.dispatchEvent(new CustomEvent("turbolev:open-new-request",{detail:{appointmentDate:day,appointmentTime:time,postId,source:"PLANNER"}}));}
 function routeParams(extra:Record<string,string>={}){return{...(statusFilter?{status:statusFilter}:{}),date:anchorDay,scope:view,...extra};}
 function chooseView(next:ViewMode){if(next==="week"){setQuickFilter("ALL");setStatusFilter("");setMechanicFilter("");setPostFilter("");setSearchDraft("");setSearch("");navigateCrm("Планувальник",{date:anchorDay,scope:"week"});return;}navigateCrm("Планувальник",{...(statusFilter?{status:statusFilter}:{}),date:anchorDay,scope:"day"});}
 function chooseStatus(value:string){setQuickFilter("ALL");navigateCrm("Планувальник",{...(isPlannerStatus(value)?{status:value}:{}),date:anchorDay,scope:view});}
 function goDay(day:string){setAnchorDay(day);navigateCrm("Планувальник",{...(view==="day"&&statusFilter?{status:statusFilter}:{}),date:day,scope:view});}
 function openDay(day:string){setAnchorDay(day);setView("day");navigateCrm("Планувальник",{...(statusFilter?{status:statusFilter}:{}),date:day,scope:"day"});}
 function openAppointment(item:Appointment){navigateCrm("Планувальник",routeParams({appointmentId:item.id}));}
 function closeEdit(){setDetailEdit(null);setDetailDraft(null);navigateCrm("Планувальник",routeParams());}
 function beginDetailEdit(section:DetailEditSection){if(!selected)return;const current=editState(selected,timeZone);setDetailEdit(section);setDetailDraft({...current,problem:selected.problem||""});}
 function cancelDetailEdit(){setDetailEdit(null);setDetailDraft(null);}
 function updateDetailDraft(patch:Partial<DetailDraft>){setDetailDraft(current=>current?{...current,...patch}:current);}
 async function saveDetailEdit(){if(!selected||!detailDraft||!detailEdit)return;let payload:Record<string,unknown>={};if(detailEdit==="POST"){payload={postId:detailDraft.postId||null};}else if(detailEdit==="MECHANIC"){payload={mechanicId:detailDraft.mechanicId||null};}else if(detailEdit==="DATETIME"){if(!detailDraft.date||!detailDraft.start){setMessage("Оберіть дату і час початку.");return;}const start=zonedDateTimeToDate(detailDraft.date,detailDraft.start,timeZone);const end=new Date(start.getTime()+Number(detailDraft.duration||60)*60000);payload={plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString()};}else{payload={problem:detailDraft.problem||null,comment:detailDraft.comment||null};}setSaving(true);const saved=await patch(selected.id,payload,"Запис оновлено.");setSaving(false);if(saved)cancelDetailEdit();}
 async function patch(id:string,payload:Record<string,unknown>,success:string):Promise<boolean>{try{const response=await fetch(`/api/planner/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {appointment?:Appointment;warning?:{message?:string}|null;message?:string};if(!response.ok)throw new Error(data.message||"Не вдалося змінити запис.");const updatedAppointment=data.appointment;if(updatedAppointment){setAppointments(current=>current.map(item=>item.id===updatedAppointment.id?{...item,...updatedAppointment}:item));setSelected(current=>current?.id===updatedAppointment.id?{...current,...updatedAppointment}:current);}setMessage(data.warning?.message?`${success} ⚠ ${data.warning.message}`:success);return true;}catch(error){setMessage(error instanceof Error?error.message:"Не вдалося змінити запис.");return false;}}
 async function resizeAppointment(item:Appointment,day:string,startTime:string,endTime:string){const start=zonedDateTimeToDate(day,startTime,timeZone);const end=zonedDateTimeToDate(day,endTime,timeZone);return patch(item.id,{plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString()},`Запис змінено: ${startTime}–${endTime}.`);}
 async function suggestAlternative(item:Appointment,targetDay:string,targetTime:string,durationMinutes:number,preferredPostId:string|null){
  if(!location)return;
  try{
   const params=new URLSearchParams({date:targetDay,locationId:location.id,durationMinutes:String(durationMinutes),excludeAppointmentId:item.id});
   const response=await fetch("/api/planner/availability?"+params.toString(),{cache:"no-store"});
   const data=await response.json() as {slots?:Array<{time:string;posts:Array<{id:string;name:string;available:boolean}>;mechanics:Array<{id:string;available:boolean}>}>};
   if(!response.ok||!data.slots)return;
   const targetMinutes=Number(targetTime.slice(0,2))*60+Number(targetTime.slice(3,5));
   for(const slot of data.slots){
    const slotMinutes=Number(slot.time.slice(0,2))*60+Number(slot.time.slice(3,5));
    if(slotMinutes<targetMinutes)continue;
    const mechanicOk=!item.mechanicId||slot.mechanics.some(m=>m.id===item.mechanicId&&m.available);
    if(!mechanicOk)continue;
    const same=preferredPostId?slot.posts.find(p=>p.id===preferredPostId&&p.available):null;
    const post=same||slot.posts.find(p=>p.available);
    if(post){setSuggestion({appointmentId:item.id,day:targetDay,time:slot.time,postId:post.id,postName:post.name,durationMinutes});setMessage("Є найближчий вільний варіант: "+post.name+", "+slot.time+".");return;}
   }
  }catch{}
 }
 async function moveAppointment(item:Appointment,targetDay:string,targetTime:string,postId:string|null,durationMinutes=duration(item)){
  const start=zonedDateTimeToDate(targetDay,targetTime,timeZone);const end=new Date(start.getTime()+durationMinutes*60000);
  const previous=appointments.find(candidate=>candidate.id===item.id)||item;
  const nextPost=postId?location?.posts.find(candidate=>candidate.id===postId)||previous.post||null:null;
  const nextAppointment={...previous,plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString(),postId,post:nextPost};
  const mutation=moveMutationRef.current+1;moveMutationRef.current=mutation;
  setAppointments(current=>current.map(candidate=>candidate.id===item.id?nextAppointment:candidate));
  setMessage("Зберігаю переміщення…");setSuggestion(null);
  const saved=await patch(item.id,{plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString(),postId},"Запис переміщено та збережено.");
  if(!saved&&moveMutationRef.current===mutation){setAppointments(current=>current.map(candidate=>candidate.id===previous.id?previous:candidate));void suggestAlternative(previous,targetDay,targetTime,durationMinutes,postId);}
 }
 async function drop(event:DragEvent,targetDay:string){event.preventDefault();const id=event.dataTransfer.getData("text/planner-appointment");const item=appointments.find(x=>x.id===id);if(!item)return;await moveAppointment(item,targetDay,clock(item.plannedStartAt,timeZone),item.postId||null);}
 async function saveEdit(){if(!edit)return;const requiresSlot=!["NO_SHOW","CANCELLED","COMPLETED","RESERVE"].includes(edit.status);if(requiresSlot&&(!edit.start||!edit.postId||!edit.mechanicId)){setMessage("Оберіть доступний час, пост і механіка.");return;}setSaving(true);const start=zonedDateTimeToDate(edit.date,edit.start||"09:00",timeZone);const end=new Date(start.getTime()+Number(edit.duration||60)*60000);await patch(edit.id,{status:edit.status,postId:edit.postId||null,mechanicId:edit.mechanicId||null,plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString(),comment:edit.comment||null},"Запис оновлено.");setSaving(false);closeEdit();}
 async function markArrived(){if(!selected)return;setSaving(true);await patch(selected.id,{status:"ARRIVED"},"Автомобіль відмічено як прибулий.");setSaving(false);}
 function openSelectedWork(){if(!selected)return;if(selected.workOrderId){navigateCrm("Комерційна пропозиція",{workOrderId:selected.workOrderId,workOrderTab:"works"});return;}if(selected.vehicleId){navigateCrm("Авто",{vehicleId:selected.vehicleId,vehiclePage:"diagnostic-card"});return;}setMessage("Для цього запису ще немає робочого процесу.");}
 function openSelectedParts(){if(!selected)return;if(selected.workOrderId){navigateCrm("Комерційна пропозиція",{workOrderId:selected.workOrderId,workOrderTab:"parts"});return;}navigateCrm("Підбір запчастин",{...(selected.vehicleId?{vehicleId:selected.vehicleId}:{}),...(selected.plateNumber?{plate:selected.plateNumber}:{})});}
 function openSelectedPayment(){if(!selected)return;navigateCrm("Оплати",{...(selected.workOrderId?{workOrderId:selected.workOrderId}:{}),...(selected.vehicleId?{vehicleId:selected.vehicleId}:{})});}
 function openSelectedCompleteFlow(){if(!selected)return;if(selected.workOrderId){navigateCrm("Комерційна пропозиція",{workOrderId:selected.workOrderId,workOrderTab:"qc"});return;}openSelectedWork();}
 async function cancelSelected(){if(!selected||!window.confirm("Скасувати цей запис? Цю дію буде зафіксовано в CRM."))return;setSaving(true);try{const response=await fetch("/api/planner/"+selected.id,{method:"DELETE"});const data=await response.json().catch(()=>null) as {message?:string}|null;if(!response.ok)throw new Error(data?.message||"Не вдалося скасувати запис.");setMessage("Запис скасовано.");closeEdit();await load();}catch(error){setMessage(error instanceof Error?error.message:"Не вдалося скасувати запис.");}finally{setSaving(false);}}
 function openPostMenu(postId:string){if(!location)return;const now=new Date();const parts=new Intl.DateTimeFormat("en-GB",{timeZone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(now);const hours=Number(parts.find(p=>p.type==="hour")?.value||"0");const minutes=Number(parts.find(p=>p.type==="minute")?.value||"0");let minute=anchorDay===today?hours*60+minutes:location.openMinute;minute=Math.max(location.openMinute,Math.ceil(minute/30)*30);minute=Math.min(minute,Math.max(location.openMinute,location.closeMinute-30));setBlockPost({postId,start:pad(Math.floor(minute/60))+":"+pad(minute%60),duration:"60",reason:"Пост недоступний"});}
 async function createPostBlock(){if(!blockPost||!location)return;setSaving(true);try{const start=zonedDateTimeToDate(anchorDay,blockPost.start,timeZone);const end=new Date(start.getTime()+Number(blockPost.duration)*60000);const post=location.posts.find(p=>p.id===blockPost.postId);const response=await fetch("/api/planner",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locationId:location.id,postId:blockPost.postId,mechanicId:null,status:"RESERVE",customerName:"Блокування поста",vehicleLabel:"Пост недоступний",problem:blockPost.reason||"Пост недоступний",comment:(post?.name||"Пост")+" · службове блокування ресурсу",source:"PLANNER_RESOURCE_BLOCK",priority:10,plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString()})});const data=await response.json().catch(()=>null) as {message?:string}|null;if(!response.ok)throw new Error(data?.message||"Не вдалося заблокувати пост.");setMessage((post?.name||"Пост")+" заблоковано на "+blockPost.duration+" хв.");setBlockPost(null);await load();}catch(error){setMessage(error instanceof Error?error.message:"Не вдалося заблокувати пост.");}finally{setSaving(false);}}
 return <div className={layoutStyles.calendarRoot}><div className={styles.page} data-planner-page="true">
  <CrmPageHeader
    eyebrow={`TURBO LEV · СТО ${(location?.name||"ГЛЕВАХА").toUpperCase()}`}
    title="Планувальник"
    description={view==="day" ? "День по постах — весь робочий день на одному екрані." : "Тижневий огляд завантаження станції."}
    actions={<div className={styles.headerActionCluster}>
      <div className={layoutStyles.viewToggle} aria-label="Режим перегляду">
        <button type="button" className={`${layoutStyles.viewButton} ${view==="day"?layoutStyles.viewActive:""}`} onClick={()=>chooseView("day")}>День · пости</button>
        <button type="button" className={`${layoutStyles.viewButton} ${view==="week"?layoutStyles.viewActive:""}`} onClick={()=>chooseView("week")}>Тиждень</button>
      </div>
      <button type="button" className={styles.secondary} onClick={()=>goDay(today)} disabled={anchorDay===today}>Сьогодні</button>
      <button type="button" className={styles.primary} onClick={()=>openNewRequest(anchorDay)}>+ Нова заявка</button>
    </div>}
  />
  {view==="day"&&<section className={styles.toolbar}>
    {view==="day"&&<div className={styles.toolbarDate}>
      <button type="button" aria-label="Попередній день" onClick={()=>goDay(addDays(anchorDay,-1))}>‹</button>
      <label className={styles.calendarControl} title="Відкрити календар"><span>Дата</span><strong>{longDay(anchorDay)}</strong><input type="date" value={anchorDay} onClick={e=>{const input=e.currentTarget as HTMLInputElement&{showPicker?:()=>void};try{input.showPicker?.();}catch{input.focus();}}} onChange={e=>e.target.value&&goDay(e.target.value)} aria-label="Обрати дату в календарі"/></label>
      <button type="button" aria-label="Наступний день" onClick={()=>goDay(addDays(anchorDay,1))}>›</button>
    </div>}
    {locations.length>1&&<label><span>Локація</span><select value={locationId} onChange={e=>{setPostFilter("");void load(e.target.value)}}>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
    <label><span>Статус запису</span><select value={statusFilter} onChange={e=>chooseStatus(e.target.value)}><option value="">Усі записи</option>{PLANNER_STATUS_OPTIONS.map(x=><option key={x} value={x}>{STATUS_META[x].label}</option>)}</select></label>
    <label><span>Виконавець</span><select value={mechanicFilter} onChange={e=>setMechanicFilter(e.target.value)}><option value="">Усі виконавці</option>{location?.mechanics.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
    <label><span>Пост</span><select value={postFilter} onChange={e=>setPostFilter(e.target.value)}><option value="">Усі пости</option>{location?.posts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}<option value="__RECEPTION__">Без поста / зона приймання</option></select></label>
    <div className={styles.toolbarEnd}><div className={styles.searchBox}><span>⌕</span><input value={searchDraft} onChange={e=>setSearchDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setSearch(searchDraft)} placeholder="Пошук: клієнт, авто, номер..."/><button onClick={()=>setSearch(searchDraft)}>Пошук</button></div></div>
  </section>}
  {view==="day"&&<section className={styles.kpiBar} aria-label="Оперативні показники">
    <button type="button" className={quickFilter==="ALL"?styles.kpiActive:""} onClick={()=>setQuickFilter("ALL")}><i>▣</i><span><b>{daySnapshot.total} авто</b><small>на сьогодні</small></span></button>
    <button type="button" className={quickFilter==="COMPLETED"?styles.kpiActive:""} onClick={()=>setQuickFilter("COMPLETED")}><i className={styles.kpiGreen}>✓</i><span><b>{daySnapshot.completed} завершено</b><small>видано / готово</small></span></button>
    <button type="button" className={quickFilter==="IN_PROGRESS"?styles.kpiActive:""} onClick={()=>setQuickFilter("IN_PROGRESS")}><i className={styles.kpiBlue}>▶</i><span><b>{daySnapshot.inProgress} в роботі</b><small>активний процес</small></span></button>
    <button type="button" className={quickFilter==="WAITING"?styles.kpiActive:""} onClick={()=>setQuickFilter("WAITING")}><i className={styles.kpiAmber}>◷</i><span><b>{daySnapshot.waiting} очікує</b><small>клієнта / деталі</small></span></button>
    <button type="button" className={quickFilter==="OVERDUE"?styles.kpiActive:""} onClick={()=>setQuickFilter("OVERDUE")}><i className={styles.kpiRed}>!</i><span><b>{daySnapshot.overdue} прострочено</b><small>потребує реакції</small></span></button>
    <button type="button" onClick={()=>navigateCrm("Оплати",{date:anchorDay})}><i className={styles.kpiGreen}>₴</i><span><b>{amount(daySnapshot.planned)}</b><small>заплановано</small></span></button>
    <button type="button" onClick={()=>navigateCrm("Оплати",{date:anchorDay})}><i className={styles.kpiGreen}>✓</i><span><b>{amount(daySnapshot.paid)}</b><small>оплачено</small></span></button>
    <button type="button" className={`${styles.kpiAttention} ${quickFilter==="ATTENTION"?styles.kpiActive:""}`} onClick={()=>setQuickFilter("ATTENTION")}><i>⚠</i><span><b>{daySnapshot.attention} потребують уваги</b><small>прострочення / блокери</small></span></button>
  </section>}
  {view==="week"&&<div className={styles.rangeNav}><button onClick={()=>goDay(addDays(anchorDay,-7))}>‹ Попередній тиждень</button><strong>{`${formatDate(anchorDay)} — ${formatDate(addDays(anchorDay,6))}`}</strong><button onClick={()=>goDay(addDays(anchorDay,7))}>Наступний тиждень ›</button></div>}
  <span className={styles.visuallyHidden} aria-live="polite">{busy?"Оновлюю…":message}</span>{view==="day"&&<div className={styles.systemBanner}><span>{busy?"Оновлюю…":message}</span>{suggestion&&<button type="button" onClick={()=>{const item=appointments.find(x=>x.id===suggestion.appointmentId);if(item)void moveAppointment(item,suggestion.day,suggestion.time,suggestion.postId,suggestion.durationMinutes);}}>Перенести: {suggestion.postName} · {suggestion.time}</button>}{suggestion&&<button type="button" className={styles.bannerDismiss} onClick={()=>setSuggestion(null)} aria-label="Закрити підказку">×</button>}</div>}
  {view==="day"&&location?<div className={`${styles.operationalLayout} ${selected?styles.operationalLayoutWithDrawer:""}`}><div className={styles.plannerCanvas}><PlannerDayView day={anchorDay} location={location} appointments={filtered} selectedAppointmentId={selected?.id||null} onOpen={openAppointment} onCreate={(day,time,postId)=>openNewRequest(day,time,postId)} onResize={resizeAppointment} onMove={moveAppointment} onMetrics={setDayMetrics} onPostMenu={openPostMenu} showMetrics={false}/></div>{selected&&<PlannerDetailDrawer appointment={selected} location={location} timeZone={timeZone} busy={saving} onClose={closeEdit} onArrive={()=>void markArrived()} onEdit={()=>{setEdit(editState(selected,timeZone));setSelected(null)}} onOpenVehicle={()=>selected.vehicleId&&navigateCrm("Авто",{vehicleId:selected.vehicleId})} onOpenWork={openSelectedWork} onOpenParts={openSelectedParts} onOpenPayment={openSelectedPayment} onCompleteFlow={openSelectedCompleteFlow} onCancel={()=>void cancelSelected()}/>}</div>:view==="week"?<section className={styles.weekBoard}>{days.map(day=><article key={day} className={`${styles.dayColumn} ${day===today?styles.todayColumn:""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>void drop(e,day)}><button className={styles.dayHead} onClick={()=>openDay(day)} title="Відкрити денний планувальник"><span><b>{dayName(day)}</b><small>{new Date(`${day}T12:00:00Z`).getUTCDate()}</small></span><strong>{items(day).length}</strong></button><div className={styles.dayBody}>{items(day).length?items(day).map(item=><button key={item.id} className={styles.workCard} style={{"--post-color":color(item.postId)} as CSSProperties} draggable={!(["COMPLETED","NO_SHOW","CANCELLED","RESERVE"] as Status[]).includes(item.status)&&!isActualWalkIn(item)} onDragStart={e=>{suppressClickRef.current=true;e.dataTransfer.setData("text/planner-appointment",item.id);e.dataTransfer.effectAllowed="move"}} onDragEnd={()=>{window.setTimeout(()=>{suppressClickRef.current=false},0)}} onClick={()=>{if(!suppressClickRef.current)openAppointment(item)}}><div className={styles.cardTop}><span>{clock(displayStartAt(item),timeZone)}–{clock(displayEndAt(item),timeZone)}</span><em className={`${styles.badge} ${styles[`tone_${STATUS_META[item.status].tone}`]}`}>{STATUS_META[item.status].label}</em></div><strong>{item.plateNumber||"БЕЗ НОМЕРА"}</strong><b>{item.vehicleLabel||"Автомобіль"}</b>{item.problem&&<small>{item.problem}</small>}<footer><span>{item.post?.name||"Зона приймання"}</span><span>{item.mechanic?.name||"Без майстра"}</span>{amount(item.estimatedAmount)&&<b>{amount(item.estimatedAmount)}</b>}</footer></button>):<div className={styles.free}>Вільно</div>}</div><button className={styles.add} onClick={()=>openNewRequest(day)}>+ <span>Додати</span></button></article>)}</section>:null}
  {view==="day"&&<section className={styles.bottomInsights}>
    <details><summary><span>⛓</span><strong>Шлях клієнта</strong><small>{daySnapshot.total} авто в контурі</small></summary><div className={styles.journey}><span>Записано <b>{dayAll.filter(x=>x.status==="BOOKED").length}</b></span><i>→</i><span>Прибуло <b>{dayAll.filter(x=>x.status==="ARRIVED").length}</b></span><i>→</i><span>В роботі <b>{daySnapshot.inProgress}</b></span><i>→</i><span>Очікує <b>{daySnapshot.waiting}</b></span><i>→</i><span>Завершено <b>{daySnapshot.completed}</b></span></div></details>
    <details><summary><span>▥</span><strong>Операційний пульс</strong><small>{daySnapshot.attention?daySnapshot.attention+" потребують уваги":"Критичних відхилень немає"}</small></summary><div className={styles.pulse}><span><small>В роботі</small><b>{daySnapshot.inProgress}</b></span><span><small>Прострочено</small><b className={styles.pulseDanger}>{daySnapshot.overdue}</b></span><span><small>План дня</small><b>{amount(daySnapshot.planned)}</b></span><span><small>Оплачено</small><b>{amount(daySnapshot.paid)}</b></span><span><small>Вільних слотів ×30 хв</small><b>{dayMetrics?.freeSlots??"—"}</b></span></div></details>
  </section>}
  {view==="day"&&<p className={styles.rule}>Планувальник керує записом: Записаний → Приїхав / Не приїхав / Скасований / Резерв. Діагностика й ремонт відображаються з профільних процесів.</p>}
  {blockPost&&location&&<div className={styles.modalBackdrop} onMouseDown={()=>setBlockPost(null)}><section className={styles.resourceBlockModal} onMouseDown={e=>e.stopPropagation()}>
    <header><div><p>РЕСУРС ПОСТА</p><h2>Заблокувати {location.posts.find(p=>p.id===blockPost.postId)?.name||"пост"}</h2><span>Блокування створюється як службовий резерв і враховується в конфліктах Планувальника.</span></div><button type="button" onClick={()=>setBlockPost(null)}>×</button></header>
    <div className={styles.resourceBlockForm}>
      <label><span>Початок</span><input type="time" step={1800} value={blockPost.start} onChange={e=>setBlockPost({...blockPost,start:e.target.value})}/></label>
      <label><span>Тривалість</span><select value={blockPost.duration} onChange={e=>setBlockPost({...blockPost,duration:e.target.value})}>{[30,60,90,120,180,240,360,480].map(v=><option key={v} value={v}>{v<60?v+" хв":v/60+" год"}</option>)}</select></label>
      <label className={styles.resourceBlockReason}><span>Причина</span><input value={blockPost.reason} onChange={e=>setBlockPost({...blockPost,reason:e.target.value})} placeholder="Ремонт підйомника, технічне обслуговування..."/></label>
    </div>
    <footer><button type="button" className={styles.secondary} onClick={()=>setBlockPost(null)}>Скасувати</button><button type="button" className={styles.primary} disabled={saving} onClick={()=>void createPostBlock()}>{saving?"Зберігаю…":"Заблокувати пост"}</button></footer>
  </section></div>}
  {edit&&location&&<div className={styles.modalBackdrop} onMouseDown={closeEdit}><section className={styles.modal} onMouseDown={e=>e.stopPropagation()}><div className={styles.modalHead}><div><p>ПЕРЕНЕСЕННЯ / РЕДАГУВАННЯ</p><h2>{appointments.find(x=>x.id===edit.id)?.plateNumber||"Запис"}</h2></div><button onClick={closeEdit}>×</button></div><div className={styles.formGrid}><label><span>Дата</span><input type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value,start:"",postId:"",mechanicId:""})}/></label><label><span>Тривалість</span><select value={edit.duration} onChange={e=>setEdit({...edit,duration:e.target.value,start:"",postId:"",mechanicId:""})}>{[30,60,90,120,180,240,360,480].map(x=><option key={x} value={x}>{x<60?`${x} хв`:`${x/60} год`}</option>)}</select></label>{isPlannerStatus(edit.status)?<label><span>Статус запису</span><select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value as Status})}>{PLANNER_STATUS_OPTIONS.map(x=><option key={x} value={x}>{STATUS_META[x].label}</option>)}</select></label>:<label><span>Сервісний етап</span><strong>{STATUS_META[edit.status].label}</strong><small>Керується у відповідному сервісному процесі.</small></label>}</div><label className={styles.editComment}><span>Коментар для СТО</span><textarea rows={2} value={edit.comment} onChange={e=>setEdit({...edit,comment:e.target.value})} placeholder="Додайте уточнення до запису"/></label><AvailabilityPicker date={edit.date} locationId={location.id} durationMinutes={Number(edit.duration)||60} excludeAppointmentId={edit.id} selectedTime={edit.start} selectedPostId={edit.postId} selectedMechanicId={edit.mechanicId} onChange={selection=>setEdit({...edit,start:selection.time,postId:selection.postId,mechanicId:selection.mechanicId})}/><div className={styles.modalFoot}><button className={styles.secondary} onClick={closeEdit}>Закрити</button><button className={styles.primary} disabled={saving} onClick={()=>void saveEdit()}>{saving?"Зберігаю…":"Зберегти"}</button></div></section></div>}
 </div></div>;
}
