"use client";

import { useCallback, useEffect, useMemo, useState, type CSSProperties, type DragEvent } from "react";
import { zonedDateTimeToDate } from "@/src/lib/zoned-time";
import { AvailabilityPicker } from "./availability-picker";
import { navigateCrm, readCrmRoute } from "./crm-route";
import { PlannerDayView } from "./planner-day-view";
import styles from "./planner-v2.module.css";

type Status = "BOOKED"|"ARRIVED"|"DIAGNOSTICS"|"WAITING_PARTS_SELECTION"|"WAITING_CALCULATION"|"WAITING_APPROVAL"|"WAITING_PARTS"|"READY_FOR_REPAIR"|"IN_REPAIR"|"WAITING_QC"|"READY_FOR_PICKUP"|"COMPLETED"|"WARRANTY"|"PAUSED"|"NO_SHOW"|"CANCELLED"|"RESERVE";
type ViewMode="day"|"week";
type Post={id:string;name:string;sortOrder:number;capabilities:string[]};
type Mechanic={id:string;name:string;sortOrder:number};
type Location={id:string;name:string;timezone:string;openMinute:number;closeMinute:number;posts:Post[];mechanics:Mechanic[]};
type Appointment={id:string;locationId:string;postId:string|null;mechanicId:string|null;status:Status;workOrderId?:string|null;customerName:string|null;phone:string|null;vehicleLabel:string|null;plateNumber:string|null;problem:string|null;comment:string|null;source:string|null;estimatedAmount:string|number|null;priority:number;plannedStartAt:string;plannedEndAt:string;actualArrivalAt:string|null;actualStartAt:string|null;actualEndAt:string|null;partsEtaAt:string|null;post?:Post|null;mechanic?:Mechanic|null};
type BoardResponse={status:string;locations:Location[];activeLocationId:string|null;appointments:Appointment[];message?:string};
type EditState={id:string;date:string;status:Status;postId:string;mechanicId:string;start:string;duration:string};

const KYIV_TZ="Europe/Kyiv";
const STATUS_META:Record<Status,{label:string;tone:string}>={BOOKED:{label:"Записаний",tone:"blue"},ARRIVED:{label:"Приїхав",tone:"green"},DIAGNOSTICS:{label:"Діагностика",tone:"violet"},WAITING_PARTS_SELECTION:{label:"Підбір деталей",tone:"amber"},WAITING_CALCULATION:{label:"Калькуляція",tone:"amber"},WAITING_APPROVAL:{label:"Погодження",tone:"orange"},WAITING_PARTS:{label:"Очікує деталі",tone:"amber"},READY_FOR_REPAIR:{label:"Готовий до ремонту",tone:"green"},IN_REPAIR:{label:"У ремонті",tone:"orange"},WAITING_QC:{label:"Контроль якості",tone:"cyan"},READY_FOR_PICKUP:{label:"Готовий до видачі",tone:"green"},COMPLETED:{label:"Виданий",tone:"gray"},WARRANTY:{label:"Гарантія",tone:"pink"},PAUSED:{label:"Пауза",tone:"gray"},NO_SHOW:{label:"No-show",tone:"red"},CANCELLED:{label:"Скасований",tone:"gray"},RESERVE:{label:"Резерв",tone:"gray"}};
const STATUS_OPTIONS=Object.keys(STATUS_META) as Status[];
const FALLBACK_COLORS=["#FF5A1F","#2F80ED","#7C3AED","#16A34A","#D97706","#0891B2","#DB2777"];
const pad=(n:number)=>String(n).padStart(2,"0");
function dateKey(date=new Date(),timeZone=KYIV_TZ){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${map.year}-${map.month}-${map.day}`;}
function addDays(day:string,count:number){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+count);return `${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`;}
function formatDate(day:string){return new Intl.DateTimeFormat("uk-UA",{timeZone:"UTC",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${day}T12:00:00Z`));}
function dayName(day:string){return new Intl.DateTimeFormat("uk-UA",{timeZone:"UTC",weekday:"short"}).format(new Date(`${day}T12:00:00Z`)).replace(".","");}
function longDay(day:string){return new Intl.DateTimeFormat("uk-UA",{timeZone:"UTC",weekday:"long",day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${day}T12:00:00Z`));}
function clock(iso:string,timeZone=KYIV_TZ){return new Intl.DateTimeFormat("uk-UA",{timeZone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(iso));}
function duration(item:Appointment){return Math.max(30,Math.round((+new Date(item.plannedEndAt)-+new Date(item.plannedStartAt))/60000));}
function amount(value:Appointment["estimatedAmount"]){const n=Number(value);return value!=null&&value!==""&&Number.isFinite(n)?new Intl.NumberFormat("uk-UA",{style:"currency",currency:"UAH",maximumFractionDigits:0}).format(n):"";}
function colorFromPost(post:Post,index:number){return post.capabilities.find(x=>x.startsWith("COLOR:"))?.slice(6)||FALLBACK_COLORS[index%FALLBACK_COLORS.length];}
function postType(post:Post){const type=post.capabilities.find(x=>x.startsWith("TYPE:"))?.slice(5);return type==="PIT"?"Яма":type==="ALIGNMENT"?"Розвал-сходження":type==="NO_LIFT"?"Без підйомника":"Підйомник";}
function isStatus(value:string|undefined):value is Status{return Boolean(value&&Object.prototype.hasOwnProperty.call(STATUS_META,value));}
function editState(item:Appointment,timeZone:string):EditState{return{id:item.id,date:dateKey(new Date(item.plannedStartAt),timeZone),status:item.status,postId:item.postId||"",mechanicId:item.mechanicId||"",start:clock(item.plannedStartAt,timeZone),duration:String(duration(item))};}

export function PlannerV2(){
 const [anchorDay,setAnchorDay]=useState(()=>dateKey());const [view,setView]=useState<ViewMode>("day");const [locations,setLocations]=useState<Location[]>([]);const [locationId,setLocationId]=useState("");const [appointments,setAppointments]=useState<Appointment[]>([]);const [statusFilter,setStatusFilter]=useState("");const [mechanicFilter,setMechanicFilter]=useState("");const [postFilter,setPostFilter]=useState("");const [searchDraft,setSearchDraft]=useState("");const [search,setSearch]=useState("");const [message,setMessage]=useState("План робіт готовий.");const [busy,setBusy]=useState(false);const [edit,setEdit]=useState<EditState|null>(null);const [saving,setSaving]=useState(false);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(anchorDay,i)),[anchorDay]);
 const location=useMemo(()=>locations.find(x=>x.id===locationId)??locations[0]??null,[locations,locationId]);
 const timeZone=location?.timezone||KYIV_TZ;
 const today=dateKey(new Date(),timeZone);
 const load=useCallback(async(nextLocationId?:string)=>{setBusy(true);try{const selectedLocationId=nextLocationId??locationId;const zone=locations.find(x=>x.id===selectedLocationId)?.timezone||timeZone;const fromDay=anchorDay;const toDay=view==="day"?addDays(anchorDay,1):addDays(anchorDay,7);const params=new URLSearchParams({from:zonedDateTimeToDate(fromDay,"00:00",zone).toISOString(),to:zonedDateTimeToDate(toDay,"00:00",zone).toISOString()});if(selectedLocationId)params.set("locationId",selectedLocationId);const response=await fetch(`/api/planner?${params}`,{cache:"no-store"});const data=await response.json() as BoardResponse;if(!response.ok)throw new Error(data.message||"Не вдалося завантажити План робіт.");setLocations(data.locations||[]);setLocationId(data.activeLocationId||selectedLocationId||"");setAppointments(data.appointments||[]);setMessage("План робіт синхронізовано з сервером.");}catch(error){setMessage(error instanceof Error?error.message:"План робіт недоступний.");}finally{setBusy(false);}},[anchorDay,locationId,locations,timeZone,view]);
 useEffect(()=>{void load();},[anchorDay,view]);useEffect(()=>{const timer=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(timer);},[load]);
 useEffect(()=>{const sync=()=>{const route=readCrmRoute();const nextView:ViewMode=route.scope==="week"?"week":"day";setView(nextView);if(route.date&&route.date!==anchorDay)setAnchorDay(route.date);setStatusFilter(isStatus(route.status)?route.status:"");if(route.appointmentId){const item=appointments.find(x=>x.id===route.appointmentId);if(item){const itemDay=dateKey(new Date(item.plannedStartAt),timeZone);if(itemDay!==anchorDay)setAnchorDay(itemDay);setEdit(editState(item,timeZone));}}else setEdit(null);};sync();window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[appointments,anchorDay,timeZone]);
 const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase("uk-UA");return appointments.filter(x=>x.status!=="CANCELLED").filter(x=>!statusFilter||x.status===statusFilter).filter(x=>!mechanicFilter||x.mechanicId===mechanicFilter).filter(x=>!postFilter||(postFilter==="__RECEPTION__"?!x.postId:x.postId===postFilter)).filter(x=>!q||[x.id,x.workOrderId,x.customerName,x.phone,x.vehicleLabel,x.plateNumber,x.problem].filter(Boolean).join(" ").toLocaleLowerCase("uk-UA").includes(q));},[appointments,statusFilter,mechanicFilter,postFilter,search]);
 function items(day:string){return filtered.filter(x=>dateKey(new Date(x.plannedStartAt),timeZone)===day).sort((a,b)=>+new Date(a.plannedStartAt)-+new Date(b.plannedStartAt));}
 function color(postId:string|null){if(!postId||!location)return"#64748B";const index=location.posts.findIndex(x=>x.id===postId);if(index<0)return"#64748B";return colorFromPost(location.posts[index],index);}
 function openNewRequest(day=anchorDay,time=""){window.dispatchEvent(new CustomEvent("turbolev:open-new-request",{detail:{appointmentDate:day,appointmentTime:time,source:"PLANNER"}}));}
 function routeParams(extra:Record<string,string>={}){return{...(statusFilter?{status:statusFilter}:{}),date:anchorDay,scope:view,...extra};}
 function chooseView(next:ViewMode){navigateCrm("Планувальник",{...(statusFilter?{status:statusFilter}:{}),date:anchorDay,scope:next});}
 function chooseStatus(value:string){navigateCrm("Планувальник",{...(isStatus(value)?{status:value}:{}),date:anchorDay,scope:view});}
 function goDay(day:string){setAnchorDay(day);navigateCrm("Планувальник",{...(statusFilter?{status:statusFilter}:{}),date:day,scope:view});}
 function openDay(day:string){setAnchorDay(day);setView("day");navigateCrm("Планувальник",{...(statusFilter?{status:statusFilter}:{}),date:day,scope:"day"});}
 function openAppointment(item:Appointment){navigateCrm("Планувальник",routeParams({appointmentId:item.id}));}
 function closeEdit(){navigateCrm("Планувальник",routeParams());}
 async function patch(id:string,payload:Record<string,unknown>,success:string){try{const response=await fetch(`/api/planner/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||"Не вдалося змінити наряд.");setMessage(data.warning?.message?`${success} ⚠ ${data.warning.message}`:success);await load();}catch(error){setMessage(error instanceof Error?error.message:"Не вдалося змінити наряд.");}}
 async function drop(event:DragEvent,targetDay:string){event.preventDefault();const id=event.dataTransfer.getData("text/planner-appointment");const item=appointments.find(x=>x.id===id);if(!item)return;const start=zonedDateTimeToDate(targetDay,clock(item.plannedStartAt,timeZone),timeZone);const end=new Date(start.getTime()+duration(item)*60000);await patch(id,{plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString()},`Наряд перенесено на ${formatDate(targetDay)}.`);}
 async function saveEdit(){if(!edit)return;const requiresSlot=!["NO_SHOW","CANCELLED","COMPLETED"].includes(edit.status);if(requiresSlot&&(!edit.start||!edit.postId||!edit.mechanicId)){setMessage("Оберіть доступний час, пост і майстра.");return;}setSaving(true);const start=zonedDateTimeToDate(edit.date,edit.start||"09:00",timeZone);const end=new Date(start.getTime()+Number(edit.duration||60)*60000);await patch(edit.id,{status:edit.status,postId:edit.postId||null,mechanicId:edit.mechanicId||null,plannedStartAt:start.toISOString(),plannedEndAt:end.toISOString()},"Наряд оновлено.");setSaving(false);closeEdit();}
 return <div className={styles.page}>
  <header className={styles.header}><div><p>TURBO LEV / СТО {(location?.name||"ГЛЕВАХА").toUpperCase()}</p><div className={styles.titleLine}><h1>План робіт</h1>{view==="day"&&<strong className={styles.activeDate}>{longDay(anchorDay)}</strong>}</div><span>{view==="day"?"День по постах · весь робочий день на одному екрані":"Тижневий огляд завантаження станції"}</span></div><div className={styles.headerActions}><button className={styles.secondary} onClick={()=>goDay(today)} disabled={anchorDay===today}>Сьогодні</button><button className={styles.primary} onClick={()=>openNewRequest(anchorDay)}>+ Нова заявка</button></div></header>
  <div className={styles.viewToggle}><button type="button" className={view==="day"?styles.viewActive:""} onClick={()=>chooseView("day")}>День · пости</button><button type="button" className={view==="week"?styles.viewActive:""} onClick={()=>chooseView("week")}>Тиждень</button></div>
  <section className={styles.toolbar}>{locations.length>1&&<label><span>Локація</span><select value={locationId} onChange={e=>{setPostFilter("");void load(e.target.value)}}>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<label><span>Статус</span><select value={statusFilter} onChange={e=>chooseStatus(e.target.value)}><option value="">Усі статуси</option>{STATUS_OPTIONS.filter(x=>x!=="CANCELLED").map(x=><option key={x} value={x}>{STATUS_META[x].label}</option>)}</select></label><label><span>Виконавець</span><select value={mechanicFilter} onChange={e=>setMechanicFilter(e.target.value)}><option value="">Усі виконавці</option>{location?.mechanics.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Пост</span><select value={postFilter} onChange={e=>setPostFilter(e.target.value)}><option value="">Усі пости</option>{location?.posts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}<option value="__RECEPTION__">Без поста / зона приймання</option></select></label><div className={styles.searchBox}><span>⌕</span><input value={searchDraft} onChange={e=>setSearchDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setSearch(searchDraft)} placeholder="Наряд, клієнт, авто, держномер або VIN..."/><button onClick={()=>setSearch(searchDraft)}>Пошук</button></div></section>
  {view==="day"?<div className={styles.dayRangeNav}><button aria-label="Попередній день" onClick={()=>goDay(addDays(anchorDay,-1))}>‹</button><label className={styles.calendarControl} title="Відкрити календар"><span>{longDay(anchorDay)}</span><input type="date" value={anchorDay} onChange={e=>e.target.value&&goDay(e.target.value)} aria-label="Обрати дату в календарі"/></label><button aria-label="Наступний день" onClick={()=>goDay(addDays(anchorDay,1))}>›</button></div>:<div className={styles.rangeNav}><button onClick={()=>goDay(addDays(anchorDay,-7))}>‹ Попередній тиждень</button><strong>{`${formatDate(anchorDay)} — ${formatDate(addDays(anchorDay,6))}`}</strong><button onClick={()=>goDay(addDays(anchorDay,7))}>Наступний тиждень ›</button></div>}
  {view==="week"&&<div className={styles.resourceLegend}>{location?.posts.map((post,index)=><div key={post.id}><i style={{background:colorFromPost(post,index)}}/><strong>{post.name}</strong><span>{postType(post)}</span></div>)}<div><i style={{background:"#64748B"}}/><strong>Зона приймання</strong><span>Без поста</span></div></div>}
  <div className={styles.systemMessage}>{busy?"Оновлюю…":message}</div>
  {view==="day"&&location?<PlannerDayView day={anchorDay} location={location} appointments={filtered} onOpen={openAppointment} onCreate={(day,time)=>openNewRequest(day,time)}/>:view==="week"?<section className={styles.weekBoard}>{days.map(day=><article key={day} className={`${styles.dayColumn} ${day===today?styles.todayColumn:""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>void drop(e,day)}><button className={styles.dayHead} onClick={()=>openDay(day)} title="Відкрити денний планувальник"><span><b>{dayName(day)}</b><small>{new Date(`${day}T12:00:00Z`).getUTCDate()}</small></span><strong>{items(day).length}</strong></button><div className={styles.dayBody}>{items(day).length?items(day).map(item=><button key={item.id} className={styles.workCard} style={{"--post-color":color(item.postId)} as CSSProperties} draggable={!(["COMPLETED","NO_SHOW"] as Status[]).includes(item.status)} onDragStart={e=>{e.dataTransfer.setData("text/planner-appointment",item.id);e.dataTransfer.effectAllowed="move"}} onClick={()=>openAppointment(item)}><div className={styles.cardTop}><span>{clock(item.plannedStartAt,timeZone)}–{clock(item.plannedEndAt,timeZone)}</span><em className={`${styles.badge} ${styles[`tone_${STATUS_META[item.status].tone}`]}`}>{STATUS_META[item.status].label}</em></div><strong>{item.plateNumber||"БЕЗ НОМЕРА"}</strong><b>{item.vehicleLabel||"Автомобіль"}</b>{item.customerName&&<span>{item.customerName}</span>}{item.problem&&<small>{item.problem}</small>}<footer><span>{item.post?.name||"Зона приймання"}</span><span>{item.mechanic?.name||"Без майстра"}</span>{amount(item.estimatedAmount)&&<b>{amount(item.estimatedAmount)}</b>}</footer></button>):<div className={styles.free}>Вільно</div>}</div><button className={styles.add} onClick={()=>openNewRequest(day)}>+ <span>Додати</span></button></article>)}</section>:null}
  <p className={styles.rule}>{view==="day"?"Клік по вільному слоту створює новий запис. Картка авто показує фактичну зайнятість поста.":"Тиждень — огляд потоку. Натисніть на заголовок дня, щоб відкрити його детальний план по постах."}</p>
  {edit&&location&&<div className={styles.modalBackdrop} onMouseDown={closeEdit}><section className={styles.modal} onMouseDown={e=>e.stopPropagation()}><div className={styles.modalHead}><div><p>ПЕРЕНЕСЕННЯ / РЕДАГУВАННЯ</p><h2>{appointments.find(x=>x.id===edit.id)?.plateNumber||"Наряд"}</h2></div><button onClick={closeEdit}>×</button></div><div className={styles.formGrid}><label><span>Дата</span><input type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value,start:"",postId:"",mechanicId:""})}/></label><label><span>Тривалість</span><select value={edit.duration} onChange={e=>setEdit({...edit,duration:e.target.value,start:"",postId:"",mechanicId:""})}>{[30,60,90,120,180,240,360,480].map(x=><option key={x} value={x}>{x<60?`${x} хв`:`${x/60} год`}</option>)}</select></label><label><span>Статус</span><select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value as Status})}>{STATUS_OPTIONS.map(x=><option key={x} value={x}>{STATUS_META[x].label}</option>)}</select></label></div><AvailabilityPicker date={edit.date} locationId={location.id} durationMinutes={Number(edit.duration)||60} excludeAppointmentId={edit.id} selectedTime={edit.start} selectedPostId={edit.postId} selectedMechanicId={edit.mechanicId} onChange={selection=>setEdit({...edit,start:selection.time,postId:selection.postId,mechanicId:selection.mechanicId})}/><div className={styles.modalFoot}><button className={styles.secondary} onClick={closeEdit}>Закрити</button><button className={styles.primary} disabled={saving} onClick={()=>void saveEdit()}>{saving?"Зберігаю…":"Зберегти"}</button></div></section></div>}
 </div>;
}
