"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import styles from "./settings-center.module.css";

type ThemeMode = "light" | "dark" | "auto";
type Tab = "schedule" | "personnel" | "clients" | "suppliers" | "warehouse" | "workPrices" | "posts" | "markup" | "cash" | "integrations" | "appearance";
type DirectoryCategory = "PERSONNEL" | "SUPPLIER" | "WAREHOUSE" | "WORK_PRICE" | "CASH";
type DirectoryItem = { id: string; category: DirectoryCategory; name: string; code: string | null; data: Record<string, unknown> | null; isActive: boolean; sortOrder: number };
type Post = { id: string; name: string; sortOrder: number; isActive: boolean; capabilities: string[] };
type Mechanic = { id: string; name: string; sortOrder: number; isActive: boolean };
type Location = { id: string; name: string; timezone: string; openMinute: number; closeMinute: number; posts: Post[]; mechanics: Mechanic[] };
type ScheduleDay = { day: number; label: string; enabled: boolean; open: string; close: string };
type ClientRow = { id: string; name: string | null; phone: string; updatedAt: string; _count: { vehicles: number; workOrders: number } };
type OperationsResponse = { ok: boolean; location: Location | null; settings: Record<string, unknown>; directory: DirectoryItem[]; clientCount: number; recentClients: ClientRow[]; error?: string };
type IntegrationField = { key: string; label: string; secret: boolean; required?: boolean; placeholder?: string };
type IntegrationItem = { provider: string; category: string; title: string; description: string; fields: IntegrationField[]; configured: boolean; configuredVia: string | null; status: string; masked: Record<string,string>; visible: Record<string,string> };

type Draft = Record<string, string | boolean>;

const DEFAULT_SCHEDULE: ScheduleDay[] = ["Пн","Вт","Ср","Чт","Пт","Сб","Нд"].map((label,index)=>({day:index+1,label,enabled:true,open:"09:00",close:"21:00"}));
const tabs: Array<{ id: Tab; icon: string; label: string; note: string }> = [
  { id:"schedule", icon:"◷", label:"Графік", note:"Дні та години роботи" },
  { id:"personnel", icon:"Л", label:"Персонал", note:"Працівники й ресурси" },
  { id:"clients", icon:"К", label:"Клієнти", note:"Правила та база" },
  { id:"suppliers", icon:"П", label:"Постачальники", note:"Довідник закупівель" },
  { id:"warehouse", icon:"С", label:"Склад", note:"Склади та відповідальні" },
  { id:"workPrices", icon:"₴", label:"Прайс робіт", note:"Ціни та норми" },
  { id:"posts", icon:"П", label:"Пости", note:"Тип, колір, активність" },
  { id:"markup", icon:"%", label:"Націнка", note:"Запчастини та правила" },
  { id:"cash", icon:"₴", label:"Каса", note:"Каси та оплати" },
  { id:"integrations", icon:"⌘", label:"Інтеграції", note:"Телефонія й API" },
  { id:"appearance", icon:"◐", label:"Оформлення", note:"Світла / темна тема" },
];
const POST_TYPES: Record<string,string> = { LIFT:"Підйомник", NO_LIFT:"Пост без підйомника", PIT:"Яма", ALIGNMENT:"Розвал-сходження" };

function resolveTheme(mode: ThemeMode) { return mode === "auto" ? (window.matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark") : mode; }
function applyTheme(mode: ThemeMode) { document.documentElement.dataset.theme = resolveTheme(mode); document.documentElement.dataset.themeMode = mode; }
function dataText(item: DirectoryItem, key: string) { const value = item.data?.[key]; return value == null ? "" : String(value); }
function dataBool(item: DirectoryItem, key: string) { return item.data?.[key] === true; }
function parsePost(post: Post) {
  const type = post.capabilities.find((x)=>x.startsWith("TYPE:"))?.slice(5) || (post.id.includes("glevakha") ? "LIFT" : "NO_LIFT");
  const color = post.capabilities.find((x)=>x.startsWith("COLOR:"))?.slice(6) || (post.sortOrder <= 10 ? "#FF5A1F" : "#2F80ED");
  return { type, color };
}
function asObject(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }

export function SettingsCenter() {
  const [mounted,setMounted]=useState(false); const [open,setOpen]=useState(false); const [tab,setTab]=useState<Tab>("schedule");
  const [mode,setMode]=useState<ThemeMode>("auto"); const [ops,setOps]=useState<OperationsResponse|null>(null); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [toast,setToast]=useState("");
  const [schedule,setSchedule]=useState<ScheduleDay[]>(DEFAULT_SCHEDULE); const [draft,setDraft]=useState<Draft>({});
  const [integrations,setIntegrations]=useState<IntegrationItem[]>([]); const [integrationEdit,setIntegrationEdit]=useState<string|null>(null); const [integrationValues,setIntegrationValues]=useState<Record<string,string>>({});

  useEffect(()=>{setMounted(true);const saved=(window.localStorage.getItem("turbolev-theme-mode") as ThemeMode|null)||"auto";setMode(saved);applyTheme(saved);},[]);
  useEffect(()=>{if(open)void loadAll();},[open]);

  const directoryBy = (category: DirectoryCategory) => ops?.directory.filter((item)=>item.category===category) ?? [];
  const markup = asObject(ops?.settings?.markup);
  const clientRules = asObject(ops?.settings?.client_rules);
  const cashRules = asObject(ops?.settings?.cash_rules);

  function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),2600);}
  async function loadAll(){setLoading(true);try{const [opRes,intRes]=await Promise.all([fetch("/api/settings/operations",{cache:"no-store"}),fetch("/api/settings/integrations",{cache:"no-store"})]);const data=await opRes.json() as OperationsResponse;if(!opRes.ok||!data.ok)throw new Error(data.error||"Не вдалося завантажити налаштування");setOps(data);const savedSchedule=Array.isArray(data.settings?.work_schedule)?data.settings.work_schedule as ScheduleDay[]:DEFAULT_SCHEDULE;setSchedule(savedSchedule);const i=await intRes.json() as {integrations?:IntegrationItem[]};setIntegrations(Array.isArray(i.integrations)?i.integrations:[]);}catch(error){notify(error instanceof Error?error.message:"Помилка завантаження");}finally{setLoading(false);}}
  async function action(payload:Record<string,unknown>, success:string){setSaving(true);try{const response=await fetch("/api/settings/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {ok?:boolean;error?:string};if(!response.ok||!data.ok)throw new Error(data.error||"Не вдалося зберегти");notify(success);setDraft({});await loadAll();}catch(error){notify(error instanceof Error?error.message:"Помилка збереження");}finally{setSaving(false);}}
  function selectMode(next:ThemeMode){setMode(next);window.localStorage.setItem("turbolev-theme-mode",next);window.localStorage.removeItem("turbolev-theme");applyTheme(next);}

  async function saveIntegration(item:IntegrationItem){setSaving(true);try{const response=await fetch(`/api/settings/integrations/${item.provider}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({values:integrationValues})});const data=await response.json() as {ok?:boolean;error?:string;generated?:Record<string,string>};if(!response.ok||!data.ok)throw new Error(data.error||"Не вдалося зберегти доступи");setIntegrationEdit(null);setIntegrationValues({});notify(`${item.title}: збережено`);if(data.generated&&Object.keys(data.generated).length)notify(`${item.title}: згенеровано службовий токен — перевір інтеграцію`);await loadAll();}catch(error){notify(error instanceof Error?error.message:"Помилка інтеграції");}finally{setSaving(false);}}
  async function testIntegration(item:IntegrationItem){try{const response=await fetch(`/api/settings/integrations/${item.provider}/test`,{method:"POST"});const data=await response.json() as {ok?:boolean;message?:string;error?:string};notify(data.message||data.error||(data.ok?"З'єднання працює":"Перевірка не пройшла"));await loadAll();}catch{notify("CRM не змогла перевірити інтеграцію");}}

  function renderSchedule(){return <><SectionHead title="Робочий графік СТО" text="Редагується окремо для кожного дня. Планувальник використовує цей графік як робочий час локації." /><div className={styles.schedule}>{schedule.map((day,index)=><div className={styles.scheduleRow} key={day.day}><strong>{day.label}</strong><button type="button" className={`${styles.switch} ${day.enabled?styles.switchOn:""}`} onClick={()=>setSchedule(current=>current.map((row,i)=>i===index?{...row,enabled:!row.enabled}:row))} aria-label={`${day.label}: ${day.enabled?"робочий":"вихідний"}`} /><input type="time" value={day.open} disabled={!day.enabled} onChange={(e)=>setSchedule(current=>current.map((row,i)=>i===index?{...row,open:e.target.value}:row))}/><input type="time" value={day.close} disabled={!day.enabled} onChange={(e)=>setSchedule(current=>current.map((row,i)=>i===index?{...row,close:e.target.value}:row))}/></div>)}</div><div className={styles.formActions}><button className={styles.action} disabled={saving||!ops?.location} onClick={()=>void action({action:"SAVE_SCHEDULE",locationId:ops?.location?.id,schedule},"Графік роботи збережено")}>Зберегти графік</button></div></>}

  function renderPersonnel(){const items=directoryBy("PERSONNEL");return <><SectionHead title="Персонал" text="Посади, контакти та працівники, які можуть бути ресурсом Плану робіт." actionLabel="+ Додати працівника" onAction={()=>setDraft({form:"personnel",workshopResource:false,position:"Автомеханік"})}/>{draft.form==="personnel"&&<FormCard><div className={styles.formGrid}><Field label="ПІБ" value={draft.name} onChange={(v)=>setDraft({...draft,name:v})}/><Field label="Посада" value={draft.position} onChange={(v)=>setDraft({...draft,position:v})}/><Field label="Телефон" value={draft.phone} onChange={(v)=>setDraft({...draft,phone:v})}/><label><span>Ресурс Плану робіт</span><select value={String(Boolean(draft.workshopResource))} onChange={(e)=>setDraft({...draft,workshopResource:e.target.value==="true"})}><option value="false">Ні</option><option value="true">Так, показувати як виконавця</option></select></label><Field label="% / ставка" value={draft.salary} onChange={(v)=>setDraft({...draft,salary:v})}/></div><FormActions onCancel={()=>setDraft({})} onSave={()=>void action({action:"ADD_DIRECTORY",category:"PERSONNEL",name:draft.name,code:"",data:{position:draft.position,phone:draft.phone,salary:draft.salary,workshopResource:Boolean(draft.workshopResource),locationId:ops?.location?.id}},"Працівника додано")} saving={saving}/></FormCard>}<div className={styles.cards}>{items.map(item=><DirectoryCard key={item.id} item={item} facts={[["Посада",dataText(item,"position")||"—"],["Телефон",dataText(item,"phone")||"—"],["План робіт",dataBool(item,"workshopResource")?"Так":"Ні"]]} onToggle={()=>void action({action:"TOGGLE_DIRECTORY",id:item.id,isActive:!item.isActive},item.isActive?"Працівника деактивовано":"Працівника активовано")}/>)}</div>{!items.length&&<Empty text="Додай персонал. Автомеханіків можна відразу зробити ресурсом Плану робіт."/>}</>}

  function renderClients(){return <><SectionHead title="Клієнти" text="Єдина база клієнтів і правила її ведення. Клієнт не дублюється за тим самим номером телефону."/><div className={styles.stats}><Stat label="Клієнтів у CRM" value={String(ops?.clientCount??0)}/><Stat label="Пошук дубля" value={clientRules.deduplicateByPhone===false?"Вимкнено":"По телефону"}/><Stat label="Історія авто" value={clientRules.keepVehicleHistory===false?"Вимкнено":"Зберігати"}/></div><div className={styles.formCard}><div className={styles.formGrid}><label><span>Обов’язковий телефон</span><select value={String(clientRules.requirePhone!==false)} onChange={(e)=>void action({action:"SAVE_SETTING",key:"client_rules",value:{...clientRules,requirePhone:e.target.value==="true"}},"Правила клієнтів оновлено")}><option value="true">Так</option><option value="false">Ні</option></select></label><label><span>Знижка за замовчуванням, %</span><input value={String(clientRules.defaultDiscountPercent??0)} onChange={(e)=>setDraft({...draft,clientDiscount:e.target.value})}/></label><div className={styles.formActions}><button className={styles.action} onClick={()=>void action({action:"SAVE_SETTING",key:"client_rules",value:{...clientRules,defaultDiscountPercent:Number(draft.clientDiscount??clientRules.defaultDiscountPercent??0)}},"Правила клієнтів збережено")}>Зберегти</button></div></div></div><div className={styles.clientRows}>{ops?.recentClients.map(client=><div className={styles.clientRow} key={client.id}><span><strong>{client.name||"Клієнт"}</strong><small>{client.phone}</small></span><span>{client._count.vehicles} авто</span><span>{client._count.workOrders} нарядів</span><span>{new Intl.DateTimeFormat("uk-UA").format(new Date(client.updatedAt))}</span></div>)}</div></>}

  function renderSuppliers(){const items=directoryBy("SUPPLIER");return <><SectionHead title="Постачальники" text="Контакти, умови закупівлі та строки доставки. API-доступи налаштовуються у вкладці «Інтеграції»." actionLabel="+ Постачальник" onAction={()=>setDraft({form:"supplier"})}/>{draft.form==="supplier"&&<FormCard><div className={styles.formGrid}><Field label="Назва" value={draft.name} onChange={(v)=>setDraft({...draft,name:v})}/><Field label="Телефон" value={draft.phone} onChange={(v)=>setDraft({...draft,phone:v})}/><Field label="Email" value={draft.email} onChange={(v)=>setDraft({...draft,email:v})}/><Field label="Сайт" value={draft.website} onChange={(v)=>setDraft({...draft,website:v})}/><Field label="Доставка, днів" value={draft.deliveryDays} onChange={(v)=>setDraft({...draft,deliveryDays:v})}/><label><span>Оплата</span><select value={String(draft.payment||"Передплата")} onChange={(e)=>setDraft({...draft,payment:e.target.value})}><option>Передплата</option><option>Післяплата</option><option>Відстрочка</option></select></label></div><FormActions onCancel={()=>setDraft({})} onSave={()=>void action({action:"ADD_DIRECTORY",category:"SUPPLIER",name:draft.name,data:{phone:draft.phone,email:draft.email,website:draft.website,deliveryDays:draft.deliveryDays,payment:draft.payment}},"Постачальника додано")} saving={saving}/></FormCard>}<div className={styles.cards}>{items.map(item=><DirectoryCard key={item.id} item={item} facts={[["Телефон",dataText(item,"phone")||"—"],["Доставка",dataText(item,"deliveryDays")?`${dataText(item,"deliveryDays")} дн.`:"—"],["Оплата",dataText(item,"payment")||"—"]]} onToggle={()=>void action({action:"TOGGLE_DIRECTORY",id:item.id,isActive:!item.isActive},"Статус постачальника змінено")}/>)}</div>{!items.length&&<Empty text="Постачальників ще немає у довіднику."/>}</>}

  function renderWarehouse(){const items=directoryBy("WAREHOUSE");return <><SectionHead title="Склад" text="Кількість складів не фіксована. Далі кожен склад буде використовуватись для резервів, видачі на пост і повернень." actionLabel="+ Склад" onAction={()=>setDraft({form:"warehouse"})}/>{draft.form==="warehouse"&&<FormCard><div className={styles.formGrid}><Field label="Назва складу" value={draft.name} onChange={(v)=>setDraft({...draft,name:v})}/><Field label="Локація" value={draft.location} onChange={(v)=>setDraft({...draft,location:v})}/><Field label="Відповідальний" value={draft.responsible} onChange={(v)=>setDraft({...draft,responsible:v})}/></div><FormActions onCancel={()=>setDraft({})} onSave={()=>void action({action:"ADD_DIRECTORY",category:"WAREHOUSE",name:draft.name,data:{location:draft.location,responsible:draft.responsible}},"Склад додано")} saving={saving}/></FormCard>}<div className={styles.cards}>{items.map(item=><DirectoryCard key={item.id} item={item} facts={[["Локація",dataText(item,"location")||"—"],["Відповідальний",dataText(item,"responsible")||"Не призначено"]]} onToggle={()=>void action({action:"TOGGLE_DIRECTORY",id:item.id,isActive:!item.isActive},"Статус складу змінено")}/>)}</div></>}

  function renderWorkPrices(){const items=directoryBy("WORK_PRICE");return <><SectionHead title="Прайс робіт" text="Базова ціна роботи зберігається окремо від коефіцієнта класу автомобіля. Так ціна масштабується системно." actionLabel="+ Робота" onAction={()=>setDraft({form:"price",unit:"шт"})}/>{draft.form==="price"&&<FormCard><div className={styles.formGrid}><Field label="Назва роботи" value={draft.name} onChange={(v)=>setDraft({...draft,name:v})}/><Field label="Категорія" value={draft.category} onChange={(v)=>setDraft({...draft,category:v})}/><Field label="Ціна, грн" value={draft.price} onChange={(v)=>setDraft({...draft,price:v})}/><Field label="Одиниця" value={draft.unit} onChange={(v)=>setDraft({...draft,unit:v})}/><Field label="% механіка" value={draft.mechanicPercent} onChange={(v)=>setDraft({...draft,mechanicPercent:v})}/></div><FormActions onCancel={()=>setDraft({})} onSave={()=>void action({action:"ADD_DIRECTORY",category:"WORK_PRICE",name:draft.name,data:{category:draft.category,price:Number(draft.price||0),unit:draft.unit,mechanicPercent:Number(draft.mechanicPercent||0)}},"Роботу додано в прайс")} saving={saving}/></FormCard>}<div className={styles.cards}>{items.map(item=><DirectoryCard key={item.id} item={item} facts={[["Категорія",dataText(item,"category")||"—"],["Ціна",`${dataText(item,"price")||0} грн`],["Механік",`${dataText(item,"mechanicPercent")||0}%`]]} onToggle={()=>void action({action:"TOGGLE_DIRECTORY",id:item.id,isActive:!item.isActive},"Статус роботи змінено")}/>)}</div>{!items.length&&<Empty text="Додай базові роботи та їхню ціну."/>}</>}

  function renderPosts(){const posts=ops?.location?.posts??[];return <><SectionHead title="Пости" text="Кількість постів змінюється. Тип і колір поста одразу використовуються у Плані робіт." actionLabel="+ Новий пост" onAction={()=>setDraft({form:"post",type:"LIFT",color:"#FF6600"})}/>{draft.form==="post"&&<FormCard><div className={styles.formGrid}><Field label="Назва" value={draft.name} onChange={(v)=>setDraft({...draft,name:v})}/><label><span>Тип</span><select value={String(draft.type||"LIFT")} onChange={(e)=>setDraft({...draft,type:e.target.value})}>{Object.entries(POST_TYPES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Колір у плані</span><input className={styles.inlineColor} type="color" value={String(draft.color||"#FF6600")} onChange={(e)=>setDraft({...draft,color:e.target.value})}/></label></div><FormActions onCancel={()=>setDraft({})} onSave={()=>void action({action:"ADD_POST",locationId:ops?.location?.id,name:draft.name,type:draft.type,color:draft.color},"Новий пост додано") } saving={saving}/></FormCard>}<div className={styles.cards}>{posts.map(post=>{const meta=parsePost(post);return <article className={styles.card} key={post.id}><div className={styles.cardTop}><div className={styles.cardTitle}><i className={styles.postColor} style={{background:meta.color}}/><div><strong>{post.name}</strong><small>{POST_TYPES[meta.type]||meta.type}</small></div></div><span className={`${styles.badge} ${post.isActive?styles.badgeGood:""}`}>{post.isActive?"Активний":"Вимкнений"}</span></div><div className={styles.cardActions}><button className={styles.smallButton} onClick={()=>{const name=window.prompt("Назва поста",post.name);if(!name)return;const type=window.prompt("Тип: LIFT / NO_LIFT / PIT / ALIGNMENT",meta.type)||meta.type;void action({action:"UPDATE_POST",id:post.id,name,type,color:meta.color},"Пост оновлено")}}>Редагувати</button><button className={styles.smallButton} onClick={()=>void action({action:"TOGGLE_POST",id:post.id,isActive:!post.isActive},post.isActive?"Пост вимкнено":"Пост активовано")}>{post.isActive?"Вимкнути":"Увімкнути"}</button></div></article>})}</div></>}

  function renderMarkup(){return <><SectionHead title="Націнка" text="Це правила за замовчуванням. Менеджер бачить закупівельну ціну, продажну ціну та валовий прибуток."/><div className={styles.markupGrid}><div className={styles.bigField}><span>Націнка на запчастини, %</span><input value={String(draft.partsMarkup??markup.defaultPartsPercent??23)} onChange={(e)=>setDraft({...draft,partsMarkup:e.target.value.replace(/\D/g,"")})}/><small>Застосовується до закупівельної ціни, якщо для товару або постачальника немає окремого правила.</small></div><div className={styles.bigField}><span>Роботи з деталями клієнта, +%</span><input value={String(draft.customerParts??markup.customerPartsLaborPercent??20)} onChange={(e)=>setDraft({...draft,customerParts:e.target.value.replace(/\D/g,"")})}/><small>Окреме правило для робіт, коли клієнт привіз власні запчастини.</small></div></div><div className={styles.formActions}><button className={styles.action} onClick={()=>void action({action:"SAVE_SETTING",key:"markup",value:{...markup,defaultPartsPercent:Number(draft.partsMarkup??markup.defaultPartsPercent??23),customerPartsLaborPercent:Number(draft.customerParts??markup.customerPartsLaborPercent??20)}},"Націнку збережено")}>Зберегти націнку</button></div></>}

  function renderCash(){const items=directoryBy("CASH");return <><SectionHead title="Каса" text="Налаштовуються каси та способи оплати. Фактичний баланс надалі формується тільки з проведених платежів, а не вручну." actionLabel="+ Каса" onAction={()=>setDraft({form:"cash"})}/>{draft.form==="cash"&&<FormCard><div className={styles.formGrid}><Field label="Назва каси" value={draft.name} onChange={(v)=>setDraft({...draft,name:v})}/><Field label="Локація" value={draft.location} onChange={(v)=>setDraft({...draft,location:v})}/></div><FormActions onCancel={()=>setDraft({})} onSave={()=>void action({action:"ADD_DIRECTORY",category:"CASH",name:draft.name,data:{location:draft.location,paymentMethods:cashRules.paymentMethods||["Готівка","Картка","Переказ"]}},"Касу додано")} saving={saving}/></FormCard>}<div className={styles.cards}>{items.map(item=><DirectoryCard key={item.id} item={item} facts={[["Локація",dataText(item,"location")||"—"],["Валюта",String(cashRules.currency||"UAH")]]} onToggle={()=>void action({action:"TOGGLE_DIRECTORY",id:item.id,isActive:!item.isActive},"Статус каси змінено")}/>)}</div><p className={styles.footerHint}>Способи оплати: {Array.isArray(cashRules.paymentMethods)?cashRules.paymentMethods.join(" · "):"Готівка · Картка · Переказ"}.</p></>}

  function renderIntegrations(){return <><SectionHead title="Інтеграції" text="Телефонія, соцмережі та постачальники. Секретні ключі після збереження не повертаються у браузер." actionLabel={loading?"Оновлюю…":"Оновити"} onAction={()=>void loadAll()}/><div className={styles.integrationGrid}>{integrations.map(item=>{const editing=integrationEdit===item.provider;return <article className={styles.integrationCard} key={item.provider}><div className={styles.integrationTop}><div><strong>{item.title}</strong><span>{item.description}</span></div><span className={`${styles.badge} ${item.status==="CONNECTED"?styles.badgeGood:""}`}>{item.status==="CONNECTED"?"Підключено":item.configured?"Налаштовано":"Не налаштовано"}</span></div>{editing&&<div className={styles.integrationFields}>{item.fields.map(field=><label key={field.key}><span>{field.label}</span><input type={field.secret?"password":"text"} placeholder={field.secret?(item.masked[field.key]||field.placeholder||""):field.placeholder||""} value={integrationValues[field.key]??item.visible[field.key]??""} onChange={(e)=>setIntegrationValues(current=>({...current,[field.key]:e.target.value}))}/></label>)}</div>}<div className={styles.cardActions}>{editing?<><button className={styles.action} disabled={saving} onClick={()=>void saveIntegration(item)}>Зберегти</button><button className={styles.secondary} onClick={()=>{setIntegrationEdit(null);setIntegrationValues({})}}>Скасувати</button></>:<button className={styles.smallButton} onClick={()=>{setIntegrationEdit(item.provider);setIntegrationValues({...item.visible})}}>Налаштувати</button>}<button className={styles.smallButton} onClick={()=>void testIntegration(item)}>Перевірити</button></div></article>})}</div></>}

  function renderAppearance(){return <><SectionHead title="Оформлення" text="Тема CRM може повторювати налаштування системи або бути зафіксована вручну."/><div className={styles.themeGrid}>{(["light","dark","auto"] as ThemeMode[]).map(value=><button key={value} className={`${styles.themeButton} ${mode===value?styles.themeActive:""}`} onClick={()=>selectMode(value)}><div className={`${styles.themePreview} ${styles[value]}`}/><strong>{value==="light"?"Світла":value==="dark"?"Темна":"Автоматична"}</strong><small>{value==="auto"?"Як у Windows / браузері":"Фіксований режим"}</small></button>)}</div></>}

  const content = loading&&!ops?<Empty text="Завантажую налаштування…"/>:tab==="schedule"?renderSchedule():tab==="personnel"?renderPersonnel():tab==="clients"?renderClients():tab==="suppliers"?renderSuppliers():tab==="warehouse"?renderWarehouse():tab==="workPrices"?renderWorkPrices():tab==="posts"?renderPosts():tab==="markup"?renderMarkup():tab==="cash"?renderCash():tab==="integrations"?renderIntegrations():renderAppearance();

  const portal = open?<div className={styles.backdrop} onMouseDown={()=>setOpen(false)}>{toast&&<div className={styles.toast}>{toast}</div>}<section className={styles.modal} onMouseDown={(e)=>e.stopPropagation()}><header className={styles.head}><div><p>TURBO LEV · СИСТЕМА</p><h2>Налаштування</h2><span>{ops?.location?.name||"СТО"} · усі довідники редаговані та пов’язані з CRM</span></div><button className={styles.close} onClick={()=>setOpen(false)}>×</button></header><div className={styles.layout}><aside className={styles.tabs}>{tabs.map(item=><button key={item.id} className={`${styles.tab} ${tab===item.id?styles.tabActive:""}`} onClick={()=>{setTab(item.id);setDraft({});setIntegrationEdit(null)}}><span className={styles.tabIcon}>{item.icon}</span><span><strong>{item.label}</strong><small>{item.note}</small></span></button>)}</aside><main className={styles.content}>{content}</main></div></section></div>:null;

  return <><button className="settingsNavButton" type="button" onClick={()=>setOpen(true)}><span className="navDot"/>Налаштування</button>{mounted&&portal?createPortal(portal,document.body):null}</>;
}

function SectionHead({title,text,actionLabel,onAction}:{title:string;text:string;actionLabel?:string;onAction?:()=>void}){return <div className={styles.sectionHead}><div><h3>{title}</h3><p>{text}</p></div>{actionLabel&&onAction?<button className={styles.action} onClick={onAction}>{actionLabel}</button>:null}</div>}
function Field({label,value,onChange}:{label:string;value:Draft[string];onChange:(value:string)=>void}){return <label><span>{label}</span><input value={String(value??"")} onChange={(e)=>onChange(e.target.value)}/></label>}
function FormCard({children}:{children:React.ReactNode}){return <div className={styles.formCard}>{children}</div>}
function FormActions({onCancel,onSave,saving}:{onCancel:()=>void;onSave:()=>void;saving:boolean}){return <div className={styles.formActions}><button className={styles.secondary} onClick={onCancel}>Скасувати</button><button className={styles.action} disabled={saving} onClick={onSave}>{saving?"Зберігаю…":"Зберегти"}</button></div>}
function DirectoryCard({item,facts,onToggle}:{item:DirectoryItem;facts:Array<[string,string]>;onToggle:()=>void}){return <article className={styles.card}><div className={styles.cardTop}><div className={styles.cardTitle}><i className={styles.dot} style={{background:item.isActive?"#16a34a":"#64748b"}}/><div><strong>{item.name}</strong><small>{item.code||item.category}</small></div></div><span className={`${styles.badge} ${item.isActive?styles.badgeGood:""}`}>{item.isActive?"Активний":"Вимкнений"}</span></div><div className={styles.cardBody}>{facts.map(([label,value])=><div className={styles.fact} key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className={styles.cardActions}><button className={styles.smallButton} onClick={onToggle}>{item.isActive?"Вимкнути":"Увімкнути"}</button></div></article>}
function Stat({label,value}:{label:string;value:string}){return <div className={styles.stat}><span>{label}</span><strong>{value}</strong></div>}
function Empty({text}:{text:string}){return <div className={styles.empty}>{text}</div>}
