CREATE TABLE "CrmTask" (
  "id" TEXT NOT NULL,
  "title" VARCHAR(240) NOT NULL,
  "description" TEXT,
  "status" VARCHAR(24) NOT NULL DEFAULT 'OPEN',
  "priority" VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  "assignedUserId" VARCHAR(64) NOT NULL,
  "createdByUserId" VARCHAR(64),
  "dueAt" TIMESTAMP(3),
  "remindAt" TIMESTAMP(3),
  "completedAt" TIMESTAMP(3),
  "sourceType" VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
  "sourceId" VARCHAR(96),
  "clientId" VARCHAR(64),
  "vehicleId" VARCHAR(64),
  "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
  "dedupeKey" VARCHAR(180),
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CrmTask_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "CrmTask_dedupeKey_key" ON "CrmTask"("dedupeKey");
CREATE INDEX "CrmTask_assignedUserId_status_dueAt_idx" ON "CrmTask"("assignedUserId", "status", "dueAt");
CREATE INDEX "CrmTask_sourceType_sourceId_idx" ON "CrmTask"("sourceType", "sourceId");
CREATE INDEX "CrmTask_clientId_idx" ON "CrmTask"("clientId");
CREATE INDEX "CrmTask_vehicleId_idx" ON "CrmTask"("vehicleId");
CREATE INDEX "CrmTask_createdAt_idx" ON "CrmTask"("createdAt");

CREATE OR REPLACE FUNCTION turbolev_task_id(seed TEXT)
RETURNS TEXT
LANGUAGE SQL
VOLATILE
AS $$
  SELECT 'task_' || md5(random()::text || clock_timestamp()::text || COALESCE(seed, ''));
$$;

CREATE OR REPLACE FUNCTION turbolev_sync_lead_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'lead:' || NEW."id" || ':next-action';
  task_title TEXT;
  task_due TIMESTAMP(3);
  active_status BOOLEAN;
BEGIN
  active_status := NEW."status"::text IN ('NEW','CONTACTED','QUALIFIED','ESTIMATE','WAITING','NO_ANSWER');

  IF active_status AND NEW."assignedUserId" IS NOT NULL THEN
    task_title := COALESCE(NULLIF(BTRIM(NEW."nextAction"), ''),
      CASE NEW."status"::text
        WHEN 'NEW' THEN 'Опрацювати новий лід'
        WHEN 'CONTACTED' THEN 'Уточнити потребу клієнта'
        WHEN 'QUALIFIED' THEN 'Підготувати прорахунок'
        WHEN 'ESTIMATE' THEN 'Погодити прорахунок з клієнтом'
        WHEN 'WAITING' THEN 'Отримати рішення клієнта'
        WHEN 'NO_ANSWER' THEN 'Повторити контакт з клієнтом'
        ELSE 'Опрацювати лід'
      END
    );
    task_due := COALESCE(NEW."nextContactAt", CASE WHEN NEW."status"::text = 'NEW' THEN CURRENT_TIMESTAMP + INTERVAL '30 minutes' ELSE CURRENT_TIMESTAMP + INTERVAL '1 day' END);

    INSERT INTO "CrmTask" (
      "id", "title", "status", "priority", "assignedUserId", "dueAt",
      "sourceType", "sourceId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
    ) VALUES (
      turbolev_task_id(NEW."id"), task_title, 'OPEN',
      CASE WHEN NEW."status"::text IN ('NEW','NO_ANSWER') THEN 'HIGH' ELSE 'MEDIUM' END,
      NEW."assignedUserId", task_due, 'LEAD', NEW."id", true, task_key,
      jsonb_build_object('leadStatus', NEW."status"::text), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
    ON CONFLICT ("dedupeKey") DO UPDATE SET
      "title" = EXCLUDED."title",
      "status" = 'OPEN',
      "priority" = EXCLUDED."priority",
      "assignedUserId" = EXCLUDED."assignedUserId",
      "dueAt" = EXCLUDED."dueAt",
      "completedAt" = NULL,
      "metadata" = EXCLUDED."metadata",
      "updatedAt" = CURRENT_TIMESTAMP;
  ELSE
    UPDATE "CrmTask"
       SET "status"='DONE', "completedAt"=COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt"=CURRENT_TIMESTAMP
     WHERE "dedupeKey"=task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER "Lead_task_after_insert"
AFTER INSERT ON "Lead"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_lead_task();

CREATE TRIGGER "Lead_task_after_update"
AFTER UPDATE OF "status", "nextAction", "nextContactAt", "assignedUserId" ON "Lead"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_lead_task();

CREATE OR REPLACE FUNCTION turbolev_sync_inquiry_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'inquiry:' || NEW."id" || ':active';
  task_title TEXT;
BEGIN
  IF NEW."assignedUserId" IS NOT NULL
     AND NEW."state"::text IN ('NEW','IN_WORK')
     AND NEW."answered" = false THEN
    task_title := CASE WHEN NEW."state"::text = 'NEW'
      THEN 'Опрацювати нове звернення: '
      ELSE 'Відповісти клієнту: '
    END || LEFT(COALESCE(NULLIF(BTRIM(NEW."subject"), ''), 'без теми'), 170);

    INSERT INTO "CrmTask" (
      "id", "title", "status", "priority", "assignedUserId", "dueAt",
      "sourceType", "sourceId", "autoGenerated", "dedupeKey", "metadata", "createdAt", "updatedAt"
    ) VALUES (
      turbolev_task_id(NEW."id"), task_title, 'OPEN',
      CASE WHEN NEW."channel"::text = 'BINOTEL' AND LOWER(COALESCE(NEW."subject", '') || ' ' || COALESCE(NEW."preview", '')) LIKE '%пропущ%' THEN 'CRITICAL' ELSE 'HIGH' END,
      NEW."assignedUserId", NEW."receivedAt" + INTERVAL '15 minutes',
      'INQUIRY', NEW."id", true, task_key,
      jsonb_build_object('channel', NEW."channel"::text), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
    ON CONFLICT ("dedupeKey") DO UPDATE SET
      "title" = EXCLUDED."title",
      "status" = 'OPEN',
      "priority" = EXCLUDED."priority",
      "assignedUserId" = EXCLUDED."assignedUserId",
      "dueAt" = EXCLUDED."dueAt",
      "completedAt" = NULL,
      "metadata" = EXCLUDED."metadata",
      "updatedAt" = CURRENT_TIMESTAMP;
  ELSE
    UPDATE "CrmTask"
       SET "status"='DONE', "completedAt"=COALESCE("completedAt", CURRENT_TIMESTAMP), "updatedAt"=CURRENT_TIMESTAMP
     WHERE "dedupeKey"=task_key AND "status" IN ('OPEN','IN_PROGRESS');
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER "CommunicationInquiry_task_after_insert"
AFTER INSERT ON "CommunicationInquiry"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_inquiry_task();

CREATE TRIGGER "CommunicationInquiry_task_after_update"
AFTER UPDATE OF "state", "assignedUserId", "answered", "receivedAt", "subject" ON "CommunicationInquiry"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_inquiry_task();

CREATE OR REPLACE FUNCTION turbolev_sync_message_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."direction"::text = 'IN' THEN
    UPDATE "CommunicationInquiry"
       SET "answered"=false, "unread"=true, "updatedAt"=CURRENT_TIMESTAMP
     WHERE "id"=NEW."inquiryId";
  ELSIF NEW."direction"::text = 'OUT' THEN
    UPDATE "CommunicationInquiry"
       SET "answered"=true,
           "unread"=false,
           "state"=CASE WHEN "state"::text='NEW' THEN 'IN_WORK'::"InquiryState" ELSE "state" END,
           "updatedAt"=CURRENT_TIMESTAMP
     WHERE "id"=NEW."inquiryId";
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "CommunicationMessage_task_after_insert"
AFTER INSERT ON "CommunicationMessage"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_message_task();
