-- Stage 2 of the business-process task engine.
-- Adds automatic personal tasks for estimates, parts, payments, QC and warranties.

CREATE OR REPLACE FUNCTION turbolev_task_assignee_for_work_order(work_order_id TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT COALESCE(
    l."assignedUserId",
    (
      SELECT ci."assignedUserId"
      FROM "CommunicationInquiry" ci
      WHERE ci."leadId" = dr."leadId"
        AND ci."assignedUserId" IS NOT NULL
      ORDER BY ci."updatedAt" DESC
      LIMIT 1
    ),
    (
      SELECT ch."managerId"
      FROM "CallHistory" ch
      WHERE ch."workOrderId" = wo."id"
        AND ch."managerId" IS NOT NULL
      ORDER BY ch."createdAt" DESC
      LIMIT 1
    )
  )
  FROM "WorkOrder" wo
  JOIN "DiagnosticRequest" dr ON dr."id" = wo."diagnosticRequestId"
  LEFT JOIN "Lead" l ON l."id" = dr."leadId"
  WHERE wo."id" = work_order_id
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION turbolev_close_process_task(task_key TEXT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE "CrmTask"
     SET "status" = 'DONE',
         "completedAt" = COALESCE("completedAt", CURRENT_TIMESTAMP),
         "updatedAt" = CURRENT_TIMESTAMP
   WHERE "dedupeKey" = task_key
     AND "status" IN ('OPEN', 'IN_PROGRESS');
END;
$$;

CREATE OR REPLACE FUNCTION turbolev_upsert_process_task(
  task_key TEXT,
  task_title TEXT,
  task_priority TEXT,
  task_assignee TEXT,
  task_due TIMESTAMP(3),
  task_source_type TEXT,
  task_source_id TEXT,
  task_work_order_id TEXT,
  task_work_order_tab TEXT,
  task_target_section TEXT,
  task_source_status TEXT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  task_client_id TEXT;
  task_vehicle_id TEXT;
BEGIN
  IF task_assignee IS NULL THEN
    PERFORM turbolev_close_process_task(task_key);
    RETURN;
  END IF;

  SELECT wo."clientId", wo."vehicleId"
    INTO task_client_id, task_vehicle_id
    FROM "WorkOrder" wo
   WHERE wo."id" = task_work_order_id
   LIMIT 1;

  INSERT INTO "CrmTask" (
    "id", "title", "status", "priority", "assignedUserId", "dueAt",
    "sourceType", "sourceId", "clientId", "vehicleId", "autoGenerated",
    "dedupeKey", "metadata", "createdAt", "updatedAt"
  ) VALUES (
    turbolev_task_id(task_source_id),
    LEFT(task_title, 240),
    'OPEN',
    task_priority,
    task_assignee,
    task_due,
    task_source_type,
    task_source_id,
    task_client_id,
    task_vehicle_id,
    true,
    task_key,
    jsonb_build_object(
      'workOrderId', task_work_order_id,
      'workOrderTab', task_work_order_tab,
      'targetSection', task_target_section,
      'sourceStatus', task_source_status
    ),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
  ON CONFLICT ("dedupeKey") DO UPDATE SET
    "title" = EXCLUDED."title",
    "status" = 'OPEN',
    "priority" = EXCLUDED."priority",
    "assignedUserId" = EXCLUDED."assignedUserId",
    "dueAt" = EXCLUDED."dueAt",
    "completedAt" = NULL,
    "sourceId" = EXCLUDED."sourceId",
    "clientId" = EXCLUDED."clientId",
    "vehicleId" = EXCLUDED."vehicleId",
    "metadata" = EXCLUDED."metadata",
    "updatedAt" = CURRENT_TIMESTAMP;
END;
$$;

CREATE OR REPLACE FUNCTION turbolev_sync_estimate_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'estimate:' || NEW."id" || ':action';
  assignee TEXT;
  title TEXT;
  priority TEXT;
  due_at TIMESTAMP(3);
BEGIN
  assignee := turbolev_task_assignee_for_work_order(NEW."workOrderId");

  IF NEW."status"::text = 'DRAFT' THEN
    title := 'Завершити кошторис та підготувати його до відправлення клієнту';
    priority := 'MEDIUM';
    due_at := CURRENT_TIMESTAMP + INTERVAL '2 hours';
  ELSIF NEW."status"::text = 'SENT' THEN
    title := 'Отримати рішення клієнта по кошторису';
    priority := 'HIGH';
    due_at := COALESCE(NEW."sentAt", CURRENT_TIMESTAMP) + INTERVAL '24 hours';
  ELSE
    PERFORM turbolev_close_process_task(task_key);
    RETURN NEW;
  END IF;

  PERFORM turbolev_upsert_process_task(
    task_key, title, priority, assignee, due_at,
    'ESTIMATE', NEW."id", NEW."workOrderId", 'estimate', 'Замовлення-наряди', NEW."status"::text
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "WorkOrderEstimate_task_after_insert" ON "WorkOrderEstimate";
CREATE TRIGGER "WorkOrderEstimate_task_after_insert"
AFTER INSERT ON "WorkOrderEstimate"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_estimate_task();

DROP TRIGGER IF EXISTS "WorkOrderEstimate_task_after_update" ON "WorkOrderEstimate";
CREATE TRIGGER "WorkOrderEstimate_task_after_update"
AFTER UPDATE OF "status", "sentAt", "workOrderId" ON "WorkOrderEstimate"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_estimate_task();

CREATE OR REPLACE FUNCTION turbolev_sync_parts_request_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'parts-request:' || NEW."id" || ':action';
  assignee TEXT;
  title TEXT;
  priority TEXT;
  due_at TIMESTAMP(3);
  eta_at TIMESTAMP(3);
BEGIN
  assignee := turbolev_task_assignee_for_work_order(NEW."workOrderId");
  SELECT MIN(pri."etaAt") INTO eta_at
    FROM "PartsRequestItem" pri
   WHERE pri."partsRequestId" = NEW."id"
     AND pri."etaAt" IS NOT NULL;

  IF NEW."status"::text IN ('NEW', 'SELECTING', 'SELECTED') THEN
    title := 'Підібрати та погодити запчастини для ремонту';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '2 hours';
  ELSIF NEW."status"::text = 'WAITING_APPROVAL' THEN
    title := 'Отримати погодження клієнта по запчастинах';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '24 hours';
  ELSIF NEW."status"::text IN ('APPROVED', 'ORDER_REQUIRED') THEN
    title := 'Замовити погоджені запчастини';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '2 hours';
  ELSIF NEW."status"::text IN ('ORDERED', 'PARTIALLY_RECEIVED') THEN
    title := CASE WHEN NEW."status"::text = 'PARTIALLY_RECEIVED'
      THEN 'Контролювати отримання решти запчастин'
      ELSE 'Контролювати надходження замовлених запчастин'
    END;
    priority := CASE WHEN NEW."status"::text = 'PARTIALLY_RECEIVED' THEN 'HIGH' ELSE 'MEDIUM' END;
    due_at := COALESCE(eta_at, CURRENT_TIMESTAMP + INTERVAL '1 day');
  ELSE
    PERFORM turbolev_close_process_task(task_key);
    RETURN NEW;
  END IF;

  PERFORM turbolev_upsert_process_task(
    task_key, title, priority, assignee, due_at,
    'PARTS_REQUEST', NEW."id", NEW."workOrderId", 'parts', 'Замовлення-наряди', NEW."status"::text
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "PartsRequest_task_after_insert" ON "PartsRequest";
CREATE TRIGGER "PartsRequest_task_after_insert"
AFTER INSERT ON "PartsRequest"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_parts_request_task();

DROP TRIGGER IF EXISTS "PartsRequest_task_after_update" ON "PartsRequest";
CREATE TRIGGER "PartsRequest_task_after_update"
AFTER UPDATE OF "status", "workOrderId", "paymentConfirmedAt" ON "PartsRequest"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_parts_request_task();

CREATE OR REPLACE FUNCTION turbolev_sync_payment_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'payment:' || NEW."id" || ':receivable';
  assignee TEXT;
  fallback_user TEXT;
  title TEXT;
  priority TEXT;
  due_at TIMESTAMP(3);
BEGIN
  IF NEW."direction"::text <> 'RECEIVABLE' OR NEW."workOrderId" IS NULL THEN
    PERFORM turbolev_close_process_task(task_key);
    RETURN NEW;
  END IF;

  assignee := turbolev_task_assignee_for_work_order(NEW."workOrderId");
  IF assignee IS NULL AND NEW."sourceEventId" IS NOT NULL THEN
    SELECT fe."createdById" INTO fallback_user
      FROM "FinancialEvent" fe
     WHERE fe."id" = NEW."sourceEventId"
     LIMIT 1;
    assignee := fallback_user;
  END IF;

  IF NEW."status"::text = 'OPEN' THEN
    title := 'Отримати оплату від клієнта';
    priority := 'HIGH';
    due_at := COALESCE(NEW."dueAt", CURRENT_TIMESTAMP + INTERVAL '1 day');
  ELSIF NEW."status"::text = 'PARTIALLY_PAID' THEN
    title := 'Отримати залишок оплати від клієнта';
    priority := 'HIGH';
    due_at := COALESCE(NEW."dueAt", CURRENT_TIMESTAMP + INTERVAL '1 day');
  ELSIF NEW."status"::text = 'OVERDUE' THEN
    title := 'Прострочена оплата: зв’язатися з клієнтом';
    priority := 'CRITICAL';
    due_at := CURRENT_TIMESTAMP;
  ELSE
    PERFORM turbolev_close_process_task(task_key);
    RETURN NEW;
  END IF;

  PERFORM turbolev_upsert_process_task(
    task_key, title, priority, assignee, due_at,
    'PAYMENT', NEW."id", NEW."workOrderId", 'payment', 'Замовлення-наряди', NEW."status"::text
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "FinancialObligation_task_after_insert" ON "FinancialObligation";
CREATE TRIGGER "FinancialObligation_task_after_insert"
AFTER INSERT ON "FinancialObligation"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_payment_task();

DROP TRIGGER IF EXISTS "FinancialObligation_task_after_update" ON "FinancialObligation";
CREATE TRIGGER "FinancialObligation_task_after_update"
AFTER UPDATE OF "status", "dueAt", "settledAmount", "workOrderId", "direction" ON "FinancialObligation"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_payment_task();

CREATE OR REPLACE FUNCTION turbolev_sync_qc_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'qc:' || NEW."id" || ':action';
  assignee TEXT;
  title TEXT;
  priority TEXT;
  due_at TIMESTAMP(3);
BEGIN
  assignee := turbolev_task_assignee_for_work_order(NEW."workOrderId");

  IF NEW."status"::text = 'PENDING' THEN
    title := 'Проконтролювати проведення контролю якості';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '1 hour';
  ELSIF NEW."status"::text = 'IN_PROGRESS' THEN
    title := 'Завершити контроль якості автомобіля';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '2 hours';
  ELSIF NEW."status"::text = 'FAILED' THEN
    title := 'QC не пройдено: організувати усунення зауважень';
    priority := 'CRITICAL';
    due_at := CURRENT_TIMESTAMP + INTERVAL '30 minutes';
  ELSIF NEW."status"::text = 'RECHECK' THEN
    title := 'Провести повторний контроль якості';
    priority := 'CRITICAL';
    due_at := CURRENT_TIMESTAMP + INTERVAL '1 hour';
  ELSE
    PERFORM turbolev_close_process_task(task_key);
    RETURN NEW;
  END IF;

  PERFORM turbolev_upsert_process_task(
    task_key, title, priority, assignee, due_at,
    'QC', NEW."id", NEW."workOrderId", 'qc', 'Замовлення-наряди', NEW."status"::text
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "WorkOrderQualityControl_task_after_insert" ON "WorkOrderQualityControl";
CREATE TRIGGER "WorkOrderQualityControl_task_after_insert"
AFTER INSERT ON "WorkOrderQualityControl"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_qc_task();

DROP TRIGGER IF EXISTS "WorkOrderQualityControl_task_after_update" ON "WorkOrderQualityControl";
CREATE TRIGGER "WorkOrderQualityControl_task_after_update"
AFTER UPDATE OF "status", "workOrderId" ON "WorkOrderQualityControl"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_qc_task();

CREATE OR REPLACE FUNCTION turbolev_sync_warranty_task()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  task_key TEXT := 'warranty:' || NEW."id" || ':action';
  work_order_id TEXT;
  assignee TEXT;
  title TEXT;
  priority TEXT;
  due_at TIMESTAMP(3);
BEGIN
  SELECT wol."workOrderId" INTO work_order_id
    FROM "WorkOrderLine" wol
   WHERE wol."id" = NEW."workOrderLineId"
   LIMIT 1;

  assignee := COALESCE(NEW."openedByUserId", turbolev_task_assignee_for_work_order(work_order_id));

  IF NEW."status"::text = 'OPEN' THEN
    title := 'Опрацювати нове гарантійне звернення';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '2 hours';
  ELSIF NEW."status"::text = 'REVIEW' THEN
    title := 'Прийняти рішення по гарантійному зверненню';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '4 hours';
  ELSIF NEW."status"::text = 'APPROVED' THEN
    title := 'Організувати виконання гарантійних робіт';
    priority := 'HIGH';
    due_at := CURRENT_TIMESTAMP + INTERVAL '1 day';
  ELSE
    PERFORM turbolev_close_process_task(task_key);
    RETURN NEW;
  END IF;

  PERFORM turbolev_upsert_process_task(
    task_key, title, priority, assignee, due_at,
    'WARRANTY', NEW."id", work_order_id, NULL, 'Гарантії', NEW."status"::text
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "WarrantyClaim_task_after_insert" ON "WarrantyClaim";
CREATE TRIGGER "WarrantyClaim_task_after_insert"
AFTER INSERT ON "WarrantyClaim"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_warranty_task();

DROP TRIGGER IF EXISTS "WarrantyClaim_task_after_update" ON "WarrantyClaim";
CREATE TRIGGER "WarrantyClaim_task_after_update"
AFTER UPDATE OF "status", "openedByUserId", "workOrderLineId" ON "WarrantyClaim"
FOR EACH ROW EXECUTE FUNCTION turbolev_sync_warranty_task();

-- Backfill currently active process records without changing business values.
UPDATE "WorkOrderEstimate"
   SET "status" = "status"
 WHERE "status"::text IN ('DRAFT', 'SENT');

UPDATE "PartsRequest"
   SET "status" = "status"
 WHERE "status"::text IN ('NEW', 'SELECTING', 'SELECTED', 'WAITING_APPROVAL', 'APPROVED', 'ORDER_REQUIRED', 'ORDERED', 'PARTIALLY_RECEIVED');

UPDATE "FinancialObligation"
   SET "status" = "status"
 WHERE "direction"::text = 'RECEIVABLE'
   AND "workOrderId" IS NOT NULL
   AND "status"::text IN ('OPEN', 'PARTIALLY_PAID', 'OVERDUE');

UPDATE "WorkOrderQualityControl"
   SET "status" = "status"
 WHERE "status"::text IN ('PENDING', 'IN_PROGRESS', 'FAILED', 'RECHECK');

UPDATE "WarrantyClaim"
   SET "status" = "status"
 WHERE "status"::text IN ('OPEN', 'REVIEW', 'APPROVED');
