import { NextRequest, NextResponse } from "next/server";
import { randomBytes, randomUUID, scryptSync } from "node:crypto";
import { getPrisma } from "@/src/lib/prisma";

export const runtime="nodejs";
export const dynamic="force-dynamic";

function hashPassword(value:string){const salt=randomBytes(16).toString("hex");const hash=scryptSync(value,salt,64).toString("hex");return `${salt}:${hash}`}
function n(value:unknown){if(value===""||value==null)return null;const x=Number(value);return Number.isFinite(x)?x:null}
function bodyToData(body:any){return{firstName:String(body.firstName||"").trim(),lastName:String(body.lastName||"").trim(),birthDate:body.birthDate?new Date(`${body.birthDate}T00:00:00`):null,email:body.email?String(body.email).trim():null,phone:body.phone?String(body.phone).trim():null,phoneCountry:body.phoneCountry?String(body.phoneCountry):"UA",address:body.address?String(body.address).trim():null,photoUrl:body.photoUrl?String(body.photoUrl):null,personnelCategory:body.personnelCategory?String(body.personnelCategory):null,position:body.position?String(body.position):null,crmLogin:body.crmLogin?String(body.crmLogin).trim():null,isActive:body.isActive!==false,baseSalary:n(body.baseSalary),minimumSalary:n(body.minimumSalary),workPercent:n(body.workPercent),partsSalesPercent:n(body.partsSalesPercent),partsMarginPercent:n(body.partsMarginPercent),netProfitPercent:n(body.netProfitPercent),payrollRuleNote:body.payrollRuleNote?String(body.payrollRuleNote):null}}

export async function GET(){const prisma=getPrisma();try{const items=await prisma.employeeProfile.findMany({orderBy:[{isActive:"desc"},{lastName:"asc"},{firstName:"asc"}],include:{documents:{orderBy:{name:"asc"}}}});return NextResponse.json({ok:true,items},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error("personnel GET failed",e);return NextResponse.json({ok:false,error:"Не вдалося завантажити персонал."},{status:500})}}

export async function POST(request:NextRequest){const prisma=getPrisma();try{const body=await request.json();const data=bodyToData(body);if(!data.firstName||!data.lastName)return NextResponse.json({ok:false,error:"Вкажіть ім’я та прізвище."},{status:400});const created=await prisma.employeeProfile.create({data:{id:randomUUID(),...data,crmPasswordHash:body.password?hashPassword(String(body.password)):null,documents:{create:(Array.isArray(body.documents)?body.documents:[]).map((d:any)=>({id:randomUUID(),type:String(d.type||"OTHER"),name:String(d.name||"Документ"),status:String(d.status||"MISSING"),fileUrl:d.fileUrl?String(d.fileUrl):null,uploadedAt:d.status==="UPLOADED"?new Date():null}))}},include:{documents:true}});return NextResponse.json({ok:true,item:created})}catch(e){console.error("personnel POST failed",e);return NextResponse.json({ok:false,error:"Не вдалося створити співробітника. Перевірте унікальність e-mail/логіну."},{status:500})}}

export async function PUT(request:NextRequest){const prisma=getPrisma();try{const body=await request.json();const id=String(body.id||"");if(!id)return NextResponse.json({ok:false,error:"Не вказано співробітника."},{status:400});const data:any=bodyToData(body);if(body.password)data.crmPasswordHash=hashPassword(String(body.password));const documents=Array.isArray(body.documents)?body.documents:[];const item=await prisma.$transaction(async(tx)=>{await tx.employeeDocument.deleteMany({where:{employeeId:id}});await tx.employeeProfile.update({where:{id},data});if(documents.length)await tx.employeeDocument.createMany({data:documents.map((d:any)=>({id:randomUUID(),employeeId:id,type:String(d.type||"OTHER"),name:String(d.name||"Документ"),status:String(d.status||"MISSING"),fileUrl:d.fileUrl?String(d.fileUrl):null,uploadedAt:d.status==="UPLOADED"?new Date():null}))});return tx.employeeProfile.findUniqueOrThrow({where:{id},include:{documents:true}})});return NextResponse.json({ok:true,item})}catch(e){console.error("personnel PUT failed",e);return NextResponse.json({ok:false,error:"Не вдалося оновити співробітника."},{status:500})}}

export async function DELETE(request:NextRequest){const prisma=getPrisma();const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({ok:false,error:"Не вказано співробітника."},{status:400});try{await prisma.employeeProfile.delete({where:{id}});return NextResponse.json({ok:true})}catch(e){console.error("personnel DELETE failed",e);return NextResponse.json({ok:false,error:"Не вдалося видалити співробітника."},{status:500})}}
