import assert from "node:assert/strict";
import { finalizeAttentionIncidents } from "../src/domain/attention-incidents";
import type { AttentionCenterResult, AttentionSignal } from "../src/services/attention-center.service";

const now = new Date("2026-10-06T12:00:00.000Z");

function signal(partial: Partial<AttentionSignal> & Pick<AttentionSignal, "id" | "title">): AttentionSignal {
  return {
    id: partial.id,
    sourceType: partial.sourceType || "APPOINTMENT",
    sourceId: partial.sourceId ?? "apt-1",
    taskId: partial.taskId ?? null,
    title: partial.title,
    description: partial.description ?? null,
    reason: partial.reason || "test",
    category: partial.category || "SERVICE",
    level: partial.level || "HIGH",
    bucket: partial.bucket || "ACTION",
    dueAt: partial.dueAt ?? "2026-10-06T10:00:00.000Z",
    occurredAt: partial.occurredAt || "2026-10-06T09:00:00.000Z",
    isOverdue: partial.isOverdue ?? true,
    overdueMinutes: partial.overdueMinutes ?? 120,
    isToday: partial.isToday ?? true,
    autoGenerated: partial.autoGenerated ?? true,
    amount: partial.amount ?? null,
    currency: partial.currency ?? null,
    counterparty: partial.counterparty ?? "Клієнт",
    action: partial.action ?? { label: "Відкрити запис", section: "Планувальник", params: { appointmentId: partial.sourceId ?? "apt-1" } },
    metadata: partial.metadata || { plateNumber: "AA 0001 AA", status: "BOOKED" },
  };
}

const raw: AttentionSignal[] = [
  signal({
    id: "appointment:apt-1:arrival",
    sourceId: "apt-1",
    title: "AA 0001 AA: не підтверджено приїзд",
    reason: "Прибуття не зафіксовано.",
    metadata: { plateNumber: "AA 0001 AA", status: "BOOKED" },
  }),
  signal({
    id: "appointment:apt-1:stale-booked",
    sourceId: "apt-1",
    title: "AA 0001 AA: час запису минув, статус досі BOOKED",
    reason: "Статус не змінено.",
    metadata: { plateNumber: "AA 0001 AA", status: "BOOKED", attentionReason: "STALE_BOOKED" },
  }),
  signal({
    id: "appointment:old:no-show",
    sourceId: "old",
    title: "BB 0002 BB: клієнт не приїхав",
    reason: "Старий no-show.",
    dueAt: "2026-09-20T10:00:00.000Z",
    occurredAt: "2026-09-20T10:00:00.000Z",
    overdueMinutes: 23_000,
    isToday: false,
    level: "CRITICAL",
    metadata: { plateNumber: "BB 0002 BB", status: "NO_SHOW" },
    action: { label: "Відкрити запис", section: "Планувальник", params: { appointmentId: "old" } },
  }),
  signal({
    id: "post-load:today",
    sourceType: "POST_LOAD",
    sourceId: "2026-10-06",
    title: "Низьке завантаження постів сьогодні",
    category: "POSTS",
    bucket: "ACTION",
    level: "HIGH",
    metadata: { utilizationPct: 20 },
    action: { label: "Відкрити планувальник", section: "Планувальник" },
  }),
];

const center: AttentionCenterResult = {
  signals: raw,
  summary: { total: 4, critical: 1, overdue: 4, action: 4, waiting: 0, today: 3 },
  categories: {
    COMMUNICATIONS: 0,
    SERVICE: 3,
    DIAGNOSTICS: 0,
    PARTS: 0,
    SUPPLIERS: 0,
    FINANCE: 0,
    PAYROLL: 0,
    POSTS: 1,
    QUALITY: 0,
    WARRANTY: 0,
    MANUAL: 0,
  },
  postLoad: { today: null, tomorrow: null },
  generatedAt: now.toISOString(),
};

const result = finalizeAttentionIncidents(center, now) as AttentionCenterResult & { rawSignalCount?: number };

assert.equal(result.rawSignalCount, 4);
assert.equal(result.summary.total, 3, "two appointment signals must collapse into one incident");

const arrivalIncident = result.signals.find((item) => item.id === "incident:appointment:apt-1");
assert.ok(arrivalIncident, "collapsed appointment incident should exist");
assert.match(arrivalIncident.title, /не визначено результат запланованого приїзду/i);
assert.equal(arrivalIncident.metadata.relatedSignalCount, 2);
assert.equal(arrivalIncident.metadata.incidentClass, "OPERATIONS");
assert.equal(arrivalIncident.metadata.stageLabel, "Запис / приїзд");

const oldIncident = result.signals.find((item) => item.id === "incident:appointment:old");
assert.ok(oldIncident, "old appointment incident should exist");
assert.equal(oldIncident.metadata.incidentClass, "DATA_CLEANUP");
assert.equal(oldIncident.level, "MEDIUM");
assert.equal(oldIncident.bucket, "MONITORING");

const postSignal = result.signals.find((item) => item.sourceType === "POST_LOAD");
assert.ok(postSignal, "non vehicle operational signal must remain separate");
assert.equal(postSignal.metadata.incident, false);

console.log("attention-incidents-contract-smoke: ok");
