ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONTACTED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'QUALIFIED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'ESTIMATE';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'WAITING';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NO_ANSWER';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'LOST';

ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'INSTAGRAM';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'FACEBOOK';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'GOOGLE_MAPS';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'VIBER';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'WHATSAPP';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'OLX';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'TIKTOK';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'REFERRAL';

ALTER TABLE "Lead"
  ADD COLUMN IF NOT EXISTS "carYear" INTEGER,
  ADD COLUMN IF NOT EXISTS "plateNumber" VARCHAR(24),
  ADD COLUMN IF NOT EXISTS "need" TEXT,
  ADD COLUMN IF NOT EXISTS "nextAction" TEXT,
  ADD COLUMN IF NOT EXISTS "contactAttempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "preliminaryAmount" DECIMAL(14,2);

CREATE INDEX IF NOT EXISTS "Lead_lastActivityAt_idx" ON "Lead"("lastActivityAt");
CREATE INDEX IF NOT EXISTS "Lead_plateNumber_idx" ON "Lead"("plateNumber");

CREATE TABLE IF NOT EXISTS "AuditEvent" (
  "id" TEXT NOT NULL,
  "actorId" VARCHAR(64),
  "actorName" VARCHAR(160),
  "entityType" VARCHAR(64) NOT NULL,
  "entityId" VARCHAR(96) NOT NULL,
  "action" VARCHAR(64) NOT NULL,
  "before" JSONB,
  "after" JSONB,
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "AuditEvent_entityType_entityId_createdAt_idx" ON "AuditEvent"("entityType","entityId","createdAt");
CREATE INDEX IF NOT EXISTS "AuditEvent_actorId_createdAt_idx" ON "AuditEvent"("actorId","createdAt");
CREATE INDEX IF NOT EXISTS "AuditEvent_action_createdAt_idx" ON "AuditEvent"("action","createdAt");

UPDATE "Lead" SET "lastActivityAt" = COALESCE("updatedAt", "createdAt", CURRENT_TIMESTAMP) WHERE "lastActivityAt" IS NULL;
