export const PERMISSIONS = {
  OVERVIEW_READ: "OVERVIEW.READ",
  COMMUNICATIONS_READ: "COMMUNICATIONS.READ",
  COMMUNICATIONS_WRITE: "COMMUNICATIONS.WRITE",
  LEADS_READ: "LEADS.READ",
  LEADS_WRITE: "LEADS.WRITE",
  LEADS_ASSIGN: "LEADS.ASSIGN",
  CLIENTS_READ: "CLIENTS.READ",
  CLIENTS_WRITE: "CLIENTS.WRITE",
  PLANNER_READ: "PLANNER.READ",
  PLANNER_WRITE: "PLANNER.WRITE",
  DIAGNOSTICS_READ: "DIAGNOSTICS.READ",
  DIAGNOSTICS_WRITE: "DIAGNOSTICS.WRITE",
  DIAGNOSTICS_CONFIRM: "DIAGNOSTICS.CONFIRM",
  WORK_ORDERS_READ: "WORK_ORDERS.READ",
  WORK_ORDERS_WRITE: "WORK_ORDERS.WRITE",
  WORK_ORDERS_ESTIMATE: "WORK_ORDERS.ESTIMATE",
  PRODUCTION_READ: "PRODUCTION.READ",
  PRODUCTION_WRITE: "PRODUCTION.WRITE",
  QC_READ: "QC.READ",
  QC_WRITE: "QC.WRITE",
  PARTS_READ: "PARTS.READ",
  PARTS_WRITE: "PARTS.WRITE",
  PROCUREMENT_READ: "PROCUREMENT.READ",
  PROCUREMENT_WRITE: "PROCUREMENT.WRITE",
  FINANCE_READ: "FINANCE.READ",
  FINANCE_WRITE: "FINANCE.WRITE",
  PAYMENTS_READ: "PAYMENTS.READ",
  PAYMENTS_WRITE: "PAYMENTS.WRITE",
  PAYROLL_SELF_READ: "PAYROLL.SELF_READ",
  PAYROLL_ALL_READ: "PAYROLL.ALL_READ",
  PAYROLL_WRITE: "PAYROLL.WRITE",
  PAYROLL_CLOSE: "PAYROLL.CLOSE",
  PERSONNEL_READ: "PERSONNEL.READ",
  PERSONNEL_WRITE: "PERSONNEL.WRITE",
  PERSONNEL_COMPENSATION_READ: "PERSONNEL.COMPENSATION_READ",
  WARRANTY_READ: "WARRANTY.READ",
  WARRANTY_WRITE: "WARRANTY.WRITE",
  ANALYTICS_READ: "ANALYTICS.READ",
  ANALYTICS_PERSONNEL_READ: "ANALYTICS.PERSONNEL_READ",
  ANALYTICS_FINANCIAL_READ: "ANALYTICS.FINANCIAL_READ",
  SETTINGS_READ: "SETTINGS.READ",
  SETTINGS_WRITE: "SETTINGS.WRITE",
  SETTINGS_INTEGRATIONS: "SETTINGS.INTEGRATIONS",
  AUDIT_READ: "AUDIT.READ",
  SECURITY_ACCESS_MANAGE: "SECURITY.ACCESS_MANAGE",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export type AccessScopeCode = "SELF" | "ASSIGNED" | "TEAM" | "LOCATION" | "ALL";

const SCOPE_RANK: Record<AccessScopeCode, number> = {
  SELF: 1,
  ASSIGNED: 2,
  TEAM: 3,
  LOCATION: 4,
  ALL: 5,
};

export function widerScope(a: AccessScopeCode, b: AccessScopeCode): AccessScopeCode {
  return SCOPE_RANK[a] >= SCOPE_RANK[b] ? a : b;
}

export function scopeCovers(actual: AccessScopeCode | null | undefined, required: AccessScopeCode) {
  return Boolean(actual) && SCOPE_RANK[actual!] >= SCOPE_RANK[required];
}

export const NAV_PERMISSION: Record<string, PermissionCode> = {
  overview: PERMISSIONS.OVERVIEW_READ,
  tasks: PERMISSIONS.OVERVIEW_READ,
  inquiries: PERMISSIONS.COMMUNICATIONS_READ,
  communications: PERMISSIONS.COMMUNICATIONS_READ,
  leads: PERMISSIONS.LEADS_READ,
  clients: PERMISSIONS.CLIENTS_READ,
  vehicles: PERMISSIONS.CLIENTS_READ,
  planner: PERMISSIONS.PLANNER_READ,
  diagnostics: PERMISSIONS.DIAGNOSTICS_READ,
  "work-orders": PERMISSIONS.WORK_ORDERS_READ,
  production: PERMISSIONS.PRODUCTION_READ,
  quality: PERMISSIONS.QC_READ,
  parts: PERMISSIONS.PARTS_READ,
  procurement: PERMISSIONS.PROCUREMENT_READ,
  finance: PERMISSIONS.FINANCE_READ,
  payments: PERMISSIONS.PAYMENTS_READ,
  warranties: PERMISSIONS.WARRANTY_READ,
  analytics: PERMISSIONS.ANALYTICS_READ,
  settings: PERMISSIONS.SETTINGS_READ,
};
